// Code generated by ent, DO NOT EDIT.

package village

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the village type in the database.
	Label = "village"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldContribution holds the string denoting the contribution field in the database.
	FieldContribution = "contribution"
	// FieldMemberCount holds the string denoting the member_count field in the database.
	FieldMemberCount = "member_count"
	// FieldMaxMembers holds the string denoting the max_members field in the database.
	FieldMaxMembers = "max_members"
	// FieldSpecialty holds the string denoting the specialty field in the database.
	FieldSpecialty = "specialty"
	// EdgeMembers holds the string denoting the members edge name in mutations.
	EdgeMembers = "members"
	// EdgeProjects holds the string denoting the projects edge name in mutations.
	EdgeProjects = "projects"
	// Table holds the table name of the village in the database.
	Table = "villages"
	// MembersTable is the table that holds the members relation/edge.
	MembersTable = "village_members"
	// MembersInverseTable is the table name for the VillageMember entity.
	// It exists in this package in order to avoid circular dependency with the "villagemember" package.
	MembersInverseTable = "village_members"
	// MembersColumn is the table column denoting the members relation/edge.
	MembersColumn = "village_id"
	// ProjectsTable is the table that holds the projects relation/edge.
	ProjectsTable = "village_projects"
	// ProjectsInverseTable is the table name for the VillageProject entity.
	// It exists in this package in order to avoid circular dependency with the "villageproject" package.
	ProjectsInverseTable = "village_projects"
	// ProjectsColumn is the table column denoting the projects relation/edge.
	ProjectsColumn = "village_id"
)

// Columns holds all SQL columns for village fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldName,
	FieldLevel,
	FieldContribution,
	FieldMemberCount,
	FieldMaxMembers,
	FieldSpecialty,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultLevel holds the default value on creation for the "level" field.
	DefaultLevel int
	// LevelValidator is a validator for the "level" field. It is called by the builders before save.
	LevelValidator func(int) error
	// DefaultContribution holds the default value on creation for the "contribution" field.
	DefaultContribution int64
	// ContributionValidator is a validator for the "contribution" field. It is called by the builders before save.
	ContributionValidator func(int64) error
	// DefaultMemberCount holds the default value on creation for the "member_count" field.
	DefaultMemberCount int
	// MemberCountValidator is a validator for the "member_count" field. It is called by the builders before save.
	MemberCountValidator func(int) error
	// DefaultMaxMembers holds the default value on creation for the "max_members" field.
	DefaultMaxMembers int
	// DefaultSpecialty holds the default value on creation for the "specialty" field.
	DefaultSpecialty []string
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Village queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByLevel orders the results by the level field.
func ByLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevel, opts...).ToFunc()
}

// ByContribution orders the results by the contribution field.
func ByContribution(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldContribution, opts...).ToFunc()
}

// ByMemberCount orders the results by the member_count field.
func ByMemberCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMemberCount, opts...).ToFunc()
}

// ByMaxMembers orders the results by the max_members field.
func ByMaxMembers(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMaxMembers, opts...).ToFunc()
}

// ByMembersCount orders the results by members count.
func ByMembersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newMembersStep(), opts...)
	}
}

// ByMembers orders the results by members terms.
func ByMembers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newMembersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProjectsCount orders the results by projects count.
func ByProjectsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProjectsStep(), opts...)
	}
}

// ByProjects orders the results by projects terms.
func ByProjects(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProjectsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newMembersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(MembersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, MembersTable, MembersColumn),
	)
}
func newProjectsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProjectsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, ProjectsTable, ProjectsColumn),
	)
}
