// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/activitycomment"
	"github.com/liukai/farmer/server/ent/activitylike"
	"github.com/liukai/farmer/server/ent/activitylog"
	"github.com/liukai/farmer/server/ent/user"
)

// ActivityLogCreate is the builder for creating a ActivityLog entity.
type ActivityLogCreate struct {
	config
	mutation *ActivityLogMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *ActivityLogCreate) SetUserID(v uuid.UUID) *ActivityLogCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetVillageID sets the "village_id" field.
func (_c *ActivityLogCreate) SetVillageID(v uuid.UUID) *ActivityLogCreate {
	_c.mutation.SetVillageID(v)
	return _c
}

// SetNillableVillageID sets the "village_id" field if the given value is not nil.
func (_c *ActivityLogCreate) SetNillableVillageID(v *uuid.UUID) *ActivityLogCreate {
	if v != nil {
		_c.SetVillageID(*v)
	}
	return _c
}

// SetType sets the "type" field.
func (_c *ActivityLogCreate) SetType(v string) *ActivityLogCreate {
	_c.mutation.SetType(v)
	return _c
}

// SetContent sets the "content" field.
func (_c *ActivityLogCreate) SetContent(v string) *ActivityLogCreate {
	_c.mutation.SetContent(v)
	return _c
}

// SetMeta sets the "meta" field.
func (_c *ActivityLogCreate) SetMeta(v map[string]interface{}) *ActivityLogCreate {
	_c.mutation.SetMeta(v)
	return _c
}

// SetLikeCount sets the "like_count" field.
func (_c *ActivityLogCreate) SetLikeCount(v int) *ActivityLogCreate {
	_c.mutation.SetLikeCount(v)
	return _c
}

// SetNillableLikeCount sets the "like_count" field if the given value is not nil.
func (_c *ActivityLogCreate) SetNillableLikeCount(v *int) *ActivityLogCreate {
	if v != nil {
		_c.SetLikeCount(*v)
	}
	return _c
}

// SetCommentCount sets the "comment_count" field.
func (_c *ActivityLogCreate) SetCommentCount(v int) *ActivityLogCreate {
	_c.mutation.SetCommentCount(v)
	return _c
}

// SetNillableCommentCount sets the "comment_count" field if the given value is not nil.
func (_c *ActivityLogCreate) SetNillableCommentCount(v *int) *ActivityLogCreate {
	if v != nil {
		_c.SetCommentCount(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *ActivityLogCreate) SetCreatedAt(v time.Time) *ActivityLogCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *ActivityLogCreate) SetNillableCreatedAt(v *time.Time) *ActivityLogCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *ActivityLogCreate) SetID(v uuid.UUID) *ActivityLogCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *ActivityLogCreate) SetNillableID(v *uuid.UUID) *ActivityLogCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetAuthorID sets the "author" edge to the User entity by ID.
func (_c *ActivityLogCreate) SetAuthorID(id uuid.UUID) *ActivityLogCreate {
	_c.mutation.SetAuthorID(id)
	return _c
}

// SetAuthor sets the "author" edge to the User entity.
func (_c *ActivityLogCreate) SetAuthor(v *User) *ActivityLogCreate {
	return _c.SetAuthorID(v.ID)
}

// AddLikeIDs adds the "likes" edge to the ActivityLike entity by IDs.
func (_c *ActivityLogCreate) AddLikeIDs(ids ...uuid.UUID) *ActivityLogCreate {
	_c.mutation.AddLikeIDs(ids...)
	return _c
}

// AddLikes adds the "likes" edges to the ActivityLike entity.
func (_c *ActivityLogCreate) AddLikes(v ...*ActivityLike) *ActivityLogCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddLikeIDs(ids...)
}

// AddCommentIDs adds the "comments" edge to the ActivityComment entity by IDs.
func (_c *ActivityLogCreate) AddCommentIDs(ids ...uuid.UUID) *ActivityLogCreate {
	_c.mutation.AddCommentIDs(ids...)
	return _c
}

// AddComments adds the "comments" edges to the ActivityComment entity.
func (_c *ActivityLogCreate) AddComments(v ...*ActivityComment) *ActivityLogCreate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddCommentIDs(ids...)
}

// Mutation returns the ActivityLogMutation object of the builder.
func (_c *ActivityLogCreate) Mutation() *ActivityLogMutation {
	return _c.mutation
}

// Save creates the ActivityLog in the database.
func (_c *ActivityLogCreate) Save(ctx context.Context) (*ActivityLog, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *ActivityLogCreate) SaveX(ctx context.Context) *ActivityLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActivityLogCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActivityLogCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *ActivityLogCreate) defaults() {
	if _, ok := _c.mutation.Meta(); !ok {
		v := activitylog.DefaultMeta
		_c.mutation.SetMeta(v)
	}
	if _, ok := _c.mutation.LikeCount(); !ok {
		v := activitylog.DefaultLikeCount
		_c.mutation.SetLikeCount(v)
	}
	if _, ok := _c.mutation.CommentCount(); !ok {
		v := activitylog.DefaultCommentCount
		_c.mutation.SetCommentCount(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := activitylog.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := activitylog.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *ActivityLogCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "ActivityLog.user_id"`)}
	}
	if _, ok := _c.mutation.GetType(); !ok {
		return &ValidationError{Name: "type", err: errors.New(`ent: missing required field "ActivityLog.type"`)}
	}
	if v, ok := _c.mutation.GetType(); ok {
		if err := activitylog.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.type": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Content(); !ok {
		return &ValidationError{Name: "content", err: errors.New(`ent: missing required field "ActivityLog.content"`)}
	}
	if _, ok := _c.mutation.Meta(); !ok {
		return &ValidationError{Name: "meta", err: errors.New(`ent: missing required field "ActivityLog.meta"`)}
	}
	if _, ok := _c.mutation.LikeCount(); !ok {
		return &ValidationError{Name: "like_count", err: errors.New(`ent: missing required field "ActivityLog.like_count"`)}
	}
	if v, ok := _c.mutation.LikeCount(); ok {
		if err := activitylog.LikeCountValidator(v); err != nil {
			return &ValidationError{Name: "like_count", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.like_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CommentCount(); !ok {
		return &ValidationError{Name: "comment_count", err: errors.New(`ent: missing required field "ActivityLog.comment_count"`)}
	}
	if v, ok := _c.mutation.CommentCount(); ok {
		if err := activitylog.CommentCountValidator(v); err != nil {
			return &ValidationError{Name: "comment_count", err: fmt.Errorf(`ent: validator failed for field "ActivityLog.comment_count": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "ActivityLog.created_at"`)}
	}
	if len(_c.mutation.AuthorIDs()) == 0 {
		return &ValidationError{Name: "author", err: errors.New(`ent: missing required edge "ActivityLog.author"`)}
	}
	return nil
}

func (_c *ActivityLogCreate) sqlSave(ctx context.Context) (*ActivityLog, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *ActivityLogCreate) createSpec() (*ActivityLog, *sqlgraph.CreateSpec) {
	var (
		_node = &ActivityLog{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(activitylog.Table, sqlgraph.NewFieldSpec(activitylog.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.VillageID(); ok {
		_spec.SetField(activitylog.FieldVillageID, field.TypeUUID, value)
		_node.VillageID = &value
	}
	if value, ok := _c.mutation.GetType(); ok {
		_spec.SetField(activitylog.FieldType, field.TypeString, value)
		_node.Type = value
	}
	if value, ok := _c.mutation.Content(); ok {
		_spec.SetField(activitylog.FieldContent, field.TypeString, value)
		_node.Content = value
	}
	if value, ok := _c.mutation.Meta(); ok {
		_spec.SetField(activitylog.FieldMeta, field.TypeJSON, value)
		_node.Meta = value
	}
	if value, ok := _c.mutation.LikeCount(); ok {
		_spec.SetField(activitylog.FieldLikeCount, field.TypeInt, value)
		_node.LikeCount = value
	}
	if value, ok := _c.mutation.CommentCount(); ok {
		_spec.SetField(activitylog.FieldCommentCount, field.TypeInt, value)
		_node.CommentCount = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(activitylog.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.AuthorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   activitylog.AuthorTable,
			Columns: []string{activitylog.AuthorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.LikesIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitylog.LikesTable,
			Columns: []string{activitylog.LikesColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activitylike.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.CommentsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   activitylog.CommentsTable,
			Columns: []string{activitylog.CommentsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(activitycomment.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// ActivityLogCreateBulk is the builder for creating many ActivityLog entities in bulk.
type ActivityLogCreateBulk struct {
	config
	err      error
	builders []*ActivityLogCreate
}

// Save creates the ActivityLog entities in the database.
func (_c *ActivityLogCreateBulk) Save(ctx context.Context) ([]*ActivityLog, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*ActivityLog, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*ActivityLogMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *ActivityLogCreateBulk) SaveX(ctx context.Context) []*ActivityLog {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *ActivityLogCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *ActivityLogCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
