// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/animal"
	"github.com/liukai/farmer/server/ent/farm"
	"github.com/liukai/farmer/server/ent/predicate"
)

// AnimalUpdate is the builder for updating Animal entities.
type AnimalUpdate struct {
	config
	hooks    []Hook
	mutation *AnimalMutation
}

// Where appends a list predicates to the AnimalUpdate builder.
func (_u *AnimalUpdate) Where(ps ...predicate.Animal) *AnimalUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AnimalUpdate) SetUpdatedAt(v time.Time) *AnimalUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFarmID sets the "farm_id" field.
func (_u *AnimalUpdate) SetFarmID(v uuid.UUID) *AnimalUpdate {
	_u.mutation.SetFarmID(v)
	return _u
}

// SetNillableFarmID sets the "farm_id" field if the given value is not nil.
func (_u *AnimalUpdate) SetNillableFarmID(v *uuid.UUID) *AnimalUpdate {
	if v != nil {
		_u.SetFarmID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *AnimalUpdate) SetType(v string) *AnimalUpdate {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AnimalUpdate) SetNillableType(v *string) *AnimalUpdate {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AnimalUpdate) SetName(v string) *AnimalUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AnimalUpdate) SetNillableName(v *string) *AnimalUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *AnimalUpdate) ClearName() *AnimalUpdate {
	_u.mutation.ClearName()
	return _u
}

// SetMood sets the "mood" field.
func (_u *AnimalUpdate) SetMood(v int) *AnimalUpdate {
	_u.mutation.ResetMood()
	_u.mutation.SetMood(v)
	return _u
}

// SetNillableMood sets the "mood" field if the given value is not nil.
func (_u *AnimalUpdate) SetNillableMood(v *int) *AnimalUpdate {
	if v != nil {
		_u.SetMood(*v)
	}
	return _u
}

// AddMood adds value to the "mood" field.
func (_u *AnimalUpdate) AddMood(v int) *AnimalUpdate {
	_u.mutation.AddMood(v)
	return _u
}

// SetHealth sets the "health" field.
func (_u *AnimalUpdate) SetHealth(v int) *AnimalUpdate {
	_u.mutation.ResetHealth()
	_u.mutation.SetHealth(v)
	return _u
}

// SetNillableHealth sets the "health" field if the given value is not nil.
func (_u *AnimalUpdate) SetNillableHealth(v *int) *AnimalUpdate {
	if v != nil {
		_u.SetHealth(*v)
	}
	return _u
}

// AddHealth adds value to the "health" field.
func (_u *AnimalUpdate) AddHealth(v int) *AnimalUpdate {
	_u.mutation.AddHealth(v)
	return _u
}

// SetLastFedAt sets the "last_fed_at" field.
func (_u *AnimalUpdate) SetLastFedAt(v time.Time) *AnimalUpdate {
	_u.mutation.SetLastFedAt(v)
	return _u
}

// SetNillableLastFedAt sets the "last_fed_at" field if the given value is not nil.
func (_u *AnimalUpdate) SetNillableLastFedAt(v *time.Time) *AnimalUpdate {
	if v != nil {
		_u.SetLastFedAt(*v)
	}
	return _u
}

// ClearLastFedAt clears the value of the "last_fed_at" field.
func (_u *AnimalUpdate) ClearLastFedAt() *AnimalUpdate {
	_u.mutation.ClearLastFedAt()
	return _u
}

// SetLastCleanedAt sets the "last_cleaned_at" field.
func (_u *AnimalUpdate) SetLastCleanedAt(v time.Time) *AnimalUpdate {
	_u.mutation.SetLastCleanedAt(v)
	return _u
}

// SetNillableLastCleanedAt sets the "last_cleaned_at" field if the given value is not nil.
func (_u *AnimalUpdate) SetNillableLastCleanedAt(v *time.Time) *AnimalUpdate {
	if v != nil {
		_u.SetLastCleanedAt(*v)
	}
	return _u
}

// ClearLastCleanedAt clears the value of the "last_cleaned_at" field.
func (_u *AnimalUpdate) ClearLastCleanedAt() *AnimalUpdate {
	_u.mutation.ClearLastCleanedAt()
	return _u
}

// SetLastProductAt sets the "last_product_at" field.
func (_u *AnimalUpdate) SetLastProductAt(v time.Time) *AnimalUpdate {
	_u.mutation.SetLastProductAt(v)
	return _u
}

// SetNillableLastProductAt sets the "last_product_at" field if the given value is not nil.
func (_u *AnimalUpdate) SetNillableLastProductAt(v *time.Time) *AnimalUpdate {
	if v != nil {
		_u.SetLastProductAt(*v)
	}
	return _u
}

// ClearLastProductAt clears the value of the "last_product_at" field.
func (_u *AnimalUpdate) ClearLastProductAt() *AnimalUpdate {
	_u.mutation.ClearLastProductAt()
	return _u
}

// SetFarm sets the "farm" edge to the Farm entity.
func (_u *AnimalUpdate) SetFarm(v *Farm) *AnimalUpdate {
	return _u.SetFarmID(v.ID)
}

// Mutation returns the AnimalMutation object of the builder.
func (_u *AnimalUpdate) Mutation() *AnimalMutation {
	return _u.mutation
}

// ClearFarm clears the "farm" edge to the Farm entity.
func (_u *AnimalUpdate) ClearFarm() *AnimalUpdate {
	_u.mutation.ClearFarm()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AnimalUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnimalUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AnimalUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnimalUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AnimalUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := animal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnimalUpdate) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := animal.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Animal.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := animal.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Animal.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mood(); ok {
		if err := animal.MoodValidator(v); err != nil {
			return &ValidationError{Name: "mood", err: fmt.Errorf(`ent: validator failed for field "Animal.mood": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Health(); ok {
		if err := animal.HealthValidator(v); err != nil {
			return &ValidationError{Name: "health", err: fmt.Errorf(`ent: validator failed for field "Animal.health": %w`, err)}
		}
	}
	if _u.mutation.FarmCleared() && len(_u.mutation.FarmIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Animal.farm"`)
	}
	return nil
}

func (_u *AnimalUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(animal.Table, animal.Columns, sqlgraph.NewFieldSpec(animal.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(animal.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(animal.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(animal.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(animal.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Mood(); ok {
		_spec.SetField(animal.FieldMood, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMood(); ok {
		_spec.AddField(animal.FieldMood, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Health(); ok {
		_spec.SetField(animal.FieldHealth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHealth(); ok {
		_spec.AddField(animal.FieldHealth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastFedAt(); ok {
		_spec.SetField(animal.FieldLastFedAt, field.TypeTime, value)
	}
	if _u.mutation.LastFedAtCleared() {
		_spec.ClearField(animal.FieldLastFedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastCleanedAt(); ok {
		_spec.SetField(animal.FieldLastCleanedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCleanedAtCleared() {
		_spec.ClearField(animal.FieldLastCleanedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastProductAt(); ok {
		_spec.SetField(animal.FieldLastProductAt, field.TypeTime, value)
	}
	if _u.mutation.LastProductAtCleared() {
		_spec.ClearField(animal.FieldLastProductAt, field.TypeTime)
	}
	if _u.mutation.FarmCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   animal.FarmTable,
			Columns: []string{animal.FarmColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(farm.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FarmIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   animal.FarmTable,
			Columns: []string{animal.FarmColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(farm.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{animal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AnimalUpdateOne is the builder for updating a single Animal entity.
type AnimalUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AnimalMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *AnimalUpdateOne) SetUpdatedAt(v time.Time) *AnimalUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFarmID sets the "farm_id" field.
func (_u *AnimalUpdateOne) SetFarmID(v uuid.UUID) *AnimalUpdateOne {
	_u.mutation.SetFarmID(v)
	return _u
}

// SetNillableFarmID sets the "farm_id" field if the given value is not nil.
func (_u *AnimalUpdateOne) SetNillableFarmID(v *uuid.UUID) *AnimalUpdateOne {
	if v != nil {
		_u.SetFarmID(*v)
	}
	return _u
}

// SetType sets the "type" field.
func (_u *AnimalUpdateOne) SetType(v string) *AnimalUpdateOne {
	_u.mutation.SetType(v)
	return _u
}

// SetNillableType sets the "type" field if the given value is not nil.
func (_u *AnimalUpdateOne) SetNillableType(v *string) *AnimalUpdateOne {
	if v != nil {
		_u.SetType(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *AnimalUpdateOne) SetName(v string) *AnimalUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *AnimalUpdateOne) SetNillableName(v *string) *AnimalUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// ClearName clears the value of the "name" field.
func (_u *AnimalUpdateOne) ClearName() *AnimalUpdateOne {
	_u.mutation.ClearName()
	return _u
}

// SetMood sets the "mood" field.
func (_u *AnimalUpdateOne) SetMood(v int) *AnimalUpdateOne {
	_u.mutation.ResetMood()
	_u.mutation.SetMood(v)
	return _u
}

// SetNillableMood sets the "mood" field if the given value is not nil.
func (_u *AnimalUpdateOne) SetNillableMood(v *int) *AnimalUpdateOne {
	if v != nil {
		_u.SetMood(*v)
	}
	return _u
}

// AddMood adds value to the "mood" field.
func (_u *AnimalUpdateOne) AddMood(v int) *AnimalUpdateOne {
	_u.mutation.AddMood(v)
	return _u
}

// SetHealth sets the "health" field.
func (_u *AnimalUpdateOne) SetHealth(v int) *AnimalUpdateOne {
	_u.mutation.ResetHealth()
	_u.mutation.SetHealth(v)
	return _u
}

// SetNillableHealth sets the "health" field if the given value is not nil.
func (_u *AnimalUpdateOne) SetNillableHealth(v *int) *AnimalUpdateOne {
	if v != nil {
		_u.SetHealth(*v)
	}
	return _u
}

// AddHealth adds value to the "health" field.
func (_u *AnimalUpdateOne) AddHealth(v int) *AnimalUpdateOne {
	_u.mutation.AddHealth(v)
	return _u
}

// SetLastFedAt sets the "last_fed_at" field.
func (_u *AnimalUpdateOne) SetLastFedAt(v time.Time) *AnimalUpdateOne {
	_u.mutation.SetLastFedAt(v)
	return _u
}

// SetNillableLastFedAt sets the "last_fed_at" field if the given value is not nil.
func (_u *AnimalUpdateOne) SetNillableLastFedAt(v *time.Time) *AnimalUpdateOne {
	if v != nil {
		_u.SetLastFedAt(*v)
	}
	return _u
}

// ClearLastFedAt clears the value of the "last_fed_at" field.
func (_u *AnimalUpdateOne) ClearLastFedAt() *AnimalUpdateOne {
	_u.mutation.ClearLastFedAt()
	return _u
}

// SetLastCleanedAt sets the "last_cleaned_at" field.
func (_u *AnimalUpdateOne) SetLastCleanedAt(v time.Time) *AnimalUpdateOne {
	_u.mutation.SetLastCleanedAt(v)
	return _u
}

// SetNillableLastCleanedAt sets the "last_cleaned_at" field if the given value is not nil.
func (_u *AnimalUpdateOne) SetNillableLastCleanedAt(v *time.Time) *AnimalUpdateOne {
	if v != nil {
		_u.SetLastCleanedAt(*v)
	}
	return _u
}

// ClearLastCleanedAt clears the value of the "last_cleaned_at" field.
func (_u *AnimalUpdateOne) ClearLastCleanedAt() *AnimalUpdateOne {
	_u.mutation.ClearLastCleanedAt()
	return _u
}

// SetLastProductAt sets the "last_product_at" field.
func (_u *AnimalUpdateOne) SetLastProductAt(v time.Time) *AnimalUpdateOne {
	_u.mutation.SetLastProductAt(v)
	return _u
}

// SetNillableLastProductAt sets the "last_product_at" field if the given value is not nil.
func (_u *AnimalUpdateOne) SetNillableLastProductAt(v *time.Time) *AnimalUpdateOne {
	if v != nil {
		_u.SetLastProductAt(*v)
	}
	return _u
}

// ClearLastProductAt clears the value of the "last_product_at" field.
func (_u *AnimalUpdateOne) ClearLastProductAt() *AnimalUpdateOne {
	_u.mutation.ClearLastProductAt()
	return _u
}

// SetFarm sets the "farm" edge to the Farm entity.
func (_u *AnimalUpdateOne) SetFarm(v *Farm) *AnimalUpdateOne {
	return _u.SetFarmID(v.ID)
}

// Mutation returns the AnimalMutation object of the builder.
func (_u *AnimalUpdateOne) Mutation() *AnimalMutation {
	return _u.mutation
}

// ClearFarm clears the "farm" edge to the Farm entity.
func (_u *AnimalUpdateOne) ClearFarm() *AnimalUpdateOne {
	_u.mutation.ClearFarm()
	return _u
}

// Where appends a list predicates to the AnimalUpdate builder.
func (_u *AnimalUpdateOne) Where(ps ...predicate.Animal) *AnimalUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AnimalUpdateOne) Select(field string, fields ...string) *AnimalUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Animal entity.
func (_u *AnimalUpdateOne) Save(ctx context.Context) (*Animal, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AnimalUpdateOne) SaveX(ctx context.Context) *Animal {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AnimalUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AnimalUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *AnimalUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := animal.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AnimalUpdateOne) check() error {
	if v, ok := _u.mutation.GetType(); ok {
		if err := animal.TypeValidator(v); err != nil {
			return &ValidationError{Name: "type", err: fmt.Errorf(`ent: validator failed for field "Animal.type": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Name(); ok {
		if err := animal.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Animal.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Mood(); ok {
		if err := animal.MoodValidator(v); err != nil {
			return &ValidationError{Name: "mood", err: fmt.Errorf(`ent: validator failed for field "Animal.mood": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Health(); ok {
		if err := animal.HealthValidator(v); err != nil {
			return &ValidationError{Name: "health", err: fmt.Errorf(`ent: validator failed for field "Animal.health": %w`, err)}
		}
	}
	if _u.mutation.FarmCleared() && len(_u.mutation.FarmIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Animal.farm"`)
	}
	return nil
}

func (_u *AnimalUpdateOne) sqlSave(ctx context.Context) (_node *Animal, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(animal.Table, animal.Columns, sqlgraph.NewFieldSpec(animal.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Animal.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, animal.FieldID)
		for _, f := range fields {
			if !animal.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != animal.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(animal.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.GetType(); ok {
		_spec.SetField(animal.FieldType, field.TypeString, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(animal.FieldName, field.TypeString, value)
	}
	if _u.mutation.NameCleared() {
		_spec.ClearField(animal.FieldName, field.TypeString)
	}
	if value, ok := _u.mutation.Mood(); ok {
		_spec.SetField(animal.FieldMood, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedMood(); ok {
		_spec.AddField(animal.FieldMood, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Health(); ok {
		_spec.SetField(animal.FieldHealth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedHealth(); ok {
		_spec.AddField(animal.FieldHealth, field.TypeInt, value)
	}
	if value, ok := _u.mutation.LastFedAt(); ok {
		_spec.SetField(animal.FieldLastFedAt, field.TypeTime, value)
	}
	if _u.mutation.LastFedAtCleared() {
		_spec.ClearField(animal.FieldLastFedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastCleanedAt(); ok {
		_spec.SetField(animal.FieldLastCleanedAt, field.TypeTime, value)
	}
	if _u.mutation.LastCleanedAtCleared() {
		_spec.ClearField(animal.FieldLastCleanedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.LastProductAt(); ok {
		_spec.SetField(animal.FieldLastProductAt, field.TypeTime, value)
	}
	if _u.mutation.LastProductAtCleared() {
		_spec.ClearField(animal.FieldLastProductAt, field.TypeTime)
	}
	if _u.mutation.FarmCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   animal.FarmTable,
			Columns: []string{animal.FarmColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(farm.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FarmIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   animal.FarmTable,
			Columns: []string{animal.FarmColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(farm.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Animal{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{animal.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
