// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/dialect/sql/sqljson"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/animal"
	"github.com/liukai/farmer/server/ent/building"
	"github.com/liukai/farmer/server/ent/farm"
	"github.com/liukai/farmer/server/ent/predicate"
	"github.com/liukai/farmer/server/ent/schema"
	"github.com/liukai/farmer/server/ent/user"
)

// FarmUpdate is the builder for updating Farm entities.
type FarmUpdate struct {
	config
	hooks    []Hook
	mutation *FarmMutation
}

// Where appends a list predicates to the FarmUpdate builder.
func (_u *FarmUpdate) Where(ps ...predicate.Farm) *FarmUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetOwnerID sets the "owner_id" field.
func (_u *FarmUpdate) SetOwnerID(v uuid.UUID) *FarmUpdate {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *FarmUpdate) SetNillableOwnerID(v *uuid.UUID) *FarmUpdate {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *FarmUpdate) SetName(v string) *FarmUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FarmUpdate) SetNillableName(v *string) *FarmUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *FarmUpdate) SetLevel(v int) *FarmUpdate {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *FarmUpdate) SetNillableLevel(v *int) *FarmUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *FarmUpdate) AddLevel(v int) *FarmUpdate {
	_u.mutation.AddLevel(v)
	return _u
}

// SetSpecialty sets the "specialty" field.
func (_u *FarmUpdate) SetSpecialty(v []string) *FarmUpdate {
	_u.mutation.SetSpecialty(v)
	return _u
}

// AppendSpecialty appends value to the "specialty" field.
func (_u *FarmUpdate) AppendSpecialty(v []string) *FarmUpdate {
	_u.mutation.AppendSpecialty(v)
	return _u
}

// SetPlots sets the "plots" field.
func (_u *FarmUpdate) SetPlots(v []schema.PlotState) *FarmUpdate {
	_u.mutation.SetPlots(v)
	return _u
}

// AppendPlots appends value to the "plots" field.
func (_u *FarmUpdate) AppendPlots(v []schema.PlotState) *FarmUpdate {
	_u.mutation.AppendPlots(v)
	return _u
}

// SetLastTickAt sets the "last_tick_at" field.
func (_u *FarmUpdate) SetLastTickAt(v time.Time) *FarmUpdate {
	_u.mutation.SetLastTickAt(v)
	return _u
}

// SetNillableLastTickAt sets the "last_tick_at" field if the given value is not nil.
func (_u *FarmUpdate) SetNillableLastTickAt(v *time.Time) *FarmUpdate {
	if v != nil {
		_u.SetLastTickAt(*v)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *FarmUpdate) SetOwner(v *User) *FarmUpdate {
	return _u.SetOwnerID(v.ID)
}

// AddBuildingIDs adds the "buildings" edge to the Building entity by IDs.
func (_u *FarmUpdate) AddBuildingIDs(ids ...uuid.UUID) *FarmUpdate {
	_u.mutation.AddBuildingIDs(ids...)
	return _u
}

// AddBuildings adds the "buildings" edges to the Building entity.
func (_u *FarmUpdate) AddBuildings(v ...*Building) *FarmUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBuildingIDs(ids...)
}

// AddAnimalIDs adds the "animals" edge to the Animal entity by IDs.
func (_u *FarmUpdate) AddAnimalIDs(ids ...uuid.UUID) *FarmUpdate {
	_u.mutation.AddAnimalIDs(ids...)
	return _u
}

// AddAnimals adds the "animals" edges to the Animal entity.
func (_u *FarmUpdate) AddAnimals(v ...*Animal) *FarmUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnimalIDs(ids...)
}

// Mutation returns the FarmMutation object of the builder.
func (_u *FarmUpdate) Mutation() *FarmMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *FarmUpdate) ClearOwner() *FarmUpdate {
	_u.mutation.ClearOwner()
	return _u
}

// ClearBuildings clears all "buildings" edges to the Building entity.
func (_u *FarmUpdate) ClearBuildings() *FarmUpdate {
	_u.mutation.ClearBuildings()
	return _u
}

// RemoveBuildingIDs removes the "buildings" edge to Building entities by IDs.
func (_u *FarmUpdate) RemoveBuildingIDs(ids ...uuid.UUID) *FarmUpdate {
	_u.mutation.RemoveBuildingIDs(ids...)
	return _u
}

// RemoveBuildings removes "buildings" edges to Building entities.
func (_u *FarmUpdate) RemoveBuildings(v ...*Building) *FarmUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBuildingIDs(ids...)
}

// ClearAnimals clears all "animals" edges to the Animal entity.
func (_u *FarmUpdate) ClearAnimals() *FarmUpdate {
	_u.mutation.ClearAnimals()
	return _u
}

// RemoveAnimalIDs removes the "animals" edge to Animal entities by IDs.
func (_u *FarmUpdate) RemoveAnimalIDs(ids ...uuid.UUID) *FarmUpdate {
	_u.mutation.RemoveAnimalIDs(ids...)
	return _u
}

// RemoveAnimals removes "animals" edges to Animal entities.
func (_u *FarmUpdate) RemoveAnimals(v ...*Animal) *FarmUpdate {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnimalIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FarmUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FarmUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FarmUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FarmUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FarmUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := farm.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Farm.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Level(); ok {
		if err := farm.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "Farm.level": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Farm.owner"`)
	}
	return nil
}

func (_u *FarmUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(farm.Table, farm.Columns, sqlgraph.NewFieldSpec(farm.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(farm.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(farm.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(farm.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Specialty(); ok {
		_spec.SetField(farm.FieldSpecialty, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSpecialty(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, farm.FieldSpecialty, value)
		})
	}
	if value, ok := _u.mutation.Plots(); ok {
		_spec.SetField(farm.FieldPlots, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPlots(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, farm.FieldPlots, value)
		})
	}
	if value, ok := _u.mutation.LastTickAt(); ok {
		_spec.SetField(farm.FieldLastTickAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   farm.OwnerTable,
			Columns: []string{farm.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   farm.OwnerTable,
			Columns: []string{farm.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BuildingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   farm.BuildingsTable,
			Columns: []string{farm.BuildingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(building.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBuildingsIDs(); len(nodes) > 0 && !_u.mutation.BuildingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   farm.BuildingsTable,
			Columns: []string{farm.BuildingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(building.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BuildingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   farm.BuildingsTable,
			Columns: []string{farm.BuildingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(building.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnimalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   farm.AnimalsTable,
			Columns: []string{farm.AnimalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(animal.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnimalsIDs(); len(nodes) > 0 && !_u.mutation.AnimalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   farm.AnimalsTable,
			Columns: []string{farm.AnimalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(animal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnimalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   farm.AnimalsTable,
			Columns: []string{farm.AnimalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(animal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{farm.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FarmUpdateOne is the builder for updating a single Farm entity.
type FarmUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FarmMutation
}

// SetOwnerID sets the "owner_id" field.
func (_u *FarmUpdateOne) SetOwnerID(v uuid.UUID) *FarmUpdateOne {
	_u.mutation.SetOwnerID(v)
	return _u
}

// SetNillableOwnerID sets the "owner_id" field if the given value is not nil.
func (_u *FarmUpdateOne) SetNillableOwnerID(v *uuid.UUID) *FarmUpdateOne {
	if v != nil {
		_u.SetOwnerID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *FarmUpdateOne) SetName(v string) *FarmUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *FarmUpdateOne) SetNillableName(v *string) *FarmUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetLevel sets the "level" field.
func (_u *FarmUpdateOne) SetLevel(v int) *FarmUpdateOne {
	_u.mutation.ResetLevel()
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *FarmUpdateOne) SetNillableLevel(v *int) *FarmUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// AddLevel adds value to the "level" field.
func (_u *FarmUpdateOne) AddLevel(v int) *FarmUpdateOne {
	_u.mutation.AddLevel(v)
	return _u
}

// SetSpecialty sets the "specialty" field.
func (_u *FarmUpdateOne) SetSpecialty(v []string) *FarmUpdateOne {
	_u.mutation.SetSpecialty(v)
	return _u
}

// AppendSpecialty appends value to the "specialty" field.
func (_u *FarmUpdateOne) AppendSpecialty(v []string) *FarmUpdateOne {
	_u.mutation.AppendSpecialty(v)
	return _u
}

// SetPlots sets the "plots" field.
func (_u *FarmUpdateOne) SetPlots(v []schema.PlotState) *FarmUpdateOne {
	_u.mutation.SetPlots(v)
	return _u
}

// AppendPlots appends value to the "plots" field.
func (_u *FarmUpdateOne) AppendPlots(v []schema.PlotState) *FarmUpdateOne {
	_u.mutation.AppendPlots(v)
	return _u
}

// SetLastTickAt sets the "last_tick_at" field.
func (_u *FarmUpdateOne) SetLastTickAt(v time.Time) *FarmUpdateOne {
	_u.mutation.SetLastTickAt(v)
	return _u
}

// SetNillableLastTickAt sets the "last_tick_at" field if the given value is not nil.
func (_u *FarmUpdateOne) SetNillableLastTickAt(v *time.Time) *FarmUpdateOne {
	if v != nil {
		_u.SetLastTickAt(*v)
	}
	return _u
}

// SetOwner sets the "owner" edge to the User entity.
func (_u *FarmUpdateOne) SetOwner(v *User) *FarmUpdateOne {
	return _u.SetOwnerID(v.ID)
}

// AddBuildingIDs adds the "buildings" edge to the Building entity by IDs.
func (_u *FarmUpdateOne) AddBuildingIDs(ids ...uuid.UUID) *FarmUpdateOne {
	_u.mutation.AddBuildingIDs(ids...)
	return _u
}

// AddBuildings adds the "buildings" edges to the Building entity.
func (_u *FarmUpdateOne) AddBuildings(v ...*Building) *FarmUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddBuildingIDs(ids...)
}

// AddAnimalIDs adds the "animals" edge to the Animal entity by IDs.
func (_u *FarmUpdateOne) AddAnimalIDs(ids ...uuid.UUID) *FarmUpdateOne {
	_u.mutation.AddAnimalIDs(ids...)
	return _u
}

// AddAnimals adds the "animals" edges to the Animal entity.
func (_u *FarmUpdateOne) AddAnimals(v ...*Animal) *FarmUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAnimalIDs(ids...)
}

// Mutation returns the FarmMutation object of the builder.
func (_u *FarmUpdateOne) Mutation() *FarmMutation {
	return _u.mutation
}

// ClearOwner clears the "owner" edge to the User entity.
func (_u *FarmUpdateOne) ClearOwner() *FarmUpdateOne {
	_u.mutation.ClearOwner()
	return _u
}

// ClearBuildings clears all "buildings" edges to the Building entity.
func (_u *FarmUpdateOne) ClearBuildings() *FarmUpdateOne {
	_u.mutation.ClearBuildings()
	return _u
}

// RemoveBuildingIDs removes the "buildings" edge to Building entities by IDs.
func (_u *FarmUpdateOne) RemoveBuildingIDs(ids ...uuid.UUID) *FarmUpdateOne {
	_u.mutation.RemoveBuildingIDs(ids...)
	return _u
}

// RemoveBuildings removes "buildings" edges to Building entities.
func (_u *FarmUpdateOne) RemoveBuildings(v ...*Building) *FarmUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveBuildingIDs(ids...)
}

// ClearAnimals clears all "animals" edges to the Animal entity.
func (_u *FarmUpdateOne) ClearAnimals() *FarmUpdateOne {
	_u.mutation.ClearAnimals()
	return _u
}

// RemoveAnimalIDs removes the "animals" edge to Animal entities by IDs.
func (_u *FarmUpdateOne) RemoveAnimalIDs(ids ...uuid.UUID) *FarmUpdateOne {
	_u.mutation.RemoveAnimalIDs(ids...)
	return _u
}

// RemoveAnimals removes "animals" edges to Animal entities.
func (_u *FarmUpdateOne) RemoveAnimals(v ...*Animal) *FarmUpdateOne {
	ids := make([]uuid.UUID, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAnimalIDs(ids...)
}

// Where appends a list predicates to the FarmUpdate builder.
func (_u *FarmUpdateOne) Where(ps ...predicate.Farm) *FarmUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FarmUpdateOne) Select(field string, fields ...string) *FarmUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Farm entity.
func (_u *FarmUpdateOne) Save(ctx context.Context) (*Farm, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FarmUpdateOne) SaveX(ctx context.Context) *Farm {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FarmUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FarmUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FarmUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := farm.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Farm.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Level(); ok {
		if err := farm.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "Farm.level": %w`, err)}
		}
	}
	if _u.mutation.OwnerCleared() && len(_u.mutation.OwnerIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Farm.owner"`)
	}
	return nil
}

func (_u *FarmUpdateOne) sqlSave(ctx context.Context) (_node *Farm, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(farm.Table, farm.Columns, sqlgraph.NewFieldSpec(farm.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Farm.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, farm.FieldID)
		for _, f := range fields {
			if !farm.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != farm.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(farm.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(farm.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedLevel(); ok {
		_spec.AddField(farm.FieldLevel, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Specialty(); ok {
		_spec.SetField(farm.FieldSpecialty, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedSpecialty(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, farm.FieldSpecialty, value)
		})
	}
	if value, ok := _u.mutation.Plots(); ok {
		_spec.SetField(farm.FieldPlots, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.AppendedPlots(); ok {
		_spec.AddModifier(func(u *sql.UpdateBuilder) {
			sqljson.Append(u, farm.FieldPlots, value)
		})
	}
	if value, ok := _u.mutation.LastTickAt(); ok {
		_spec.SetField(farm.FieldLastTickAt, field.TypeTime, value)
	}
	if _u.mutation.OwnerCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   farm.OwnerTable,
			Columns: []string{farm.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.OwnerIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   farm.OwnerTable,
			Columns: []string{farm.OwnerColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.BuildingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   farm.BuildingsTable,
			Columns: []string{farm.BuildingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(building.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedBuildingsIDs(); len(nodes) > 0 && !_u.mutation.BuildingsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   farm.BuildingsTable,
			Columns: []string{farm.BuildingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(building.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.BuildingsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   farm.BuildingsTable,
			Columns: []string{farm.BuildingsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(building.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AnimalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   farm.AnimalsTable,
			Columns: []string{farm.AnimalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(animal.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAnimalsIDs(); len(nodes) > 0 && !_u.mutation.AnimalsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   farm.AnimalsTable,
			Columns: []string{farm.AnimalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(animal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AnimalsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   farm.AnimalsTable,
			Columns: []string{farm.AnimalsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(animal.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Farm{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{farm.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
