// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/friendrequest"
	"github.com/liukai/farmer/server/ent/predicate"
	"github.com/liukai/farmer/server/ent/user"
)

// FriendRequestUpdate is the builder for updating FriendRequest entities.
type FriendRequestUpdate struct {
	config
	hooks    []Hook
	mutation *FriendRequestMutation
}

// Where appends a list predicates to the FriendRequestUpdate builder.
func (_u *FriendRequestUpdate) Where(ps ...predicate.FriendRequest) *FriendRequestUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FriendRequestUpdate) SetUpdatedAt(v time.Time) *FriendRequestUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFromUserID sets the "from_user_id" field.
func (_u *FriendRequestUpdate) SetFromUserID(v uuid.UUID) *FriendRequestUpdate {
	_u.mutation.SetFromUserID(v)
	return _u
}

// SetNillableFromUserID sets the "from_user_id" field if the given value is not nil.
func (_u *FriendRequestUpdate) SetNillableFromUserID(v *uuid.UUID) *FriendRequestUpdate {
	if v != nil {
		_u.SetFromUserID(*v)
	}
	return _u
}

// SetToUserID sets the "to_user_id" field.
func (_u *FriendRequestUpdate) SetToUserID(v uuid.UUID) *FriendRequestUpdate {
	_u.mutation.SetToUserID(v)
	return _u
}

// SetNillableToUserID sets the "to_user_id" field if the given value is not nil.
func (_u *FriendRequestUpdate) SetNillableToUserID(v *uuid.UUID) *FriendRequestUpdate {
	if v != nil {
		_u.SetToUserID(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *FriendRequestUpdate) SetMessage(v string) *FriendRequestUpdate {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *FriendRequestUpdate) SetNillableMessage(v *string) *FriendRequestUpdate {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *FriendRequestUpdate) ClearMessage() *FriendRequestUpdate {
	_u.mutation.ClearMessage()
	return _u
}

// SetStatus sets the "status" field.
func (_u *FriendRequestUpdate) SetStatus(v string) *FriendRequestUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FriendRequestUpdate) SetNillableStatus(v *string) *FriendRequestUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFromUser sets the "from_user" edge to the User entity.
func (_u *FriendRequestUpdate) SetFromUser(v *User) *FriendRequestUpdate {
	return _u.SetFromUserID(v.ID)
}

// SetToUser sets the "to_user" edge to the User entity.
func (_u *FriendRequestUpdate) SetToUser(v *User) *FriendRequestUpdate {
	return _u.SetToUserID(v.ID)
}

// Mutation returns the FriendRequestMutation object of the builder.
func (_u *FriendRequestUpdate) Mutation() *FriendRequestMutation {
	return _u.mutation
}

// ClearFromUser clears the "from_user" edge to the User entity.
func (_u *FriendRequestUpdate) ClearFromUser() *FriendRequestUpdate {
	_u.mutation.ClearFromUser()
	return _u
}

// ClearToUser clears the "to_user" edge to the User entity.
func (_u *FriendRequestUpdate) ClearToUser() *FriendRequestUpdate {
	_u.mutation.ClearToUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FriendRequestUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FriendRequestUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FriendRequestUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FriendRequestUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FriendRequestUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := friendrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FriendRequestUpdate) check() error {
	if v, ok := _u.mutation.Message(); ok {
		if err := friendrequest.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "FriendRequest.message": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := friendrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FriendRequest.status": %w`, err)}
		}
	}
	if _u.mutation.FromUserCleared() && len(_u.mutation.FromUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FriendRequest.from_user"`)
	}
	if _u.mutation.ToUserCleared() && len(_u.mutation.ToUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FriendRequest.to_user"`)
	}
	return nil
}

func (_u *FriendRequestUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(friendrequest.Table, friendrequest.Columns, sqlgraph.NewFieldSpec(friendrequest.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(friendrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(friendrequest.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(friendrequest.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(friendrequest.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.FromUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   friendrequest.FromUserTable,
			Columns: []string{friendrequest.FromUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FromUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   friendrequest.FromUserTable,
			Columns: []string{friendrequest.FromUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ToUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   friendrequest.ToUserTable,
			Columns: []string{friendrequest.ToUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ToUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   friendrequest.ToUserTable,
			Columns: []string{friendrequest.ToUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{friendrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FriendRequestUpdateOne is the builder for updating a single FriendRequest entity.
type FriendRequestUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FriendRequestMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *FriendRequestUpdateOne) SetUpdatedAt(v time.Time) *FriendRequestUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetFromUserID sets the "from_user_id" field.
func (_u *FriendRequestUpdateOne) SetFromUserID(v uuid.UUID) *FriendRequestUpdateOne {
	_u.mutation.SetFromUserID(v)
	return _u
}

// SetNillableFromUserID sets the "from_user_id" field if the given value is not nil.
func (_u *FriendRequestUpdateOne) SetNillableFromUserID(v *uuid.UUID) *FriendRequestUpdateOne {
	if v != nil {
		_u.SetFromUserID(*v)
	}
	return _u
}

// SetToUserID sets the "to_user_id" field.
func (_u *FriendRequestUpdateOne) SetToUserID(v uuid.UUID) *FriendRequestUpdateOne {
	_u.mutation.SetToUserID(v)
	return _u
}

// SetNillableToUserID sets the "to_user_id" field if the given value is not nil.
func (_u *FriendRequestUpdateOne) SetNillableToUserID(v *uuid.UUID) *FriendRequestUpdateOne {
	if v != nil {
		_u.SetToUserID(*v)
	}
	return _u
}

// SetMessage sets the "message" field.
func (_u *FriendRequestUpdateOne) SetMessage(v string) *FriendRequestUpdateOne {
	_u.mutation.SetMessage(v)
	return _u
}

// SetNillableMessage sets the "message" field if the given value is not nil.
func (_u *FriendRequestUpdateOne) SetNillableMessage(v *string) *FriendRequestUpdateOne {
	if v != nil {
		_u.SetMessage(*v)
	}
	return _u
}

// ClearMessage clears the value of the "message" field.
func (_u *FriendRequestUpdateOne) ClearMessage() *FriendRequestUpdateOne {
	_u.mutation.ClearMessage()
	return _u
}

// SetStatus sets the "status" field.
func (_u *FriendRequestUpdateOne) SetStatus(v string) *FriendRequestUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *FriendRequestUpdateOne) SetNillableStatus(v *string) *FriendRequestUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetFromUser sets the "from_user" edge to the User entity.
func (_u *FriendRequestUpdateOne) SetFromUser(v *User) *FriendRequestUpdateOne {
	return _u.SetFromUserID(v.ID)
}

// SetToUser sets the "to_user" edge to the User entity.
func (_u *FriendRequestUpdateOne) SetToUser(v *User) *FriendRequestUpdateOne {
	return _u.SetToUserID(v.ID)
}

// Mutation returns the FriendRequestMutation object of the builder.
func (_u *FriendRequestUpdateOne) Mutation() *FriendRequestMutation {
	return _u.mutation
}

// ClearFromUser clears the "from_user" edge to the User entity.
func (_u *FriendRequestUpdateOne) ClearFromUser() *FriendRequestUpdateOne {
	_u.mutation.ClearFromUser()
	return _u
}

// ClearToUser clears the "to_user" edge to the User entity.
func (_u *FriendRequestUpdateOne) ClearToUser() *FriendRequestUpdateOne {
	_u.mutation.ClearToUser()
	return _u
}

// Where appends a list predicates to the FriendRequestUpdate builder.
func (_u *FriendRequestUpdateOne) Where(ps ...predicate.FriendRequest) *FriendRequestUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FriendRequestUpdateOne) Select(field string, fields ...string) *FriendRequestUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated FriendRequest entity.
func (_u *FriendRequestUpdateOne) Save(ctx context.Context) (*FriendRequest, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FriendRequestUpdateOne) SaveX(ctx context.Context) *FriendRequest {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FriendRequestUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FriendRequestUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *FriendRequestUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := friendrequest.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FriendRequestUpdateOne) check() error {
	if v, ok := _u.mutation.Message(); ok {
		if err := friendrequest.MessageValidator(v); err != nil {
			return &ValidationError{Name: "message", err: fmt.Errorf(`ent: validator failed for field "FriendRequest.message": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := friendrequest.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "FriendRequest.status": %w`, err)}
		}
	}
	if _u.mutation.FromUserCleared() && len(_u.mutation.FromUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FriendRequest.from_user"`)
	}
	if _u.mutation.ToUserCleared() && len(_u.mutation.ToUserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "FriendRequest.to_user"`)
	}
	return nil
}

func (_u *FriendRequestUpdateOne) sqlSave(ctx context.Context) (_node *FriendRequest, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(friendrequest.Table, friendrequest.Columns, sqlgraph.NewFieldSpec(friendrequest.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "FriendRequest.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, friendrequest.FieldID)
		for _, f := range fields {
			if !friendrequest.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != friendrequest.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(friendrequest.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Message(); ok {
		_spec.SetField(friendrequest.FieldMessage, field.TypeString, value)
	}
	if _u.mutation.MessageCleared() {
		_spec.ClearField(friendrequest.FieldMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(friendrequest.FieldStatus, field.TypeString, value)
	}
	if _u.mutation.FromUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   friendrequest.FromUserTable,
			Columns: []string{friendrequest.FromUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.FromUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   friendrequest.FromUserTable,
			Columns: []string{friendrequest.FromUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.ToUserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   friendrequest.ToUserTable,
			Columns: []string{friendrequest.ToUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ToUserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   friendrequest.ToUserTable,
			Columns: []string{friendrequest.ToUserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &FriendRequest{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{friendrequest.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
