// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/friendrequest"
	"github.com/liukai/farmer/server/ent/user"
)

// FriendRequest is the model entity for the FriendRequest schema.
type FriendRequest struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// FromUserID holds the value of the "from_user_id" field.
	FromUserID uuid.UUID `json:"from_user_id,omitempty"`
	// ToUserID holds the value of the "to_user_id" field.
	ToUserID uuid.UUID `json:"to_user_id,omitempty"`
	// Message holds the value of the "message" field.
	Message *string `json:"message,omitempty"`
	// pending/accepted/rejected
	Status string `json:"status,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FriendRequestQuery when eager-loading is set.
	Edges        FriendRequestEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FriendRequestEdges holds the relations/edges for other nodes in the graph.
type FriendRequestEdges struct {
	// FromUser holds the value of the from_user edge.
	FromUser *User `json:"from_user,omitempty"`
	// ToUser holds the value of the to_user edge.
	ToUser *User `json:"to_user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// FromUserOrErr returns the FromUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FriendRequestEdges) FromUserOrErr() (*User, error) {
	if e.FromUser != nil {
		return e.FromUser, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "from_user"}
}

// ToUserOrErr returns the ToUser value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FriendRequestEdges) ToUserOrErr() (*User, error) {
	if e.ToUser != nil {
		return e.ToUser, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "to_user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*FriendRequest) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case friendrequest.FieldMessage, friendrequest.FieldStatus:
			values[i] = new(sql.NullString)
		case friendrequest.FieldCreatedAt, friendrequest.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		case friendrequest.FieldID, friendrequest.FieldFromUserID, friendrequest.FieldToUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the FriendRequest fields.
func (_m *FriendRequest) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case friendrequest.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case friendrequest.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case friendrequest.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case friendrequest.FieldFromUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field from_user_id", values[i])
			} else if value != nil {
				_m.FromUserID = *value
			}
		case friendrequest.FieldToUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field to_user_id", values[i])
			} else if value != nil {
				_m.ToUserID = *value
			}
		case friendrequest.FieldMessage:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field message", values[i])
			} else if value.Valid {
				_m.Message = new(string)
				*_m.Message = value.String
			}
		case friendrequest.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the FriendRequest.
// This includes values selected through modifiers, order, etc.
func (_m *FriendRequest) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryFromUser queries the "from_user" edge of the FriendRequest entity.
func (_m *FriendRequest) QueryFromUser() *UserQuery {
	return NewFriendRequestClient(_m.config).QueryFromUser(_m)
}

// QueryToUser queries the "to_user" edge of the FriendRequest entity.
func (_m *FriendRequest) QueryToUser() *UserQuery {
	return NewFriendRequestClient(_m.config).QueryToUser(_m)
}

// Update returns a builder for updating this FriendRequest.
// Note that you need to call FriendRequest.Unwrap() before calling this method if this FriendRequest
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *FriendRequest) Update() *FriendRequestUpdateOne {
	return NewFriendRequestClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the FriendRequest entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *FriendRequest) Unwrap() *FriendRequest {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: FriendRequest is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *FriendRequest) String() string {
	var builder strings.Builder
	builder.WriteString("FriendRequest(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("from_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.FromUserID))
	builder.WriteString(", ")
	builder.WriteString("to_user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.ToUserID))
	builder.WriteString(", ")
	if v := _m.Message; v != nil {
		builder.WriteString("message=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteByte(')')
	return builder.String()
}

// FriendRequests is a parsable slice of FriendRequest.
type FriendRequests []*FriendRequest
