// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/friend"
	"github.com/liukai/farmer/server/ent/predicate"
	"github.com/liukai/farmer/server/ent/user"
)

// FriendUpdate is the builder for updating Friend entities.
type FriendUpdate struct {
	config
	hooks    []Hook
	mutation *FriendMutation
}

// Where appends a list predicates to the FriendUpdate builder.
func (_u *FriendUpdate) Where(ps ...predicate.Friend) *FriendUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserAID sets the "user_a_id" field.
func (_u *FriendUpdate) SetUserAID(v uuid.UUID) *FriendUpdate {
	_u.mutation.SetUserAID(v)
	return _u
}

// SetNillableUserAID sets the "user_a_id" field if the given value is not nil.
func (_u *FriendUpdate) SetNillableUserAID(v *uuid.UUID) *FriendUpdate {
	if v != nil {
		_u.SetUserAID(*v)
	}
	return _u
}

// SetUserBID sets the "user_b_id" field.
func (_u *FriendUpdate) SetUserBID(v uuid.UUID) *FriendUpdate {
	_u.mutation.SetUserBID(v)
	return _u
}

// SetNillableUserBID sets the "user_b_id" field if the given value is not nil.
func (_u *FriendUpdate) SetNillableUserBID(v *uuid.UUID) *FriendUpdate {
	if v != nil {
		_u.SetUserBID(*v)
	}
	return _u
}

// SetUserA sets the "user_a" edge to the User entity.
func (_u *FriendUpdate) SetUserA(v *User) *FriendUpdate {
	return _u.SetUserAID(v.ID)
}

// SetUserB sets the "user_b" edge to the User entity.
func (_u *FriendUpdate) SetUserB(v *User) *FriendUpdate {
	return _u.SetUserBID(v.ID)
}

// Mutation returns the FriendMutation object of the builder.
func (_u *FriendUpdate) Mutation() *FriendMutation {
	return _u.mutation
}

// ClearUserA clears the "user_a" edge to the User entity.
func (_u *FriendUpdate) ClearUserA() *FriendUpdate {
	_u.mutation.ClearUserA()
	return _u
}

// ClearUserB clears the "user_b" edge to the User entity.
func (_u *FriendUpdate) ClearUserB() *FriendUpdate {
	_u.mutation.ClearUserB()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *FriendUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FriendUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *FriendUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FriendUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FriendUpdate) check() error {
	if _u.mutation.UserACleared() && len(_u.mutation.UserAIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Friend.user_a"`)
	}
	if _u.mutation.UserBCleared() && len(_u.mutation.UserBIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Friend.user_b"`)
	}
	return nil
}

func (_u *FriendUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(friend.Table, friend.Columns, sqlgraph.NewFieldSpec(friend.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.UserACleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   friend.UserATable,
			Columns: []string{friend.UserAColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserAIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   friend.UserATable,
			Columns: []string{friend.UserAColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserBCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   friend.UserBTable,
			Columns: []string{friend.UserBColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserBIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   friend.UserBTable,
			Columns: []string{friend.UserBColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{friend.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// FriendUpdateOne is the builder for updating a single Friend entity.
type FriendUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *FriendMutation
}

// SetUserAID sets the "user_a_id" field.
func (_u *FriendUpdateOne) SetUserAID(v uuid.UUID) *FriendUpdateOne {
	_u.mutation.SetUserAID(v)
	return _u
}

// SetNillableUserAID sets the "user_a_id" field if the given value is not nil.
func (_u *FriendUpdateOne) SetNillableUserAID(v *uuid.UUID) *FriendUpdateOne {
	if v != nil {
		_u.SetUserAID(*v)
	}
	return _u
}

// SetUserBID sets the "user_b_id" field.
func (_u *FriendUpdateOne) SetUserBID(v uuid.UUID) *FriendUpdateOne {
	_u.mutation.SetUserBID(v)
	return _u
}

// SetNillableUserBID sets the "user_b_id" field if the given value is not nil.
func (_u *FriendUpdateOne) SetNillableUserBID(v *uuid.UUID) *FriendUpdateOne {
	if v != nil {
		_u.SetUserBID(*v)
	}
	return _u
}

// SetUserA sets the "user_a" edge to the User entity.
func (_u *FriendUpdateOne) SetUserA(v *User) *FriendUpdateOne {
	return _u.SetUserAID(v.ID)
}

// SetUserB sets the "user_b" edge to the User entity.
func (_u *FriendUpdateOne) SetUserB(v *User) *FriendUpdateOne {
	return _u.SetUserBID(v.ID)
}

// Mutation returns the FriendMutation object of the builder.
func (_u *FriendUpdateOne) Mutation() *FriendMutation {
	return _u.mutation
}

// ClearUserA clears the "user_a" edge to the User entity.
func (_u *FriendUpdateOne) ClearUserA() *FriendUpdateOne {
	_u.mutation.ClearUserA()
	return _u
}

// ClearUserB clears the "user_b" edge to the User entity.
func (_u *FriendUpdateOne) ClearUserB() *FriendUpdateOne {
	_u.mutation.ClearUserB()
	return _u
}

// Where appends a list predicates to the FriendUpdate builder.
func (_u *FriendUpdateOne) Where(ps ...predicate.Friend) *FriendUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *FriendUpdateOne) Select(field string, fields ...string) *FriendUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Friend entity.
func (_u *FriendUpdateOne) Save(ctx context.Context) (*Friend, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *FriendUpdateOne) SaveX(ctx context.Context) *Friend {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *FriendUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *FriendUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *FriendUpdateOne) check() error {
	if _u.mutation.UserACleared() && len(_u.mutation.UserAIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Friend.user_a"`)
	}
	if _u.mutation.UserBCleared() && len(_u.mutation.UserBIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Friend.user_b"`)
	}
	return nil
}

func (_u *FriendUpdateOne) sqlSave(ctx context.Context) (_node *Friend, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(friend.Table, friend.Columns, sqlgraph.NewFieldSpec(friend.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Friend.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, friend.FieldID)
		for _, f := range fields {
			if !friend.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != friend.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if _u.mutation.UserACleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   friend.UserATable,
			Columns: []string{friend.UserAColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserAIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   friend.UserATable,
			Columns: []string{friend.UserAColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserBCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   friend.UserBTable,
			Columns: []string{friend.UserBColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserBIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   friend.UserBTable,
			Columns: []string{friend.UserBColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Friend{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{friend.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
