// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/friend"
	"github.com/liukai/farmer/server/ent/user"
)

// Friend is the model entity for the Friend schema.
type Friend struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// ID 较小的一方
	UserAID uuid.UUID `json:"user_a_id,omitempty"`
	// UserBID holds the value of the "user_b_id" field.
	UserBID uuid.UUID `json:"user_b_id,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the FriendQuery when eager-loading is set.
	Edges        FriendEdges `json:"edges"`
	selectValues sql.SelectValues
}

// FriendEdges holds the relations/edges for other nodes in the graph.
type FriendEdges struct {
	// UserA holds the value of the user_a edge.
	UserA *User `json:"user_a,omitempty"`
	// UserB holds the value of the user_b edge.
	UserB *User `json:"user_b,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// UserAOrErr returns the UserA value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FriendEdges) UserAOrErr() (*User, error) {
	if e.UserA != nil {
		return e.UserA, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user_a"}
}

// UserBOrErr returns the UserB value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e FriendEdges) UserBOrErr() (*User, error) {
	if e.UserB != nil {
		return e.UserB, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user_b"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Friend) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case friend.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		case friend.FieldID, friend.FieldUserAID, friend.FieldUserBID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Friend fields.
func (_m *Friend) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case friend.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case friend.FieldUserAID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_a_id", values[i])
			} else if value != nil {
				_m.UserAID = *value
			}
		case friend.FieldUserBID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_b_id", values[i])
			} else if value != nil {
				_m.UserBID = *value
			}
		case friend.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Friend.
// This includes values selected through modifiers, order, etc.
func (_m *Friend) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUserA queries the "user_a" edge of the Friend entity.
func (_m *Friend) QueryUserA() *UserQuery {
	return NewFriendClient(_m.config).QueryUserA(_m)
}

// QueryUserB queries the "user_b" edge of the Friend entity.
func (_m *Friend) QueryUserB() *UserQuery {
	return NewFriendClient(_m.config).QueryUserB(_m)
}

// Update returns a builder for updating this Friend.
// Note that you need to call Friend.Unwrap() before calling this method if this Friend
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Friend) Update() *FriendUpdateOne {
	return NewFriendClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Friend entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Friend) Unwrap() *Friend {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Friend is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Friend) String() string {
	var builder strings.Builder
	builder.WriteString("Friend(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_a_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserAID))
	builder.WriteString(", ")
	builder.WriteString("user_b_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserBID))
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Friends is a parsable slice of Friend.
type Friends []*Friend
