// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/paymentorder"
	"github.com/liukai/farmer/server/ent/user"
)

// PaymentOrderCreate is the builder for creating a PaymentOrder entity.
type PaymentOrderCreate struct {
	config
	mutation *PaymentOrderMutation
	hooks    []Hook
}

// SetUserID sets the "user_id" field.
func (_c *PaymentOrderCreate) SetUserID(v uuid.UUID) *PaymentOrderCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetPackageID sets the "package_id" field.
func (_c *PaymentOrderCreate) SetPackageID(v string) *PaymentOrderCreate {
	_c.mutation.SetPackageID(v)
	return _c
}

// SetAmountCents sets the "amount_cents" field.
func (_c *PaymentOrderCreate) SetAmountCents(v int) *PaymentOrderCreate {
	_c.mutation.SetAmountCents(v)
	return _c
}

// SetDiamondsToGrant sets the "diamonds_to_grant" field.
func (_c *PaymentOrderCreate) SetDiamondsToGrant(v int) *PaymentOrderCreate {
	_c.mutation.SetDiamondsToGrant(v)
	return _c
}

// SetStatus sets the "status" field.
func (_c *PaymentOrderCreate) SetStatus(v string) *PaymentOrderCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableStatus(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetWxPrepayID sets the "wx_prepay_id" field.
func (_c *PaymentOrderCreate) SetWxPrepayID(v string) *PaymentOrderCreate {
	_c.mutation.SetWxPrepayID(v)
	return _c
}

// SetNillableWxPrepayID sets the "wx_prepay_id" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableWxPrepayID(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetWxPrepayID(*v)
	}
	return _c
}

// SetWxTransactionID sets the "wx_transaction_id" field.
func (_c *PaymentOrderCreate) SetWxTransactionID(v string) *PaymentOrderCreate {
	_c.mutation.SetWxTransactionID(v)
	return _c
}

// SetNillableWxTransactionID sets the "wx_transaction_id" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableWxTransactionID(v *string) *PaymentOrderCreate {
	if v != nil {
		_c.SetWxTransactionID(*v)
	}
	return _c
}

// SetPaidAt sets the "paid_at" field.
func (_c *PaymentOrderCreate) SetPaidAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetPaidAt(v)
	return _c
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillablePaidAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetPaidAt(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *PaymentOrderCreate) SetCreatedAt(v time.Time) *PaymentOrderCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableCreatedAt(v *time.Time) *PaymentOrderCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PaymentOrderCreate) SetID(v uuid.UUID) *PaymentOrderCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PaymentOrderCreate) SetNillableID(v *uuid.UUID) *PaymentOrderCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *PaymentOrderCreate) SetUser(v *User) *PaymentOrderCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_c *PaymentOrderCreate) Mutation() *PaymentOrderMutation {
	return _c.mutation
}

// Save creates the PaymentOrder in the database.
func (_c *PaymentOrderCreate) Save(ctx context.Context) (*PaymentOrder, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PaymentOrderCreate) SaveX(ctx context.Context) *PaymentOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentOrderCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentOrderCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PaymentOrderCreate) defaults() {
	if _, ok := _c.mutation.Status(); !ok {
		v := paymentorder.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := paymentorder.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := paymentorder.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PaymentOrderCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "PaymentOrder.user_id"`)}
	}
	if _, ok := _c.mutation.PackageID(); !ok {
		return &ValidationError{Name: "package_id", err: errors.New(`ent: missing required field "PaymentOrder.package_id"`)}
	}
	if v, ok := _c.mutation.PackageID(); ok {
		if err := paymentorder.PackageIDValidator(v); err != nil {
			return &ValidationError{Name: "package_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.package_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.AmountCents(); !ok {
		return &ValidationError{Name: "amount_cents", err: errors.New(`ent: missing required field "PaymentOrder.amount_cents"`)}
	}
	if v, ok := _c.mutation.AmountCents(); ok {
		if err := paymentorder.AmountCentsValidator(v); err != nil {
			return &ValidationError{Name: "amount_cents", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.amount_cents": %w`, err)}
		}
	}
	if _, ok := _c.mutation.DiamondsToGrant(); !ok {
		return &ValidationError{Name: "diamonds_to_grant", err: errors.New(`ent: missing required field "PaymentOrder.diamonds_to_grant"`)}
	}
	if v, ok := _c.mutation.DiamondsToGrant(); ok {
		if err := paymentorder.DiamondsToGrantValidator(v); err != nil {
			return &ValidationError{Name: "diamonds_to_grant", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.diamonds_to_grant": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "PaymentOrder.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if v, ok := _c.mutation.WxPrepayID(); ok {
		if err := paymentorder.WxPrepayIDValidator(v); err != nil {
			return &ValidationError{Name: "wx_prepay_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.wx_prepay_id": %w`, err)}
		}
	}
	if v, ok := _c.mutation.WxTransactionID(); ok {
		if err := paymentorder.WxTransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "wx_transaction_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.wx_transaction_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "PaymentOrder.created_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "PaymentOrder.user"`)}
	}
	return nil
}

func (_c *PaymentOrderCreate) sqlSave(ctx context.Context) (*PaymentOrder, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PaymentOrderCreate) createSpec() (*PaymentOrder, *sqlgraph.CreateSpec) {
	var (
		_node = &PaymentOrder{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(paymentorder.Table, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.PackageID(); ok {
		_spec.SetField(paymentorder.FieldPackageID, field.TypeString, value)
		_node.PackageID = value
	}
	if value, ok := _c.mutation.AmountCents(); ok {
		_spec.SetField(paymentorder.FieldAmountCents, field.TypeInt, value)
		_node.AmountCents = value
	}
	if value, ok := _c.mutation.DiamondsToGrant(); ok {
		_spec.SetField(paymentorder.FieldDiamondsToGrant, field.TypeInt, value)
		_node.DiamondsToGrant = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.WxPrepayID(); ok {
		_spec.SetField(paymentorder.FieldWxPrepayID, field.TypeString, value)
		_node.WxPrepayID = &value
	}
	if value, ok := _c.mutation.WxTransactionID(); ok {
		_spec.SetField(paymentorder.FieldWxTransactionID, field.TypeString, value)
		_node.WxTransactionID = &value
	}
	if value, ok := _c.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
		_node.PaidAt = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(paymentorder.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PaymentOrderCreateBulk is the builder for creating many PaymentOrder entities in bulk.
type PaymentOrderCreateBulk struct {
	config
	err      error
	builders []*PaymentOrderCreate
}

// Save creates the PaymentOrder entities in the database.
func (_c *PaymentOrderCreateBulk) Save(ctx context.Context) ([]*PaymentOrder, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PaymentOrder, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PaymentOrderMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PaymentOrderCreateBulk) SaveX(ctx context.Context) []*PaymentOrder {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PaymentOrderCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PaymentOrderCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
