// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/paymentorder"
	"github.com/liukai/farmer/server/ent/predicate"
	"github.com/liukai/farmer/server/ent/user"
)

// PaymentOrderUpdate is the builder for updating PaymentOrder entities.
type PaymentOrderUpdate struct {
	config
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (_u *PaymentOrderUpdate) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *PaymentOrderUpdate) SetUserID(v uuid.UUID) *PaymentOrderUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableUserID(v *uuid.UUID) *PaymentOrderUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPackageID sets the "package_id" field.
func (_u *PaymentOrderUpdate) SetPackageID(v string) *PaymentOrderUpdate {
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillablePackageID(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// SetAmountCents sets the "amount_cents" field.
func (_u *PaymentOrderUpdate) SetAmountCents(v int) *PaymentOrderUpdate {
	_u.mutation.ResetAmountCents()
	_u.mutation.SetAmountCents(v)
	return _u
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableAmountCents(v *int) *PaymentOrderUpdate {
	if v != nil {
		_u.SetAmountCents(*v)
	}
	return _u
}

// AddAmountCents adds value to the "amount_cents" field.
func (_u *PaymentOrderUpdate) AddAmountCents(v int) *PaymentOrderUpdate {
	_u.mutation.AddAmountCents(v)
	return _u
}

// SetDiamondsToGrant sets the "diamonds_to_grant" field.
func (_u *PaymentOrderUpdate) SetDiamondsToGrant(v int) *PaymentOrderUpdate {
	_u.mutation.ResetDiamondsToGrant()
	_u.mutation.SetDiamondsToGrant(v)
	return _u
}

// SetNillableDiamondsToGrant sets the "diamonds_to_grant" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableDiamondsToGrant(v *int) *PaymentOrderUpdate {
	if v != nil {
		_u.SetDiamondsToGrant(*v)
	}
	return _u
}

// AddDiamondsToGrant adds value to the "diamonds_to_grant" field.
func (_u *PaymentOrderUpdate) AddDiamondsToGrant(v int) *PaymentOrderUpdate {
	_u.mutation.AddDiamondsToGrant(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentOrderUpdate) SetStatus(v string) *PaymentOrderUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableStatus(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetWxPrepayID sets the "wx_prepay_id" field.
func (_u *PaymentOrderUpdate) SetWxPrepayID(v string) *PaymentOrderUpdate {
	_u.mutation.SetWxPrepayID(v)
	return _u
}

// SetNillableWxPrepayID sets the "wx_prepay_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableWxPrepayID(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetWxPrepayID(*v)
	}
	return _u
}

// ClearWxPrepayID clears the value of the "wx_prepay_id" field.
func (_u *PaymentOrderUpdate) ClearWxPrepayID() *PaymentOrderUpdate {
	_u.mutation.ClearWxPrepayID()
	return _u
}

// SetWxTransactionID sets the "wx_transaction_id" field.
func (_u *PaymentOrderUpdate) SetWxTransactionID(v string) *PaymentOrderUpdate {
	_u.mutation.SetWxTransactionID(v)
	return _u
}

// SetNillableWxTransactionID sets the "wx_transaction_id" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillableWxTransactionID(v *string) *PaymentOrderUpdate {
	if v != nil {
		_u.SetWxTransactionID(*v)
	}
	return _u
}

// ClearWxTransactionID clears the value of the "wx_transaction_id" field.
func (_u *PaymentOrderUpdate) ClearWxTransactionID() *PaymentOrderUpdate {
	_u.mutation.ClearWxTransactionID()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentOrderUpdate) SetPaidAt(v time.Time) *PaymentOrderUpdate {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentOrderUpdate) SetNillablePaidAt(v *time.Time) *PaymentOrderUpdate {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentOrderUpdate) ClearPaidAt() *PaymentOrderUpdate {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentOrderUpdate) SetUser(v *User) *PaymentOrderUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_u *PaymentOrderUpdate) Mutation() *PaymentOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentOrderUpdate) ClearUser() *PaymentOrderUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PaymentOrderUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PaymentOrderUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentOrderUpdate) check() error {
	if v, ok := _u.mutation.PackageID(); ok {
		if err := paymentorder.PackageIDValidator(v); err != nil {
			return &ValidationError{Name: "package_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.package_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AmountCents(); ok {
		if err := paymentorder.AmountCentsValidator(v); err != nil {
			return &ValidationError{Name: "amount_cents", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.amount_cents": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DiamondsToGrant(); ok {
		if err := paymentorder.DiamondsToGrantValidator(v); err != nil {
			return &ValidationError{Name: "diamonds_to_grant", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.diamonds_to_grant": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WxPrepayID(); ok {
		if err := paymentorder.WxPrepayIDValidator(v); err != nil {
			return &ValidationError{Name: "wx_prepay_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.wx_prepay_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WxTransactionID(); ok {
		if err := paymentorder.WxTransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "wx_transaction_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.wx_transaction_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentOrder.user"`)
	}
	return nil
}

func (_u *PaymentOrderUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(paymentorder.FieldPackageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountCents(); ok {
		_spec.SetField(paymentorder.FieldAmountCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAmountCents(); ok {
		_spec.AddField(paymentorder.FieldAmountCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DiamondsToGrant(); ok {
		_spec.SetField(paymentorder.FieldDiamondsToGrant, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDiamondsToGrant(); ok {
		_spec.AddField(paymentorder.FieldDiamondsToGrant, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.WxPrepayID(); ok {
		_spec.SetField(paymentorder.FieldWxPrepayID, field.TypeString, value)
	}
	if _u.mutation.WxPrepayIDCleared() {
		_spec.ClearField(paymentorder.FieldWxPrepayID, field.TypeString)
	}
	if value, ok := _u.mutation.WxTransactionID(); ok {
		_spec.SetField(paymentorder.FieldWxTransactionID, field.TypeString, value)
	}
	if _u.mutation.WxTransactionIDCleared() {
		_spec.ClearField(paymentorder.FieldWxTransactionID, field.TypeString)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(paymentorder.FieldPaidAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PaymentOrderUpdateOne is the builder for updating a single PaymentOrder entity.
type PaymentOrderUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PaymentOrderMutation
}

// SetUserID sets the "user_id" field.
func (_u *PaymentOrderUpdateOne) SetUserID(v uuid.UUID) *PaymentOrderUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableUserID(v *uuid.UUID) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetPackageID sets the "package_id" field.
func (_u *PaymentOrderUpdateOne) SetPackageID(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetPackageID(v)
	return _u
}

// SetNillablePackageID sets the "package_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillablePackageID(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetPackageID(*v)
	}
	return _u
}

// SetAmountCents sets the "amount_cents" field.
func (_u *PaymentOrderUpdateOne) SetAmountCents(v int) *PaymentOrderUpdateOne {
	_u.mutation.ResetAmountCents()
	_u.mutation.SetAmountCents(v)
	return _u
}

// SetNillableAmountCents sets the "amount_cents" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableAmountCents(v *int) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetAmountCents(*v)
	}
	return _u
}

// AddAmountCents adds value to the "amount_cents" field.
func (_u *PaymentOrderUpdateOne) AddAmountCents(v int) *PaymentOrderUpdateOne {
	_u.mutation.AddAmountCents(v)
	return _u
}

// SetDiamondsToGrant sets the "diamonds_to_grant" field.
func (_u *PaymentOrderUpdateOne) SetDiamondsToGrant(v int) *PaymentOrderUpdateOne {
	_u.mutation.ResetDiamondsToGrant()
	_u.mutation.SetDiamondsToGrant(v)
	return _u
}

// SetNillableDiamondsToGrant sets the "diamonds_to_grant" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableDiamondsToGrant(v *int) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetDiamondsToGrant(*v)
	}
	return _u
}

// AddDiamondsToGrant adds value to the "diamonds_to_grant" field.
func (_u *PaymentOrderUpdateOne) AddDiamondsToGrant(v int) *PaymentOrderUpdateOne {
	_u.mutation.AddDiamondsToGrant(v)
	return _u
}

// SetStatus sets the "status" field.
func (_u *PaymentOrderUpdateOne) SetStatus(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableStatus(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetWxPrepayID sets the "wx_prepay_id" field.
func (_u *PaymentOrderUpdateOne) SetWxPrepayID(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetWxPrepayID(v)
	return _u
}

// SetNillableWxPrepayID sets the "wx_prepay_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableWxPrepayID(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetWxPrepayID(*v)
	}
	return _u
}

// ClearWxPrepayID clears the value of the "wx_prepay_id" field.
func (_u *PaymentOrderUpdateOne) ClearWxPrepayID() *PaymentOrderUpdateOne {
	_u.mutation.ClearWxPrepayID()
	return _u
}

// SetWxTransactionID sets the "wx_transaction_id" field.
func (_u *PaymentOrderUpdateOne) SetWxTransactionID(v string) *PaymentOrderUpdateOne {
	_u.mutation.SetWxTransactionID(v)
	return _u
}

// SetNillableWxTransactionID sets the "wx_transaction_id" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillableWxTransactionID(v *string) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetWxTransactionID(*v)
	}
	return _u
}

// ClearWxTransactionID clears the value of the "wx_transaction_id" field.
func (_u *PaymentOrderUpdateOne) ClearWxTransactionID() *PaymentOrderUpdateOne {
	_u.mutation.ClearWxTransactionID()
	return _u
}

// SetPaidAt sets the "paid_at" field.
func (_u *PaymentOrderUpdateOne) SetPaidAt(v time.Time) *PaymentOrderUpdateOne {
	_u.mutation.SetPaidAt(v)
	return _u
}

// SetNillablePaidAt sets the "paid_at" field if the given value is not nil.
func (_u *PaymentOrderUpdateOne) SetNillablePaidAt(v *time.Time) *PaymentOrderUpdateOne {
	if v != nil {
		_u.SetPaidAt(*v)
	}
	return _u
}

// ClearPaidAt clears the value of the "paid_at" field.
func (_u *PaymentOrderUpdateOne) ClearPaidAt() *PaymentOrderUpdateOne {
	_u.mutation.ClearPaidAt()
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *PaymentOrderUpdateOne) SetUser(v *User) *PaymentOrderUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the PaymentOrderMutation object of the builder.
func (_u *PaymentOrderUpdateOne) Mutation() *PaymentOrderMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *PaymentOrderUpdateOne) ClearUser() *PaymentOrderUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the PaymentOrderUpdate builder.
func (_u *PaymentOrderUpdateOne) Where(ps ...predicate.PaymentOrder) *PaymentOrderUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PaymentOrderUpdateOne) Select(field string, fields ...string) *PaymentOrderUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PaymentOrder entity.
func (_u *PaymentOrderUpdateOne) Save(ctx context.Context) (*PaymentOrder, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PaymentOrderUpdateOne) SaveX(ctx context.Context) *PaymentOrder {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PaymentOrderUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PaymentOrderUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PaymentOrderUpdateOne) check() error {
	if v, ok := _u.mutation.PackageID(); ok {
		if err := paymentorder.PackageIDValidator(v); err != nil {
			return &ValidationError{Name: "package_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.package_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.AmountCents(); ok {
		if err := paymentorder.AmountCentsValidator(v); err != nil {
			return &ValidationError{Name: "amount_cents", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.amount_cents": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DiamondsToGrant(); ok {
		if err := paymentorder.DiamondsToGrantValidator(v); err != nil {
			return &ValidationError{Name: "diamonds_to_grant", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.diamonds_to_grant": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := paymentorder.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.status": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WxPrepayID(); ok {
		if err := paymentorder.WxPrepayIDValidator(v); err != nil {
			return &ValidationError{Name: "wx_prepay_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.wx_prepay_id": %w`, err)}
		}
	}
	if v, ok := _u.mutation.WxTransactionID(); ok {
		if err := paymentorder.WxTransactionIDValidator(v); err != nil {
			return &ValidationError{Name: "wx_transaction_id", err: fmt.Errorf(`ent: validator failed for field "PaymentOrder.wx_transaction_id": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PaymentOrder.user"`)
	}
	return nil
}

func (_u *PaymentOrderUpdateOne) sqlSave(ctx context.Context) (_node *PaymentOrder, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(paymentorder.Table, paymentorder.Columns, sqlgraph.NewFieldSpec(paymentorder.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PaymentOrder.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, paymentorder.FieldID)
		for _, f := range fields {
			if !paymentorder.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != paymentorder.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.PackageID(); ok {
		_spec.SetField(paymentorder.FieldPackageID, field.TypeString, value)
	}
	if value, ok := _u.mutation.AmountCents(); ok {
		_spec.SetField(paymentorder.FieldAmountCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAmountCents(); ok {
		_spec.AddField(paymentorder.FieldAmountCents, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DiamondsToGrant(); ok {
		_spec.SetField(paymentorder.FieldDiamondsToGrant, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDiamondsToGrant(); ok {
		_spec.AddField(paymentorder.FieldDiamondsToGrant, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(paymentorder.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.WxPrepayID(); ok {
		_spec.SetField(paymentorder.FieldWxPrepayID, field.TypeString, value)
	}
	if _u.mutation.WxPrepayIDCleared() {
		_spec.ClearField(paymentorder.FieldWxPrepayID, field.TypeString)
	}
	if value, ok := _u.mutation.WxTransactionID(); ok {
		_spec.SetField(paymentorder.FieldWxTransactionID, field.TypeString, value)
	}
	if _u.mutation.WxTransactionIDCleared() {
		_spec.ClearField(paymentorder.FieldWxTransactionID, field.TypeString)
	}
	if value, ok := _u.mutation.PaidAt(); ok {
		_spec.SetField(paymentorder.FieldPaidAt, field.TypeTime, value)
	}
	if _u.mutation.PaidAtCleared() {
		_spec.ClearField(paymentorder.FieldPaidAt, field.TypeTime)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   paymentorder.UserTable,
			Columns: []string{paymentorder.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PaymentOrder{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{paymentorder.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
