// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/predicate"
	"github.com/liukai/farmer/server/ent/relationship"
	"github.com/liukai/farmer/server/ent/user"
)

// RelationshipUpdate is the builder for updating Relationship entities.
type RelationshipUpdate struct {
	config
	hooks    []Hook
	mutation *RelationshipMutation
}

// Where appends a list predicates to the RelationshipUpdate builder.
func (_u *RelationshipUpdate) Where(ps ...predicate.Relationship) *RelationshipUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RelationshipUpdate) SetUpdatedAt(v time.Time) *RelationshipUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserAID sets the "user_a_id" field.
func (_u *RelationshipUpdate) SetUserAID(v uuid.UUID) *RelationshipUpdate {
	_u.mutation.SetUserAID(v)
	return _u
}

// SetNillableUserAID sets the "user_a_id" field if the given value is not nil.
func (_u *RelationshipUpdate) SetNillableUserAID(v *uuid.UUID) *RelationshipUpdate {
	if v != nil {
		_u.SetUserAID(*v)
	}
	return _u
}

// SetUserBID sets the "user_b_id" field.
func (_u *RelationshipUpdate) SetUserBID(v uuid.UUID) *RelationshipUpdate {
	_u.mutation.SetUserBID(v)
	return _u
}

// SetNillableUserBID sets the "user_b_id" field if the given value is not nil.
func (_u *RelationshipUpdate) SetNillableUserBID(v *uuid.UUID) *RelationshipUpdate {
	if v != nil {
		_u.SetUserBID(*v)
	}
	return _u
}

// SetAffinity sets the "affinity" field.
func (_u *RelationshipUpdate) SetAffinity(v int) *RelationshipUpdate {
	_u.mutation.ResetAffinity()
	_u.mutation.SetAffinity(v)
	return _u
}

// SetNillableAffinity sets the "affinity" field if the given value is not nil.
func (_u *RelationshipUpdate) SetNillableAffinity(v *int) *RelationshipUpdate {
	if v != nil {
		_u.SetAffinity(*v)
	}
	return _u
}

// AddAffinity adds value to the "affinity" field.
func (_u *RelationshipUpdate) AddAffinity(v int) *RelationshipUpdate {
	_u.mutation.AddAffinity(v)
	return _u
}

// SetLevel sets the "level" field.
func (_u *RelationshipUpdate) SetLevel(v string) *RelationshipUpdate {
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *RelationshipUpdate) SetNillableLevel(v *string) *RelationshipUpdate {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// SetLastInteractAt sets the "last_interact_at" field.
func (_u *RelationshipUpdate) SetLastInteractAt(v time.Time) *RelationshipUpdate {
	_u.mutation.SetLastInteractAt(v)
	return _u
}

// SetNillableLastInteractAt sets the "last_interact_at" field if the given value is not nil.
func (_u *RelationshipUpdate) SetNillableLastInteractAt(v *time.Time) *RelationshipUpdate {
	if v != nil {
		_u.SetLastInteractAt(*v)
	}
	return _u
}

// SetUserA sets the "user_a" edge to the User entity.
func (_u *RelationshipUpdate) SetUserA(v *User) *RelationshipUpdate {
	return _u.SetUserAID(v.ID)
}

// SetUserB sets the "user_b" edge to the User entity.
func (_u *RelationshipUpdate) SetUserB(v *User) *RelationshipUpdate {
	return _u.SetUserBID(v.ID)
}

// Mutation returns the RelationshipMutation object of the builder.
func (_u *RelationshipUpdate) Mutation() *RelationshipMutation {
	return _u.mutation
}

// ClearUserA clears the "user_a" edge to the User entity.
func (_u *RelationshipUpdate) ClearUserA() *RelationshipUpdate {
	_u.mutation.ClearUserA()
	return _u
}

// ClearUserB clears the "user_b" edge to the User entity.
func (_u *RelationshipUpdate) ClearUserB() *RelationshipUpdate {
	_u.mutation.ClearUserB()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RelationshipUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelationshipUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RelationshipUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelationshipUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RelationshipUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := relationship.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelationshipUpdate) check() error {
	if v, ok := _u.mutation.Affinity(); ok {
		if err := relationship.AffinityValidator(v); err != nil {
			return &ValidationError{Name: "affinity", err: fmt.Errorf(`ent: validator failed for field "Relationship.affinity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Level(); ok {
		if err := relationship.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "Relationship.level": %w`, err)}
		}
	}
	if _u.mutation.UserACleared() && len(_u.mutation.UserAIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Relationship.user_a"`)
	}
	if _u.mutation.UserBCleared() && len(_u.mutation.UserBIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Relationship.user_b"`)
	}
	return nil
}

func (_u *RelationshipUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relationship.Table, relationship.Columns, sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(relationship.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Affinity(); ok {
		_spec.SetField(relationship.FieldAffinity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAffinity(); ok {
		_spec.AddField(relationship.FieldAffinity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(relationship.FieldLevel, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastInteractAt(); ok {
		_spec.SetField(relationship.FieldLastInteractAt, field.TypeTime, value)
	}
	if _u.mutation.UserACleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relationship.UserATable,
			Columns: []string{relationship.UserAColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserAIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relationship.UserATable,
			Columns: []string{relationship.UserAColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserBCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relationship.UserBTable,
			Columns: []string{relationship.UserBColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserBIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relationship.UserBTable,
			Columns: []string{relationship.UserBColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relationship.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RelationshipUpdateOne is the builder for updating a single Relationship entity.
type RelationshipUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RelationshipMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RelationshipUpdateOne) SetUpdatedAt(v time.Time) *RelationshipUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserAID sets the "user_a_id" field.
func (_u *RelationshipUpdateOne) SetUserAID(v uuid.UUID) *RelationshipUpdateOne {
	_u.mutation.SetUserAID(v)
	return _u
}

// SetNillableUserAID sets the "user_a_id" field if the given value is not nil.
func (_u *RelationshipUpdateOne) SetNillableUserAID(v *uuid.UUID) *RelationshipUpdateOne {
	if v != nil {
		_u.SetUserAID(*v)
	}
	return _u
}

// SetUserBID sets the "user_b_id" field.
func (_u *RelationshipUpdateOne) SetUserBID(v uuid.UUID) *RelationshipUpdateOne {
	_u.mutation.SetUserBID(v)
	return _u
}

// SetNillableUserBID sets the "user_b_id" field if the given value is not nil.
func (_u *RelationshipUpdateOne) SetNillableUserBID(v *uuid.UUID) *RelationshipUpdateOne {
	if v != nil {
		_u.SetUserBID(*v)
	}
	return _u
}

// SetAffinity sets the "affinity" field.
func (_u *RelationshipUpdateOne) SetAffinity(v int) *RelationshipUpdateOne {
	_u.mutation.ResetAffinity()
	_u.mutation.SetAffinity(v)
	return _u
}

// SetNillableAffinity sets the "affinity" field if the given value is not nil.
func (_u *RelationshipUpdateOne) SetNillableAffinity(v *int) *RelationshipUpdateOne {
	if v != nil {
		_u.SetAffinity(*v)
	}
	return _u
}

// AddAffinity adds value to the "affinity" field.
func (_u *RelationshipUpdateOne) AddAffinity(v int) *RelationshipUpdateOne {
	_u.mutation.AddAffinity(v)
	return _u
}

// SetLevel sets the "level" field.
func (_u *RelationshipUpdateOne) SetLevel(v string) *RelationshipUpdateOne {
	_u.mutation.SetLevel(v)
	return _u
}

// SetNillableLevel sets the "level" field if the given value is not nil.
func (_u *RelationshipUpdateOne) SetNillableLevel(v *string) *RelationshipUpdateOne {
	if v != nil {
		_u.SetLevel(*v)
	}
	return _u
}

// SetLastInteractAt sets the "last_interact_at" field.
func (_u *RelationshipUpdateOne) SetLastInteractAt(v time.Time) *RelationshipUpdateOne {
	_u.mutation.SetLastInteractAt(v)
	return _u
}

// SetNillableLastInteractAt sets the "last_interact_at" field if the given value is not nil.
func (_u *RelationshipUpdateOne) SetNillableLastInteractAt(v *time.Time) *RelationshipUpdateOne {
	if v != nil {
		_u.SetLastInteractAt(*v)
	}
	return _u
}

// SetUserA sets the "user_a" edge to the User entity.
func (_u *RelationshipUpdateOne) SetUserA(v *User) *RelationshipUpdateOne {
	return _u.SetUserAID(v.ID)
}

// SetUserB sets the "user_b" edge to the User entity.
func (_u *RelationshipUpdateOne) SetUserB(v *User) *RelationshipUpdateOne {
	return _u.SetUserBID(v.ID)
}

// Mutation returns the RelationshipMutation object of the builder.
func (_u *RelationshipUpdateOne) Mutation() *RelationshipMutation {
	return _u.mutation
}

// ClearUserA clears the "user_a" edge to the User entity.
func (_u *RelationshipUpdateOne) ClearUserA() *RelationshipUpdateOne {
	_u.mutation.ClearUserA()
	return _u
}

// ClearUserB clears the "user_b" edge to the User entity.
func (_u *RelationshipUpdateOne) ClearUserB() *RelationshipUpdateOne {
	_u.mutation.ClearUserB()
	return _u
}

// Where appends a list predicates to the RelationshipUpdate builder.
func (_u *RelationshipUpdateOne) Where(ps ...predicate.Relationship) *RelationshipUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RelationshipUpdateOne) Select(field string, fields ...string) *RelationshipUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Relationship entity.
func (_u *RelationshipUpdateOne) Save(ctx context.Context) (*Relationship, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RelationshipUpdateOne) SaveX(ctx context.Context) *Relationship {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RelationshipUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RelationshipUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RelationshipUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := relationship.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RelationshipUpdateOne) check() error {
	if v, ok := _u.mutation.Affinity(); ok {
		if err := relationship.AffinityValidator(v); err != nil {
			return &ValidationError{Name: "affinity", err: fmt.Errorf(`ent: validator failed for field "Relationship.affinity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Level(); ok {
		if err := relationship.LevelValidator(v); err != nil {
			return &ValidationError{Name: "level", err: fmt.Errorf(`ent: validator failed for field "Relationship.level": %w`, err)}
		}
	}
	if _u.mutation.UserACleared() && len(_u.mutation.UserAIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Relationship.user_a"`)
	}
	if _u.mutation.UserBCleared() && len(_u.mutation.UserBIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Relationship.user_b"`)
	}
	return nil
}

func (_u *RelationshipUpdateOne) sqlSave(ctx context.Context) (_node *Relationship, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(relationship.Table, relationship.Columns, sqlgraph.NewFieldSpec(relationship.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Relationship.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, relationship.FieldID)
		for _, f := range fields {
			if !relationship.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != relationship.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(relationship.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Affinity(); ok {
		_spec.SetField(relationship.FieldAffinity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAffinity(); ok {
		_spec.AddField(relationship.FieldAffinity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Level(); ok {
		_spec.SetField(relationship.FieldLevel, field.TypeString, value)
	}
	if value, ok := _u.mutation.LastInteractAt(); ok {
		_spec.SetField(relationship.FieldLastInteractAt, field.TypeTime, value)
	}
	if _u.mutation.UserACleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relationship.UserATable,
			Columns: []string{relationship.UserAColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserAIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relationship.UserATable,
			Columns: []string{relationship.UserAColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UserBCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relationship.UserBTable,
			Columns: []string{relationship.UserBColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserBIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   relationship.UserBTable,
			Columns: []string{relationship.UserBColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Relationship{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{relationship.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
