// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/predicate"
	"github.com/liukai/farmer/server/ent/role"
	"github.com/liukai/farmer/server/ent/user"
)

// RoleUpdate is the builder for updating Role entities.
type RoleUpdate struct {
	config
	hooks    []Hook
	mutation *RoleMutation
}

// Where appends a list predicates to the RoleUpdate builder.
func (_u *RoleUpdate) Where(ps ...predicate.Role) *RoleUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RoleUpdate) SetUpdatedAt(v time.Time) *RoleUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RoleUpdate) SetUserID(v uuid.UUID) *RoleUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableUserID(v *uuid.UUID) *RoleUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RoleUpdate) SetName(v string) *RoleUpdate {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableName(v *string) *RoleUpdate {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAvatar sets the "avatar" field.
func (_u *RoleUpdate) SetAvatar(v string) *RoleUpdate {
	_u.mutation.SetAvatar(v)
	return _u
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableAvatar(v *string) *RoleUpdate {
	if v != nil {
		_u.SetAvatar(*v)
	}
	return _u
}

// SetExtroversion sets the "extroversion" field.
func (_u *RoleUpdate) SetExtroversion(v int) *RoleUpdate {
	_u.mutation.ResetExtroversion()
	_u.mutation.SetExtroversion(v)
	return _u
}

// SetNillableExtroversion sets the "extroversion" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableExtroversion(v *int) *RoleUpdate {
	if v != nil {
		_u.SetExtroversion(*v)
	}
	return _u
}

// AddExtroversion adds value to the "extroversion" field.
func (_u *RoleUpdate) AddExtroversion(v int) *RoleUpdate {
	_u.mutation.AddExtroversion(v)
	return _u
}

// SetGenerosity sets the "generosity" field.
func (_u *RoleUpdate) SetGenerosity(v int) *RoleUpdate {
	_u.mutation.ResetGenerosity()
	_u.mutation.SetGenerosity(v)
	return _u
}

// SetNillableGenerosity sets the "generosity" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableGenerosity(v *int) *RoleUpdate {
	if v != nil {
		_u.SetGenerosity(*v)
	}
	return _u
}

// AddGenerosity adds value to the "generosity" field.
func (_u *RoleUpdate) AddGenerosity(v int) *RoleUpdate {
	_u.mutation.AddGenerosity(v)
	return _u
}

// SetAdventure sets the "adventure" field.
func (_u *RoleUpdate) SetAdventure(v int) *RoleUpdate {
	_u.mutation.ResetAdventure()
	_u.mutation.SetAdventure(v)
	return _u
}

// SetNillableAdventure sets the "adventure" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableAdventure(v *int) *RoleUpdate {
	if v != nil {
		_u.SetAdventure(*v)
	}
	return _u
}

// AddAdventure adds value to the "adventure" field.
func (_u *RoleUpdate) AddAdventure(v int) *RoleUpdate {
	_u.mutation.AddAdventure(v)
	return _u
}

// SetStrategyManagement sets the "strategy_management" field.
func (_u *RoleUpdate) SetStrategyManagement(v int) *RoleUpdate {
	_u.mutation.ResetStrategyManagement()
	_u.mutation.SetStrategyManagement(v)
	return _u
}

// SetNillableStrategyManagement sets the "strategy_management" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableStrategyManagement(v *int) *RoleUpdate {
	if v != nil {
		_u.SetStrategyManagement(*v)
	}
	return _u
}

// AddStrategyManagement adds value to the "strategy_management" field.
func (_u *RoleUpdate) AddStrategyManagement(v int) *RoleUpdate {
	_u.mutation.AddStrategyManagement(v)
	return _u
}

// SetStrategyPlanting sets the "strategy_planting" field.
func (_u *RoleUpdate) SetStrategyPlanting(v int) *RoleUpdate {
	_u.mutation.ResetStrategyPlanting()
	_u.mutation.SetStrategyPlanting(v)
	return _u
}

// SetNillableStrategyPlanting sets the "strategy_planting" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableStrategyPlanting(v *int) *RoleUpdate {
	if v != nil {
		_u.SetStrategyPlanting(*v)
	}
	return _u
}

// AddStrategyPlanting adds value to the "strategy_planting" field.
func (_u *RoleUpdate) AddStrategyPlanting(v int) *RoleUpdate {
	_u.mutation.AddStrategyPlanting(v)
	return _u
}

// SetStrategySocial sets the "strategy_social" field.
func (_u *RoleUpdate) SetStrategySocial(v int) *RoleUpdate {
	_u.mutation.ResetStrategySocial()
	_u.mutation.SetStrategySocial(v)
	return _u
}

// SetNillableStrategySocial sets the "strategy_social" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableStrategySocial(v *int) *RoleUpdate {
	if v != nil {
		_u.SetStrategySocial(*v)
	}
	return _u
}

// AddStrategySocial adds value to the "strategy_social" field.
func (_u *RoleUpdate) AddStrategySocial(v int) *RoleUpdate {
	_u.mutation.AddStrategySocial(v)
	return _u
}

// SetStrategyTrade sets the "strategy_trade" field.
func (_u *RoleUpdate) SetStrategyTrade(v int) *RoleUpdate {
	_u.mutation.ResetStrategyTrade()
	_u.mutation.SetStrategyTrade(v)
	return _u
}

// SetNillableStrategyTrade sets the "strategy_trade" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableStrategyTrade(v *int) *RoleUpdate {
	if v != nil {
		_u.SetStrategyTrade(*v)
	}
	return _u
}

// AddStrategyTrade adds value to the "strategy_trade" field.
func (_u *RoleUpdate) AddStrategyTrade(v int) *RoleUpdate {
	_u.mutation.AddStrategyTrade(v)
	return _u
}

// SetStrategyResource sets the "strategy_resource" field.
func (_u *RoleUpdate) SetStrategyResource(v int) *RoleUpdate {
	_u.mutation.ResetStrategyResource()
	_u.mutation.SetStrategyResource(v)
	return _u
}

// SetNillableStrategyResource sets the "strategy_resource" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableStrategyResource(v *int) *RoleUpdate {
	if v != nil {
		_u.SetStrategyResource(*v)
	}
	return _u
}

// AddStrategyResource adds value to the "strategy_resource" field.
func (_u *RoleUpdate) AddStrategyResource(v int) *RoleUpdate {
	_u.mutation.AddStrategyResource(v)
	return _u
}

// SetDailySocialCount sets the "daily_social_count" field.
func (_u *RoleUpdate) SetDailySocialCount(v int) *RoleUpdate {
	_u.mutation.ResetDailySocialCount()
	_u.mutation.SetDailySocialCount(v)
	return _u
}

// SetNillableDailySocialCount sets the "daily_social_count" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableDailySocialCount(v *int) *RoleUpdate {
	if v != nil {
		_u.SetDailySocialCount(*v)
	}
	return _u
}

// AddDailySocialCount adds value to the "daily_social_count" field.
func (_u *RoleUpdate) AddDailySocialCount(v int) *RoleUpdate {
	_u.mutation.AddDailySocialCount(v)
	return _u
}

// SetDailySocialDate sets the "daily_social_date" field.
func (_u *RoleUpdate) SetDailySocialDate(v time.Time) *RoleUpdate {
	_u.mutation.SetDailySocialDate(v)
	return _u
}

// SetNillableDailySocialDate sets the "daily_social_date" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableDailySocialDate(v *time.Time) *RoleUpdate {
	if v != nil {
		_u.SetDailySocialDate(*v)
	}
	return _u
}

// ClearDailySocialDate clears the value of the "daily_social_date" field.
func (_u *RoleUpdate) ClearDailySocialDate() *RoleUpdate {
	_u.mutation.ClearDailySocialDate()
	return _u
}

// SetLastActiveAt sets the "last_active_at" field.
func (_u *RoleUpdate) SetLastActiveAt(v time.Time) *RoleUpdate {
	_u.mutation.SetLastActiveAt(v)
	return _u
}

// SetNillableLastActiveAt sets the "last_active_at" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableLastActiveAt(v *time.Time) *RoleUpdate {
	if v != nil {
		_u.SetLastActiveAt(*v)
	}
	return _u
}

// SetMapID sets the "map_id" field.
func (_u *RoleUpdate) SetMapID(v string) *RoleUpdate {
	_u.mutation.SetMapID(v)
	return _u
}

// SetNillableMapID sets the "map_id" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableMapID(v *string) *RoleUpdate {
	if v != nil {
		_u.SetMapID(*v)
	}
	return _u
}

// SetTileX sets the "tile_x" field.
func (_u *RoleUpdate) SetTileX(v int) *RoleUpdate {
	_u.mutation.ResetTileX()
	_u.mutation.SetTileX(v)
	return _u
}

// SetNillableTileX sets the "tile_x" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableTileX(v *int) *RoleUpdate {
	if v != nil {
		_u.SetTileX(*v)
	}
	return _u
}

// AddTileX adds value to the "tile_x" field.
func (_u *RoleUpdate) AddTileX(v int) *RoleUpdate {
	_u.mutation.AddTileX(v)
	return _u
}

// SetTileY sets the "tile_y" field.
func (_u *RoleUpdate) SetTileY(v int) *RoleUpdate {
	_u.mutation.ResetTileY()
	_u.mutation.SetTileY(v)
	return _u
}

// SetNillableTileY sets the "tile_y" field if the given value is not nil.
func (_u *RoleUpdate) SetNillableTileY(v *int) *RoleUpdate {
	if v != nil {
		_u.SetTileY(*v)
	}
	return _u
}

// AddTileY adds value to the "tile_y" field.
func (_u *RoleUpdate) AddTileY(v int) *RoleUpdate {
	_u.mutation.AddTileY(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RoleUpdate) SetUser(v *User) *RoleUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the RoleMutation object of the builder.
func (_u *RoleUpdate) Mutation() *RoleMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RoleUpdate) ClearUser() *RoleUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *RoleUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoleUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *RoleUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoleUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RoleUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := role.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoleUpdate) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := role.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Role.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Avatar(); ok {
		if err := role.AvatarValidator(v); err != nil {
			return &ValidationError{Name: "avatar", err: fmt.Errorf(`ent: validator failed for field "Role.avatar": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Extroversion(); ok {
		if err := role.ExtroversionValidator(v); err != nil {
			return &ValidationError{Name: "extroversion", err: fmt.Errorf(`ent: validator failed for field "Role.extroversion": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Generosity(); ok {
		if err := role.GenerosityValidator(v); err != nil {
			return &ValidationError{Name: "generosity", err: fmt.Errorf(`ent: validator failed for field "Role.generosity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Adventure(); ok {
		if err := role.AdventureValidator(v); err != nil {
			return &ValidationError{Name: "adventure", err: fmt.Errorf(`ent: validator failed for field "Role.adventure": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StrategyManagement(); ok {
		if err := role.StrategyManagementValidator(v); err != nil {
			return &ValidationError{Name: "strategy_management", err: fmt.Errorf(`ent: validator failed for field "Role.strategy_management": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StrategyPlanting(); ok {
		if err := role.StrategyPlantingValidator(v); err != nil {
			return &ValidationError{Name: "strategy_planting", err: fmt.Errorf(`ent: validator failed for field "Role.strategy_planting": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StrategySocial(); ok {
		if err := role.StrategySocialValidator(v); err != nil {
			return &ValidationError{Name: "strategy_social", err: fmt.Errorf(`ent: validator failed for field "Role.strategy_social": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StrategyTrade(); ok {
		if err := role.StrategyTradeValidator(v); err != nil {
			return &ValidationError{Name: "strategy_trade", err: fmt.Errorf(`ent: validator failed for field "Role.strategy_trade": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StrategyResource(); ok {
		if err := role.StrategyResourceValidator(v); err != nil {
			return &ValidationError{Name: "strategy_resource", err: fmt.Errorf(`ent: validator failed for field "Role.strategy_resource": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DailySocialCount(); ok {
		if err := role.DailySocialCountValidator(v); err != nil {
			return &ValidationError{Name: "daily_social_count", err: fmt.Errorf(`ent: validator failed for field "Role.daily_social_count": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Role.user"`)
	}
	return nil
}

func (_u *RoleUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(role.Table, role.Columns, sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(role.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(role.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Avatar(); ok {
		_spec.SetField(role.FieldAvatar, field.TypeString, value)
	}
	if value, ok := _u.mutation.Extroversion(); ok {
		_spec.SetField(role.FieldExtroversion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExtroversion(); ok {
		_spec.AddField(role.FieldExtroversion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Generosity(); ok {
		_spec.SetField(role.FieldGenerosity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGenerosity(); ok {
		_spec.AddField(role.FieldGenerosity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Adventure(); ok {
		_spec.SetField(role.FieldAdventure, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdventure(); ok {
		_spec.AddField(role.FieldAdventure, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StrategyManagement(); ok {
		_spec.SetField(role.FieldStrategyManagement, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStrategyManagement(); ok {
		_spec.AddField(role.FieldStrategyManagement, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StrategyPlanting(); ok {
		_spec.SetField(role.FieldStrategyPlanting, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStrategyPlanting(); ok {
		_spec.AddField(role.FieldStrategyPlanting, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StrategySocial(); ok {
		_spec.SetField(role.FieldStrategySocial, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStrategySocial(); ok {
		_spec.AddField(role.FieldStrategySocial, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StrategyTrade(); ok {
		_spec.SetField(role.FieldStrategyTrade, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStrategyTrade(); ok {
		_spec.AddField(role.FieldStrategyTrade, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StrategyResource(); ok {
		_spec.SetField(role.FieldStrategyResource, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStrategyResource(); ok {
		_spec.AddField(role.FieldStrategyResource, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DailySocialCount(); ok {
		_spec.SetField(role.FieldDailySocialCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDailySocialCount(); ok {
		_spec.AddField(role.FieldDailySocialCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DailySocialDate(); ok {
		_spec.SetField(role.FieldDailySocialDate, field.TypeTime, value)
	}
	if _u.mutation.DailySocialDateCleared() {
		_spec.ClearField(role.FieldDailySocialDate, field.TypeTime)
	}
	if value, ok := _u.mutation.LastActiveAt(); ok {
		_spec.SetField(role.FieldLastActiveAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MapID(); ok {
		_spec.SetField(role.FieldMapID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TileX(); ok {
		_spec.SetField(role.FieldTileX, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTileX(); ok {
		_spec.AddField(role.FieldTileX, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TileY(); ok {
		_spec.SetField(role.FieldTileY, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTileY(); ok {
		_spec.AddField(role.FieldTileY, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   role.UserTable,
			Columns: []string{role.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   role.UserTable,
			Columns: []string{role.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{role.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// RoleUpdateOne is the builder for updating a single Role entity.
type RoleUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *RoleMutation
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *RoleUpdateOne) SetUpdatedAt(v time.Time) *RoleUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *RoleUpdateOne) SetUserID(v uuid.UUID) *RoleUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableUserID(v *uuid.UUID) *RoleUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetName sets the "name" field.
func (_u *RoleUpdateOne) SetName(v string) *RoleUpdateOne {
	_u.mutation.SetName(v)
	return _u
}

// SetNillableName sets the "name" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableName(v *string) *RoleUpdateOne {
	if v != nil {
		_u.SetName(*v)
	}
	return _u
}

// SetAvatar sets the "avatar" field.
func (_u *RoleUpdateOne) SetAvatar(v string) *RoleUpdateOne {
	_u.mutation.SetAvatar(v)
	return _u
}

// SetNillableAvatar sets the "avatar" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableAvatar(v *string) *RoleUpdateOne {
	if v != nil {
		_u.SetAvatar(*v)
	}
	return _u
}

// SetExtroversion sets the "extroversion" field.
func (_u *RoleUpdateOne) SetExtroversion(v int) *RoleUpdateOne {
	_u.mutation.ResetExtroversion()
	_u.mutation.SetExtroversion(v)
	return _u
}

// SetNillableExtroversion sets the "extroversion" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableExtroversion(v *int) *RoleUpdateOne {
	if v != nil {
		_u.SetExtroversion(*v)
	}
	return _u
}

// AddExtroversion adds value to the "extroversion" field.
func (_u *RoleUpdateOne) AddExtroversion(v int) *RoleUpdateOne {
	_u.mutation.AddExtroversion(v)
	return _u
}

// SetGenerosity sets the "generosity" field.
func (_u *RoleUpdateOne) SetGenerosity(v int) *RoleUpdateOne {
	_u.mutation.ResetGenerosity()
	_u.mutation.SetGenerosity(v)
	return _u
}

// SetNillableGenerosity sets the "generosity" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableGenerosity(v *int) *RoleUpdateOne {
	if v != nil {
		_u.SetGenerosity(*v)
	}
	return _u
}

// AddGenerosity adds value to the "generosity" field.
func (_u *RoleUpdateOne) AddGenerosity(v int) *RoleUpdateOne {
	_u.mutation.AddGenerosity(v)
	return _u
}

// SetAdventure sets the "adventure" field.
func (_u *RoleUpdateOne) SetAdventure(v int) *RoleUpdateOne {
	_u.mutation.ResetAdventure()
	_u.mutation.SetAdventure(v)
	return _u
}

// SetNillableAdventure sets the "adventure" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableAdventure(v *int) *RoleUpdateOne {
	if v != nil {
		_u.SetAdventure(*v)
	}
	return _u
}

// AddAdventure adds value to the "adventure" field.
func (_u *RoleUpdateOne) AddAdventure(v int) *RoleUpdateOne {
	_u.mutation.AddAdventure(v)
	return _u
}

// SetStrategyManagement sets the "strategy_management" field.
func (_u *RoleUpdateOne) SetStrategyManagement(v int) *RoleUpdateOne {
	_u.mutation.ResetStrategyManagement()
	_u.mutation.SetStrategyManagement(v)
	return _u
}

// SetNillableStrategyManagement sets the "strategy_management" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableStrategyManagement(v *int) *RoleUpdateOne {
	if v != nil {
		_u.SetStrategyManagement(*v)
	}
	return _u
}

// AddStrategyManagement adds value to the "strategy_management" field.
func (_u *RoleUpdateOne) AddStrategyManagement(v int) *RoleUpdateOne {
	_u.mutation.AddStrategyManagement(v)
	return _u
}

// SetStrategyPlanting sets the "strategy_planting" field.
func (_u *RoleUpdateOne) SetStrategyPlanting(v int) *RoleUpdateOne {
	_u.mutation.ResetStrategyPlanting()
	_u.mutation.SetStrategyPlanting(v)
	return _u
}

// SetNillableStrategyPlanting sets the "strategy_planting" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableStrategyPlanting(v *int) *RoleUpdateOne {
	if v != nil {
		_u.SetStrategyPlanting(*v)
	}
	return _u
}

// AddStrategyPlanting adds value to the "strategy_planting" field.
func (_u *RoleUpdateOne) AddStrategyPlanting(v int) *RoleUpdateOne {
	_u.mutation.AddStrategyPlanting(v)
	return _u
}

// SetStrategySocial sets the "strategy_social" field.
func (_u *RoleUpdateOne) SetStrategySocial(v int) *RoleUpdateOne {
	_u.mutation.ResetStrategySocial()
	_u.mutation.SetStrategySocial(v)
	return _u
}

// SetNillableStrategySocial sets the "strategy_social" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableStrategySocial(v *int) *RoleUpdateOne {
	if v != nil {
		_u.SetStrategySocial(*v)
	}
	return _u
}

// AddStrategySocial adds value to the "strategy_social" field.
func (_u *RoleUpdateOne) AddStrategySocial(v int) *RoleUpdateOne {
	_u.mutation.AddStrategySocial(v)
	return _u
}

// SetStrategyTrade sets the "strategy_trade" field.
func (_u *RoleUpdateOne) SetStrategyTrade(v int) *RoleUpdateOne {
	_u.mutation.ResetStrategyTrade()
	_u.mutation.SetStrategyTrade(v)
	return _u
}

// SetNillableStrategyTrade sets the "strategy_trade" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableStrategyTrade(v *int) *RoleUpdateOne {
	if v != nil {
		_u.SetStrategyTrade(*v)
	}
	return _u
}

// AddStrategyTrade adds value to the "strategy_trade" field.
func (_u *RoleUpdateOne) AddStrategyTrade(v int) *RoleUpdateOne {
	_u.mutation.AddStrategyTrade(v)
	return _u
}

// SetStrategyResource sets the "strategy_resource" field.
func (_u *RoleUpdateOne) SetStrategyResource(v int) *RoleUpdateOne {
	_u.mutation.ResetStrategyResource()
	_u.mutation.SetStrategyResource(v)
	return _u
}

// SetNillableStrategyResource sets the "strategy_resource" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableStrategyResource(v *int) *RoleUpdateOne {
	if v != nil {
		_u.SetStrategyResource(*v)
	}
	return _u
}

// AddStrategyResource adds value to the "strategy_resource" field.
func (_u *RoleUpdateOne) AddStrategyResource(v int) *RoleUpdateOne {
	_u.mutation.AddStrategyResource(v)
	return _u
}

// SetDailySocialCount sets the "daily_social_count" field.
func (_u *RoleUpdateOne) SetDailySocialCount(v int) *RoleUpdateOne {
	_u.mutation.ResetDailySocialCount()
	_u.mutation.SetDailySocialCount(v)
	return _u
}

// SetNillableDailySocialCount sets the "daily_social_count" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableDailySocialCount(v *int) *RoleUpdateOne {
	if v != nil {
		_u.SetDailySocialCount(*v)
	}
	return _u
}

// AddDailySocialCount adds value to the "daily_social_count" field.
func (_u *RoleUpdateOne) AddDailySocialCount(v int) *RoleUpdateOne {
	_u.mutation.AddDailySocialCount(v)
	return _u
}

// SetDailySocialDate sets the "daily_social_date" field.
func (_u *RoleUpdateOne) SetDailySocialDate(v time.Time) *RoleUpdateOne {
	_u.mutation.SetDailySocialDate(v)
	return _u
}

// SetNillableDailySocialDate sets the "daily_social_date" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableDailySocialDate(v *time.Time) *RoleUpdateOne {
	if v != nil {
		_u.SetDailySocialDate(*v)
	}
	return _u
}

// ClearDailySocialDate clears the value of the "daily_social_date" field.
func (_u *RoleUpdateOne) ClearDailySocialDate() *RoleUpdateOne {
	_u.mutation.ClearDailySocialDate()
	return _u
}

// SetLastActiveAt sets the "last_active_at" field.
func (_u *RoleUpdateOne) SetLastActiveAt(v time.Time) *RoleUpdateOne {
	_u.mutation.SetLastActiveAt(v)
	return _u
}

// SetNillableLastActiveAt sets the "last_active_at" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableLastActiveAt(v *time.Time) *RoleUpdateOne {
	if v != nil {
		_u.SetLastActiveAt(*v)
	}
	return _u
}

// SetMapID sets the "map_id" field.
func (_u *RoleUpdateOne) SetMapID(v string) *RoleUpdateOne {
	_u.mutation.SetMapID(v)
	return _u
}

// SetNillableMapID sets the "map_id" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableMapID(v *string) *RoleUpdateOne {
	if v != nil {
		_u.SetMapID(*v)
	}
	return _u
}

// SetTileX sets the "tile_x" field.
func (_u *RoleUpdateOne) SetTileX(v int) *RoleUpdateOne {
	_u.mutation.ResetTileX()
	_u.mutation.SetTileX(v)
	return _u
}

// SetNillableTileX sets the "tile_x" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableTileX(v *int) *RoleUpdateOne {
	if v != nil {
		_u.SetTileX(*v)
	}
	return _u
}

// AddTileX adds value to the "tile_x" field.
func (_u *RoleUpdateOne) AddTileX(v int) *RoleUpdateOne {
	_u.mutation.AddTileX(v)
	return _u
}

// SetTileY sets the "tile_y" field.
func (_u *RoleUpdateOne) SetTileY(v int) *RoleUpdateOne {
	_u.mutation.ResetTileY()
	_u.mutation.SetTileY(v)
	return _u
}

// SetNillableTileY sets the "tile_y" field if the given value is not nil.
func (_u *RoleUpdateOne) SetNillableTileY(v *int) *RoleUpdateOne {
	if v != nil {
		_u.SetTileY(*v)
	}
	return _u
}

// AddTileY adds value to the "tile_y" field.
func (_u *RoleUpdateOne) AddTileY(v int) *RoleUpdateOne {
	_u.mutation.AddTileY(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *RoleUpdateOne) SetUser(v *User) *RoleUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the RoleMutation object of the builder.
func (_u *RoleUpdateOne) Mutation() *RoleMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *RoleUpdateOne) ClearUser() *RoleUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the RoleUpdate builder.
func (_u *RoleUpdateOne) Where(ps ...predicate.Role) *RoleUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *RoleUpdateOne) Select(field string, fields ...string) *RoleUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Role entity.
func (_u *RoleUpdateOne) Save(ctx context.Context) (*Role, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *RoleUpdateOne) SaveX(ctx context.Context) *Role {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *RoleUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *RoleUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *RoleUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := role.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *RoleUpdateOne) check() error {
	if v, ok := _u.mutation.Name(); ok {
		if err := role.NameValidator(v); err != nil {
			return &ValidationError{Name: "name", err: fmt.Errorf(`ent: validator failed for field "Role.name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Avatar(); ok {
		if err := role.AvatarValidator(v); err != nil {
			return &ValidationError{Name: "avatar", err: fmt.Errorf(`ent: validator failed for field "Role.avatar": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Extroversion(); ok {
		if err := role.ExtroversionValidator(v); err != nil {
			return &ValidationError{Name: "extroversion", err: fmt.Errorf(`ent: validator failed for field "Role.extroversion": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Generosity(); ok {
		if err := role.GenerosityValidator(v); err != nil {
			return &ValidationError{Name: "generosity", err: fmt.Errorf(`ent: validator failed for field "Role.generosity": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Adventure(); ok {
		if err := role.AdventureValidator(v); err != nil {
			return &ValidationError{Name: "adventure", err: fmt.Errorf(`ent: validator failed for field "Role.adventure": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StrategyManagement(); ok {
		if err := role.StrategyManagementValidator(v); err != nil {
			return &ValidationError{Name: "strategy_management", err: fmt.Errorf(`ent: validator failed for field "Role.strategy_management": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StrategyPlanting(); ok {
		if err := role.StrategyPlantingValidator(v); err != nil {
			return &ValidationError{Name: "strategy_planting", err: fmt.Errorf(`ent: validator failed for field "Role.strategy_planting": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StrategySocial(); ok {
		if err := role.StrategySocialValidator(v); err != nil {
			return &ValidationError{Name: "strategy_social", err: fmt.Errorf(`ent: validator failed for field "Role.strategy_social": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StrategyTrade(); ok {
		if err := role.StrategyTradeValidator(v); err != nil {
			return &ValidationError{Name: "strategy_trade", err: fmt.Errorf(`ent: validator failed for field "Role.strategy_trade": %w`, err)}
		}
	}
	if v, ok := _u.mutation.StrategyResource(); ok {
		if err := role.StrategyResourceValidator(v); err != nil {
			return &ValidationError{Name: "strategy_resource", err: fmt.Errorf(`ent: validator failed for field "Role.strategy_resource": %w`, err)}
		}
	}
	if v, ok := _u.mutation.DailySocialCount(); ok {
		if err := role.DailySocialCountValidator(v); err != nil {
			return &ValidationError{Name: "daily_social_count", err: fmt.Errorf(`ent: validator failed for field "Role.daily_social_count": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Role.user"`)
	}
	return nil
}

func (_u *RoleUpdateOne) sqlSave(ctx context.Context) (_node *Role, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(role.Table, role.Columns, sqlgraph.NewFieldSpec(role.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Role.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, role.FieldID)
		for _, f := range fields {
			if !role.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != role.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(role.FieldUpdatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Name(); ok {
		_spec.SetField(role.FieldName, field.TypeString, value)
	}
	if value, ok := _u.mutation.Avatar(); ok {
		_spec.SetField(role.FieldAvatar, field.TypeString, value)
	}
	if value, ok := _u.mutation.Extroversion(); ok {
		_spec.SetField(role.FieldExtroversion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedExtroversion(); ok {
		_spec.AddField(role.FieldExtroversion, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Generosity(); ok {
		_spec.SetField(role.FieldGenerosity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedGenerosity(); ok {
		_spec.AddField(role.FieldGenerosity, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Adventure(); ok {
		_spec.SetField(role.FieldAdventure, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedAdventure(); ok {
		_spec.AddField(role.FieldAdventure, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StrategyManagement(); ok {
		_spec.SetField(role.FieldStrategyManagement, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStrategyManagement(); ok {
		_spec.AddField(role.FieldStrategyManagement, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StrategyPlanting(); ok {
		_spec.SetField(role.FieldStrategyPlanting, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStrategyPlanting(); ok {
		_spec.AddField(role.FieldStrategyPlanting, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StrategySocial(); ok {
		_spec.SetField(role.FieldStrategySocial, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStrategySocial(); ok {
		_spec.AddField(role.FieldStrategySocial, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StrategyTrade(); ok {
		_spec.SetField(role.FieldStrategyTrade, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStrategyTrade(); ok {
		_spec.AddField(role.FieldStrategyTrade, field.TypeInt, value)
	}
	if value, ok := _u.mutation.StrategyResource(); ok {
		_spec.SetField(role.FieldStrategyResource, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedStrategyResource(); ok {
		_spec.AddField(role.FieldStrategyResource, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DailySocialCount(); ok {
		_spec.SetField(role.FieldDailySocialCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDailySocialCount(); ok {
		_spec.AddField(role.FieldDailySocialCount, field.TypeInt, value)
	}
	if value, ok := _u.mutation.DailySocialDate(); ok {
		_spec.SetField(role.FieldDailySocialDate, field.TypeTime, value)
	}
	if _u.mutation.DailySocialDateCleared() {
		_spec.ClearField(role.FieldDailySocialDate, field.TypeTime)
	}
	if value, ok := _u.mutation.LastActiveAt(); ok {
		_spec.SetField(role.FieldLastActiveAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.MapID(); ok {
		_spec.SetField(role.FieldMapID, field.TypeString, value)
	}
	if value, ok := _u.mutation.TileX(); ok {
		_spec.SetField(role.FieldTileX, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTileX(); ok {
		_spec.AddField(role.FieldTileX, field.TypeInt, value)
	}
	if value, ok := _u.mutation.TileY(); ok {
		_spec.SetField(role.FieldTileY, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedTileY(); ok {
		_spec.AddField(role.FieldTileY, field.TypeInt, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   role.UserTable,
			Columns: []string{role.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   role.UserTable,
			Columns: []string{role.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Role{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{role.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
