// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/activitycomment"
	"github.com/liukai/farmer/server/ent/activitylike"
	"github.com/liukai/farmer/server/ent/activitylog"
	"github.com/liukai/farmer/server/ent/animal"
	"github.com/liukai/farmer/server/ent/building"
	"github.com/liukai/farmer/server/ent/chatlog"
	"github.com/liukai/farmer/server/ent/dailycheckin"
	"github.com/liukai/farmer/server/ent/farm"
	"github.com/liukai/farmer/server/ent/friend"
	"github.com/liukai/farmer/server/ent/friendrequest"
	"github.com/liukai/farmer/server/ent/gift"
	"github.com/liukai/farmer/server/ent/helprequest"
	"github.com/liukai/farmer/server/ent/inventoryitem"
	"github.com/liukai/farmer/server/ent/notification"
	"github.com/liukai/farmer/server/ent/paymentorder"
	"github.com/liukai/farmer/server/ent/relationship"
	"github.com/liukai/farmer/server/ent/role"
	"github.com/liukai/farmer/server/ent/schema"
	"github.com/liukai/farmer/server/ent/season"
	"github.com/liukai/farmer/server/ent/seasonscore"
	"github.com/liukai/farmer/server/ent/seasontaskprogress"
	"github.com/liukai/farmer/server/ent/subscription"
	"github.com/liukai/farmer/server/ent/tradeorder"
	"github.com/liukai/farmer/server/ent/tradetransaction"
	"github.com/liukai/farmer/server/ent/tutorialprogress"
	"github.com/liukai/farmer/server/ent/user"
	"github.com/liukai/farmer/server/ent/village"
	"github.com/liukai/farmer/server/ent/villagemember"
	"github.com/liukai/farmer/server/ent/villageproject"
	"github.com/liukai/farmer/server/ent/villageprojectcontribution"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	activitycommentFields := schema.ActivityComment{}.Fields()
	_ = activitycommentFields
	// activitycommentDescContent is the schema descriptor for content field.
	activitycommentDescContent := activitycommentFields[3].Descriptor()
	// activitycomment.ContentValidator is a validator for the "content" field. It is called by the builders before save.
	activitycomment.ContentValidator = func() func(string) error {
		validators := activitycommentDescContent.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(content string) error {
			for _, fn := range fns {
				if err := fn(content); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// activitycommentDescCreatedAt is the schema descriptor for created_at field.
	activitycommentDescCreatedAt := activitycommentFields[4].Descriptor()
	// activitycomment.DefaultCreatedAt holds the default value on creation for the created_at field.
	activitycomment.DefaultCreatedAt = activitycommentDescCreatedAt.Default.(func() time.Time)
	// activitycommentDescID is the schema descriptor for id field.
	activitycommentDescID := activitycommentFields[0].Descriptor()
	// activitycomment.DefaultID holds the default value on creation for the id field.
	activitycomment.DefaultID = activitycommentDescID.Default.(func() uuid.UUID)
	activitylikeFields := schema.ActivityLike{}.Fields()
	_ = activitylikeFields
	// activitylikeDescCreatedAt is the schema descriptor for created_at field.
	activitylikeDescCreatedAt := activitylikeFields[3].Descriptor()
	// activitylike.DefaultCreatedAt holds the default value on creation for the created_at field.
	activitylike.DefaultCreatedAt = activitylikeDescCreatedAt.Default.(func() time.Time)
	// activitylikeDescID is the schema descriptor for id field.
	activitylikeDescID := activitylikeFields[0].Descriptor()
	// activitylike.DefaultID holds the default value on creation for the id field.
	activitylike.DefaultID = activitylikeDescID.Default.(func() uuid.UUID)
	activitylogFields := schema.ActivityLog{}.Fields()
	_ = activitylogFields
	// activitylogDescType is the schema descriptor for type field.
	activitylogDescType := activitylogFields[3].Descriptor()
	// activitylog.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	activitylog.TypeValidator = activitylogDescType.Validators[0].(func(string) error)
	// activitylogDescMeta is the schema descriptor for meta field.
	activitylogDescMeta := activitylogFields[5].Descriptor()
	// activitylog.DefaultMeta holds the default value on creation for the meta field.
	activitylog.DefaultMeta = activitylogDescMeta.Default.(map[string]interface{})
	// activitylogDescLikeCount is the schema descriptor for like_count field.
	activitylogDescLikeCount := activitylogFields[6].Descriptor()
	// activitylog.DefaultLikeCount holds the default value on creation for the like_count field.
	activitylog.DefaultLikeCount = activitylogDescLikeCount.Default.(int)
	// activitylog.LikeCountValidator is a validator for the "like_count" field. It is called by the builders before save.
	activitylog.LikeCountValidator = activitylogDescLikeCount.Validators[0].(func(int) error)
	// activitylogDescCommentCount is the schema descriptor for comment_count field.
	activitylogDescCommentCount := activitylogFields[7].Descriptor()
	// activitylog.DefaultCommentCount holds the default value on creation for the comment_count field.
	activitylog.DefaultCommentCount = activitylogDescCommentCount.Default.(int)
	// activitylog.CommentCountValidator is a validator for the "comment_count" field. It is called by the builders before save.
	activitylog.CommentCountValidator = activitylogDescCommentCount.Validators[0].(func(int) error)
	// activitylogDescCreatedAt is the schema descriptor for created_at field.
	activitylogDescCreatedAt := activitylogFields[8].Descriptor()
	// activitylog.DefaultCreatedAt holds the default value on creation for the created_at field.
	activitylog.DefaultCreatedAt = activitylogDescCreatedAt.Default.(func() time.Time)
	// activitylogDescID is the schema descriptor for id field.
	activitylogDescID := activitylogFields[0].Descriptor()
	// activitylog.DefaultID holds the default value on creation for the id field.
	activitylog.DefaultID = activitylogDescID.Default.(func() uuid.UUID)
	animalMixin := schema.Animal{}.Mixin()
	animalMixinFields0 := animalMixin[0].Fields()
	_ = animalMixinFields0
	animalFields := schema.Animal{}.Fields()
	_ = animalFields
	// animalDescCreatedAt is the schema descriptor for created_at field.
	animalDescCreatedAt := animalMixinFields0[0].Descriptor()
	// animal.DefaultCreatedAt holds the default value on creation for the created_at field.
	animal.DefaultCreatedAt = animalDescCreatedAt.Default.(func() time.Time)
	// animalDescUpdatedAt is the schema descriptor for updated_at field.
	animalDescUpdatedAt := animalMixinFields0[1].Descriptor()
	// animal.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	animal.DefaultUpdatedAt = animalDescUpdatedAt.Default.(func() time.Time)
	// animal.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	animal.UpdateDefaultUpdatedAt = animalDescUpdatedAt.UpdateDefault.(func() time.Time)
	// animalDescType is the schema descriptor for type field.
	animalDescType := animalFields[2].Descriptor()
	// animal.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	animal.TypeValidator = animalDescType.Validators[0].(func(string) error)
	// animalDescName is the schema descriptor for name field.
	animalDescName := animalFields[3].Descriptor()
	// animal.NameValidator is a validator for the "name" field. It is called by the builders before save.
	animal.NameValidator = animalDescName.Validators[0].(func(string) error)
	// animalDescMood is the schema descriptor for mood field.
	animalDescMood := animalFields[4].Descriptor()
	// animal.DefaultMood holds the default value on creation for the mood field.
	animal.DefaultMood = animalDescMood.Default.(int)
	// animal.MoodValidator is a validator for the "mood" field. It is called by the builders before save.
	animal.MoodValidator = func() func(int) error {
		validators := animalDescMood.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(mood int) error {
			for _, fn := range fns {
				if err := fn(mood); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// animalDescHealth is the schema descriptor for health field.
	animalDescHealth := animalFields[5].Descriptor()
	// animal.DefaultHealth holds the default value on creation for the health field.
	animal.DefaultHealth = animalDescHealth.Default.(int)
	// animal.HealthValidator is a validator for the "health" field. It is called by the builders before save.
	animal.HealthValidator = func() func(int) error {
		validators := animalDescHealth.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(health int) error {
			for _, fn := range fns {
				if err := fn(health); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// animalDescID is the schema descriptor for id field.
	animalDescID := animalFields[0].Descriptor()
	// animal.DefaultID holds the default value on creation for the id field.
	animal.DefaultID = animalDescID.Default.(func() uuid.UUID)
	buildingMixin := schema.Building{}.Mixin()
	buildingMixinFields0 := buildingMixin[0].Fields()
	_ = buildingMixinFields0
	buildingFields := schema.Building{}.Fields()
	_ = buildingFields
	// buildingDescCreatedAt is the schema descriptor for created_at field.
	buildingDescCreatedAt := buildingMixinFields0[0].Descriptor()
	// building.DefaultCreatedAt holds the default value on creation for the created_at field.
	building.DefaultCreatedAt = buildingDescCreatedAt.Default.(func() time.Time)
	// buildingDescUpdatedAt is the schema descriptor for updated_at field.
	buildingDescUpdatedAt := buildingMixinFields0[1].Descriptor()
	// building.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	building.DefaultUpdatedAt = buildingDescUpdatedAt.Default.(func() time.Time)
	// building.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	building.UpdateDefaultUpdatedAt = buildingDescUpdatedAt.UpdateDefault.(func() time.Time)
	// buildingDescType is the schema descriptor for type field.
	buildingDescType := buildingFields[2].Descriptor()
	// building.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	building.TypeValidator = buildingDescType.Validators[0].(func(string) error)
	// buildingDescLevel is the schema descriptor for level field.
	buildingDescLevel := buildingFields[3].Descriptor()
	// building.DefaultLevel holds the default value on creation for the level field.
	building.DefaultLevel = buildingDescLevel.Default.(int)
	// building.LevelValidator is a validator for the "level" field. It is called by the builders before save.
	building.LevelValidator = func() func(int) error {
		validators := buildingDescLevel.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(level int) error {
			for _, fn := range fns {
				if err := fn(level); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// buildingDescState is the schema descriptor for state field.
	buildingDescState := buildingFields[6].Descriptor()
	// building.DefaultState holds the default value on creation for the state field.
	building.DefaultState = buildingDescState.Default.(string)
	// building.StateValidator is a validator for the "state" field. It is called by the builders before save.
	building.StateValidator = buildingDescState.Validators[0].(func(string) error)
	// buildingDescID is the schema descriptor for id field.
	buildingDescID := buildingFields[0].Descriptor()
	// building.DefaultID holds the default value on creation for the id field.
	building.DefaultID = buildingDescID.Default.(func() uuid.UUID)
	chatlogFields := schema.ChatLog{}.Fields()
	_ = chatlogFields
	// chatlogDescScene is the schema descriptor for scene field.
	chatlogDescScene := chatlogFields[4].Descriptor()
	// chatlog.SceneValidator is a validator for the "scene" field. It is called by the builders before save.
	chatlog.SceneValidator = chatlogDescScene.Validators[0].(func(string) error)
	// chatlogDescIsLlmGenerated is the schema descriptor for is_llm_generated field.
	chatlogDescIsLlmGenerated := chatlogFields[6].Descriptor()
	// chatlog.DefaultIsLlmGenerated holds the default value on creation for the is_llm_generated field.
	chatlog.DefaultIsLlmGenerated = chatlogDescIsLlmGenerated.Default.(bool)
	// chatlogDescCreatedAt is the schema descriptor for created_at field.
	chatlogDescCreatedAt := chatlogFields[7].Descriptor()
	// chatlog.DefaultCreatedAt holds the default value on creation for the created_at field.
	chatlog.DefaultCreatedAt = chatlogDescCreatedAt.Default.(func() time.Time)
	// chatlogDescID is the schema descriptor for id field.
	chatlogDescID := chatlogFields[0].Descriptor()
	// chatlog.DefaultID holds the default value on creation for the id field.
	chatlog.DefaultID = chatlogDescID.Default.(func() uuid.UUID)
	dailycheckinFields := schema.DailyCheckin{}.Fields()
	_ = dailycheckinFields
	// dailycheckinDescConsecutiveDays is the schema descriptor for consecutive_days field.
	dailycheckinDescConsecutiveDays := dailycheckinFields[3].Descriptor()
	// dailycheckin.ConsecutiveDaysValidator is a validator for the "consecutive_days" field. It is called by the builders before save.
	dailycheckin.ConsecutiveDaysValidator = dailycheckinDescConsecutiveDays.Validators[0].(func(int) error)
	// dailycheckinDescRewardType is the schema descriptor for reward_type field.
	dailycheckinDescRewardType := dailycheckinFields[4].Descriptor()
	// dailycheckin.RewardTypeValidator is a validator for the "reward_type" field. It is called by the builders before save.
	dailycheckin.RewardTypeValidator = dailycheckinDescRewardType.Validators[0].(func(string) error)
	// dailycheckinDescRewardQuantity is the schema descriptor for reward_quantity field.
	dailycheckinDescRewardQuantity := dailycheckinFields[5].Descriptor()
	// dailycheckin.RewardQuantityValidator is a validator for the "reward_quantity" field. It is called by the builders before save.
	dailycheckin.RewardQuantityValidator = dailycheckinDescRewardQuantity.Validators[0].(func(int) error)
	// dailycheckinDescCreatedAt is the schema descriptor for created_at field.
	dailycheckinDescCreatedAt := dailycheckinFields[6].Descriptor()
	// dailycheckin.DefaultCreatedAt holds the default value on creation for the created_at field.
	dailycheckin.DefaultCreatedAt = dailycheckinDescCreatedAt.Default.(func() time.Time)
	// dailycheckinDescID is the schema descriptor for id field.
	dailycheckinDescID := dailycheckinFields[0].Descriptor()
	// dailycheckin.DefaultID holds the default value on creation for the id field.
	dailycheckin.DefaultID = dailycheckinDescID.Default.(func() uuid.UUID)
	farmFields := schema.Farm{}.Fields()
	_ = farmFields
	// farmDescName is the schema descriptor for name field.
	farmDescName := farmFields[2].Descriptor()
	// farm.NameValidator is a validator for the "name" field. It is called by the builders before save.
	farm.NameValidator = func() func(string) error {
		validators := farmDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// farmDescLevel is the schema descriptor for level field.
	farmDescLevel := farmFields[3].Descriptor()
	// farm.DefaultLevel holds the default value on creation for the level field.
	farm.DefaultLevel = farmDescLevel.Default.(int)
	// farm.LevelValidator is a validator for the "level" field. It is called by the builders before save.
	farm.LevelValidator = farmDescLevel.Validators[0].(func(int) error)
	// farmDescSpecialty is the schema descriptor for specialty field.
	farmDescSpecialty := farmFields[4].Descriptor()
	// farm.DefaultSpecialty holds the default value on creation for the specialty field.
	farm.DefaultSpecialty = farmDescSpecialty.Default.([]string)
	// farmDescPlots is the schema descriptor for plots field.
	farmDescPlots := farmFields[5].Descriptor()
	// farm.DefaultPlots holds the default value on creation for the plots field.
	farm.DefaultPlots = farmDescPlots.Default.([]schema.PlotState)
	// farmDescLastTickAt is the schema descriptor for last_tick_at field.
	farmDescLastTickAt := farmFields[6].Descriptor()
	// farm.DefaultLastTickAt holds the default value on creation for the last_tick_at field.
	farm.DefaultLastTickAt = farmDescLastTickAt.Default.(func() time.Time)
	// farmDescCreatedAt is the schema descriptor for created_at field.
	farmDescCreatedAt := farmFields[7].Descriptor()
	// farm.DefaultCreatedAt holds the default value on creation for the created_at field.
	farm.DefaultCreatedAt = farmDescCreatedAt.Default.(func() time.Time)
	// farmDescID is the schema descriptor for id field.
	farmDescID := farmFields[0].Descriptor()
	// farm.DefaultID holds the default value on creation for the id field.
	farm.DefaultID = farmDescID.Default.(func() uuid.UUID)
	friendFields := schema.Friend{}.Fields()
	_ = friendFields
	// friendDescCreatedAt is the schema descriptor for created_at field.
	friendDescCreatedAt := friendFields[3].Descriptor()
	// friend.DefaultCreatedAt holds the default value on creation for the created_at field.
	friend.DefaultCreatedAt = friendDescCreatedAt.Default.(func() time.Time)
	// friendDescID is the schema descriptor for id field.
	friendDescID := friendFields[0].Descriptor()
	// friend.DefaultID holds the default value on creation for the id field.
	friend.DefaultID = friendDescID.Default.(func() uuid.UUID)
	friendrequestMixin := schema.FriendRequest{}.Mixin()
	friendrequestMixinFields0 := friendrequestMixin[0].Fields()
	_ = friendrequestMixinFields0
	friendrequestFields := schema.FriendRequest{}.Fields()
	_ = friendrequestFields
	// friendrequestDescCreatedAt is the schema descriptor for created_at field.
	friendrequestDescCreatedAt := friendrequestMixinFields0[0].Descriptor()
	// friendrequest.DefaultCreatedAt holds the default value on creation for the created_at field.
	friendrequest.DefaultCreatedAt = friendrequestDescCreatedAt.Default.(func() time.Time)
	// friendrequestDescUpdatedAt is the schema descriptor for updated_at field.
	friendrequestDescUpdatedAt := friendrequestMixinFields0[1].Descriptor()
	// friendrequest.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	friendrequest.DefaultUpdatedAt = friendrequestDescUpdatedAt.Default.(func() time.Time)
	// friendrequest.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	friendrequest.UpdateDefaultUpdatedAt = friendrequestDescUpdatedAt.UpdateDefault.(func() time.Time)
	// friendrequestDescMessage is the schema descriptor for message field.
	friendrequestDescMessage := friendrequestFields[3].Descriptor()
	// friendrequest.MessageValidator is a validator for the "message" field. It is called by the builders before save.
	friendrequest.MessageValidator = friendrequestDescMessage.Validators[0].(func(string) error)
	// friendrequestDescStatus is the schema descriptor for status field.
	friendrequestDescStatus := friendrequestFields[4].Descriptor()
	// friendrequest.DefaultStatus holds the default value on creation for the status field.
	friendrequest.DefaultStatus = friendrequestDescStatus.Default.(string)
	// friendrequest.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	friendrequest.StatusValidator = friendrequestDescStatus.Validators[0].(func(string) error)
	// friendrequestDescID is the schema descriptor for id field.
	friendrequestDescID := friendrequestFields[0].Descriptor()
	// friendrequest.DefaultID holds the default value on creation for the id field.
	friendrequest.DefaultID = friendrequestDescID.Default.(func() uuid.UUID)
	giftFields := schema.Gift{}.Fields()
	_ = giftFields
	// giftDescItemID is the schema descriptor for item_id field.
	giftDescItemID := giftFields[3].Descriptor()
	// gift.ItemIDValidator is a validator for the "item_id" field. It is called by the builders before save.
	gift.ItemIDValidator = giftDescItemID.Validators[0].(func(string) error)
	// giftDescQuantity is the schema descriptor for quantity field.
	giftDescQuantity := giftFields[4].Descriptor()
	// gift.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	gift.QuantityValidator = giftDescQuantity.Validators[0].(func(int) error)
	// giftDescMessage is the schema descriptor for message field.
	giftDescMessage := giftFields[5].Descriptor()
	// gift.MessageValidator is a validator for the "message" field. It is called by the builders before save.
	gift.MessageValidator = giftDescMessage.Validators[0].(func(string) error)
	// giftDescIsAgentAction is the schema descriptor for is_agent_action field.
	giftDescIsAgentAction := giftFields[7].Descriptor()
	// gift.DefaultIsAgentAction holds the default value on creation for the is_agent_action field.
	gift.DefaultIsAgentAction = giftDescIsAgentAction.Default.(bool)
	// giftDescCreatedAt is the schema descriptor for created_at field.
	giftDescCreatedAt := giftFields[8].Descriptor()
	// gift.DefaultCreatedAt holds the default value on creation for the created_at field.
	gift.DefaultCreatedAt = giftDescCreatedAt.Default.(func() time.Time)
	// giftDescID is the schema descriptor for id field.
	giftDescID := giftFields[0].Descriptor()
	// gift.DefaultID holds the default value on creation for the id field.
	gift.DefaultID = giftDescID.Default.(func() uuid.UUID)
	helprequestFields := schema.HelpRequest{}.Fields()
	_ = helprequestFields
	// helprequestDescResourceType is the schema descriptor for resource_type field.
	helprequestDescResourceType := helprequestFields[3].Descriptor()
	// helprequest.ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	helprequest.ResourceTypeValidator = helprequestDescResourceType.Validators[0].(func(string) error)
	// helprequestDescResourceID is the schema descriptor for resource_id field.
	helprequestDescResourceID := helprequestFields[4].Descriptor()
	// helprequest.ResourceIDValidator is a validator for the "resource_id" field. It is called by the builders before save.
	helprequest.ResourceIDValidator = helprequestDescResourceID.Validators[0].(func(string) error)
	// helprequestDescQuantity is the schema descriptor for quantity field.
	helprequestDescQuantity := helprequestFields[5].Descriptor()
	// helprequest.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	helprequest.QuantityValidator = helprequestDescQuantity.Validators[0].(func(int) error)
	// helprequestDescMessage is the schema descriptor for message field.
	helprequestDescMessage := helprequestFields[6].Descriptor()
	// helprequest.MessageValidator is a validator for the "message" field. It is called by the builders before save.
	helprequest.MessageValidator = helprequestDescMessage.Validators[0].(func(string) error)
	// helprequestDescStatus is the schema descriptor for status field.
	helprequestDescStatus := helprequestFields[7].Descriptor()
	// helprequest.DefaultStatus holds the default value on creation for the status field.
	helprequest.DefaultStatus = helprequestDescStatus.Default.(string)
	// helprequest.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	helprequest.StatusValidator = helprequestDescStatus.Validators[0].(func(string) error)
	// helprequestDescCreatedAt is the schema descriptor for created_at field.
	helprequestDescCreatedAt := helprequestFields[8].Descriptor()
	// helprequest.DefaultCreatedAt holds the default value on creation for the created_at field.
	helprequest.DefaultCreatedAt = helprequestDescCreatedAt.Default.(func() time.Time)
	// helprequestDescID is the schema descriptor for id field.
	helprequestDescID := helprequestFields[0].Descriptor()
	// helprequest.DefaultID holds the default value on creation for the id field.
	helprequest.DefaultID = helprequestDescID.Default.(func() uuid.UUID)
	inventoryitemFields := schema.InventoryItem{}.Fields()
	_ = inventoryitemFields
	// inventoryitemDescItemID is the schema descriptor for item_id field.
	inventoryitemDescItemID := inventoryitemFields[2].Descriptor()
	// inventoryitem.ItemIDValidator is a validator for the "item_id" field. It is called by the builders before save.
	inventoryitem.ItemIDValidator = inventoryitemDescItemID.Validators[0].(func(string) error)
	// inventoryitemDescItemType is the schema descriptor for item_type field.
	inventoryitemDescItemType := inventoryitemFields[3].Descriptor()
	// inventoryitem.ItemTypeValidator is a validator for the "item_type" field. It is called by the builders before save.
	inventoryitem.ItemTypeValidator = inventoryitemDescItemType.Validators[0].(func(string) error)
	// inventoryitemDescQuantity is the schema descriptor for quantity field.
	inventoryitemDescQuantity := inventoryitemFields[4].Descriptor()
	// inventoryitem.DefaultQuantity holds the default value on creation for the quantity field.
	inventoryitem.DefaultQuantity = inventoryitemDescQuantity.Default.(int64)
	// inventoryitem.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	inventoryitem.QuantityValidator = inventoryitemDescQuantity.Validators[0].(func(int64) error)
	// inventoryitemDescUpdatedAt is the schema descriptor for updated_at field.
	inventoryitemDescUpdatedAt := inventoryitemFields[5].Descriptor()
	// inventoryitem.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	inventoryitem.DefaultUpdatedAt = inventoryitemDescUpdatedAt.Default.(func() time.Time)
	// inventoryitem.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	inventoryitem.UpdateDefaultUpdatedAt = inventoryitemDescUpdatedAt.UpdateDefault.(func() time.Time)
	// inventoryitemDescID is the schema descriptor for id field.
	inventoryitemDescID := inventoryitemFields[0].Descriptor()
	// inventoryitem.DefaultID holds the default value on creation for the id field.
	inventoryitem.DefaultID = inventoryitemDescID.Default.(func() uuid.UUID)
	notificationFields := schema.Notification{}.Fields()
	_ = notificationFields
	// notificationDescType is the schema descriptor for type field.
	notificationDescType := notificationFields[2].Descriptor()
	// notification.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	notification.TypeValidator = notificationDescType.Validators[0].(func(string) error)
	// notificationDescTitle is the schema descriptor for title field.
	notificationDescTitle := notificationFields[3].Descriptor()
	// notification.TitleValidator is a validator for the "title" field. It is called by the builders before save.
	notification.TitleValidator = notificationDescTitle.Validators[0].(func(string) error)
	// notificationDescIsRead is the schema descriptor for is_read field.
	notificationDescIsRead := notificationFields[5].Descriptor()
	// notification.DefaultIsRead holds the default value on creation for the is_read field.
	notification.DefaultIsRead = notificationDescIsRead.Default.(bool)
	// notificationDescActionType is the schema descriptor for action_type field.
	notificationDescActionType := notificationFields[6].Descriptor()
	// notification.ActionTypeValidator is a validator for the "action_type" field. It is called by the builders before save.
	notification.ActionTypeValidator = notificationDescActionType.Validators[0].(func(string) error)
	// notificationDescCreatedAt is the schema descriptor for created_at field.
	notificationDescCreatedAt := notificationFields[8].Descriptor()
	// notification.DefaultCreatedAt holds the default value on creation for the created_at field.
	notification.DefaultCreatedAt = notificationDescCreatedAt.Default.(func() time.Time)
	// notificationDescID is the schema descriptor for id field.
	notificationDescID := notificationFields[0].Descriptor()
	// notification.DefaultID holds the default value on creation for the id field.
	notification.DefaultID = notificationDescID.Default.(func() uuid.UUID)
	paymentorderFields := schema.PaymentOrder{}.Fields()
	_ = paymentorderFields
	// paymentorderDescPackageID is the schema descriptor for package_id field.
	paymentorderDescPackageID := paymentorderFields[2].Descriptor()
	// paymentorder.PackageIDValidator is a validator for the "package_id" field. It is called by the builders before save.
	paymentorder.PackageIDValidator = paymentorderDescPackageID.Validators[0].(func(string) error)
	// paymentorderDescAmountCents is the schema descriptor for amount_cents field.
	paymentorderDescAmountCents := paymentorderFields[3].Descriptor()
	// paymentorder.AmountCentsValidator is a validator for the "amount_cents" field. It is called by the builders before save.
	paymentorder.AmountCentsValidator = paymentorderDescAmountCents.Validators[0].(func(int) error)
	// paymentorderDescDiamondsToGrant is the schema descriptor for diamonds_to_grant field.
	paymentorderDescDiamondsToGrant := paymentorderFields[4].Descriptor()
	// paymentorder.DiamondsToGrantValidator is a validator for the "diamonds_to_grant" field. It is called by the builders before save.
	paymentorder.DiamondsToGrantValidator = paymentorderDescDiamondsToGrant.Validators[0].(func(int) error)
	// paymentorderDescStatus is the schema descriptor for status field.
	paymentorderDescStatus := paymentorderFields[5].Descriptor()
	// paymentorder.DefaultStatus holds the default value on creation for the status field.
	paymentorder.DefaultStatus = paymentorderDescStatus.Default.(string)
	// paymentorder.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	paymentorder.StatusValidator = paymentorderDescStatus.Validators[0].(func(string) error)
	// paymentorderDescWxPrepayID is the schema descriptor for wx_prepay_id field.
	paymentorderDescWxPrepayID := paymentorderFields[6].Descriptor()
	// paymentorder.WxPrepayIDValidator is a validator for the "wx_prepay_id" field. It is called by the builders before save.
	paymentorder.WxPrepayIDValidator = paymentorderDescWxPrepayID.Validators[0].(func(string) error)
	// paymentorderDescWxTransactionID is the schema descriptor for wx_transaction_id field.
	paymentorderDescWxTransactionID := paymentorderFields[7].Descriptor()
	// paymentorder.WxTransactionIDValidator is a validator for the "wx_transaction_id" field. It is called by the builders before save.
	paymentorder.WxTransactionIDValidator = paymentorderDescWxTransactionID.Validators[0].(func(string) error)
	// paymentorderDescCreatedAt is the schema descriptor for created_at field.
	paymentorderDescCreatedAt := paymentorderFields[9].Descriptor()
	// paymentorder.DefaultCreatedAt holds the default value on creation for the created_at field.
	paymentorder.DefaultCreatedAt = paymentorderDescCreatedAt.Default.(func() time.Time)
	// paymentorderDescID is the schema descriptor for id field.
	paymentorderDescID := paymentorderFields[0].Descriptor()
	// paymentorder.DefaultID holds the default value on creation for the id field.
	paymentorder.DefaultID = paymentorderDescID.Default.(func() uuid.UUID)
	relationshipMixin := schema.Relationship{}.Mixin()
	relationshipMixinFields0 := relationshipMixin[0].Fields()
	_ = relationshipMixinFields0
	relationshipFields := schema.Relationship{}.Fields()
	_ = relationshipFields
	// relationshipDescCreatedAt is the schema descriptor for created_at field.
	relationshipDescCreatedAt := relationshipMixinFields0[0].Descriptor()
	// relationship.DefaultCreatedAt holds the default value on creation for the created_at field.
	relationship.DefaultCreatedAt = relationshipDescCreatedAt.Default.(func() time.Time)
	// relationshipDescUpdatedAt is the schema descriptor for updated_at field.
	relationshipDescUpdatedAt := relationshipMixinFields0[1].Descriptor()
	// relationship.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	relationship.DefaultUpdatedAt = relationshipDescUpdatedAt.Default.(func() time.Time)
	// relationship.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	relationship.UpdateDefaultUpdatedAt = relationshipDescUpdatedAt.UpdateDefault.(func() time.Time)
	// relationshipDescAffinity is the schema descriptor for affinity field.
	relationshipDescAffinity := relationshipFields[3].Descriptor()
	// relationship.DefaultAffinity holds the default value on creation for the affinity field.
	relationship.DefaultAffinity = relationshipDescAffinity.Default.(int)
	// relationship.AffinityValidator is a validator for the "affinity" field. It is called by the builders before save.
	relationship.AffinityValidator = func() func(int) error {
		validators := relationshipDescAffinity.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(affinity int) error {
			for _, fn := range fns {
				if err := fn(affinity); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// relationshipDescLevel is the schema descriptor for level field.
	relationshipDescLevel := relationshipFields[4].Descriptor()
	// relationship.DefaultLevel holds the default value on creation for the level field.
	relationship.DefaultLevel = relationshipDescLevel.Default.(string)
	// relationship.LevelValidator is a validator for the "level" field. It is called by the builders before save.
	relationship.LevelValidator = relationshipDescLevel.Validators[0].(func(string) error)
	// relationshipDescLastInteractAt is the schema descriptor for last_interact_at field.
	relationshipDescLastInteractAt := relationshipFields[5].Descriptor()
	// relationship.DefaultLastInteractAt holds the default value on creation for the last_interact_at field.
	relationship.DefaultLastInteractAt = relationshipDescLastInteractAt.Default.(func() time.Time)
	// relationshipDescID is the schema descriptor for id field.
	relationshipDescID := relationshipFields[0].Descriptor()
	// relationship.DefaultID holds the default value on creation for the id field.
	relationship.DefaultID = relationshipDescID.Default.(func() uuid.UUID)
	roleMixin := schema.Role{}.Mixin()
	roleMixinFields0 := roleMixin[0].Fields()
	_ = roleMixinFields0
	roleFields := schema.Role{}.Fields()
	_ = roleFields
	// roleDescCreatedAt is the schema descriptor for created_at field.
	roleDescCreatedAt := roleMixinFields0[0].Descriptor()
	// role.DefaultCreatedAt holds the default value on creation for the created_at field.
	role.DefaultCreatedAt = roleDescCreatedAt.Default.(func() time.Time)
	// roleDescUpdatedAt is the schema descriptor for updated_at field.
	roleDescUpdatedAt := roleMixinFields0[1].Descriptor()
	// role.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	role.DefaultUpdatedAt = roleDescUpdatedAt.Default.(func() time.Time)
	// role.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	role.UpdateDefaultUpdatedAt = roleDescUpdatedAt.UpdateDefault.(func() time.Time)
	// roleDescName is the schema descriptor for name field.
	roleDescName := roleFields[2].Descriptor()
	// role.NameValidator is a validator for the "name" field. It is called by the builders before save.
	role.NameValidator = func() func(string) error {
		validators := roleDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescAvatar is the schema descriptor for avatar field.
	roleDescAvatar := roleFields[3].Descriptor()
	// role.AvatarValidator is a validator for the "avatar" field. It is called by the builders before save.
	role.AvatarValidator = roleDescAvatar.Validators[0].(func(string) error)
	// roleDescExtroversion is the schema descriptor for extroversion field.
	roleDescExtroversion := roleFields[4].Descriptor()
	// role.DefaultExtroversion holds the default value on creation for the extroversion field.
	role.DefaultExtroversion = roleDescExtroversion.Default.(int)
	// role.ExtroversionValidator is a validator for the "extroversion" field. It is called by the builders before save.
	role.ExtroversionValidator = func() func(int) error {
		validators := roleDescExtroversion.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(extroversion int) error {
			for _, fn := range fns {
				if err := fn(extroversion); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescGenerosity is the schema descriptor for generosity field.
	roleDescGenerosity := roleFields[5].Descriptor()
	// role.DefaultGenerosity holds the default value on creation for the generosity field.
	role.DefaultGenerosity = roleDescGenerosity.Default.(int)
	// role.GenerosityValidator is a validator for the "generosity" field. It is called by the builders before save.
	role.GenerosityValidator = func() func(int) error {
		validators := roleDescGenerosity.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(generosity int) error {
			for _, fn := range fns {
				if err := fn(generosity); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescAdventure is the schema descriptor for adventure field.
	roleDescAdventure := roleFields[6].Descriptor()
	// role.DefaultAdventure holds the default value on creation for the adventure field.
	role.DefaultAdventure = roleDescAdventure.Default.(int)
	// role.AdventureValidator is a validator for the "adventure" field. It is called by the builders before save.
	role.AdventureValidator = func() func(int) error {
		validators := roleDescAdventure.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(adventure int) error {
			for _, fn := range fns {
				if err := fn(adventure); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescStrategyManagement is the schema descriptor for strategy_management field.
	roleDescStrategyManagement := roleFields[7].Descriptor()
	// role.DefaultStrategyManagement holds the default value on creation for the strategy_management field.
	role.DefaultStrategyManagement = roleDescStrategyManagement.Default.(int)
	// role.StrategyManagementValidator is a validator for the "strategy_management" field. It is called by the builders before save.
	role.StrategyManagementValidator = func() func(int) error {
		validators := roleDescStrategyManagement.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(strategy_management int) error {
			for _, fn := range fns {
				if err := fn(strategy_management); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescStrategyPlanting is the schema descriptor for strategy_planting field.
	roleDescStrategyPlanting := roleFields[8].Descriptor()
	// role.DefaultStrategyPlanting holds the default value on creation for the strategy_planting field.
	role.DefaultStrategyPlanting = roleDescStrategyPlanting.Default.(int)
	// role.StrategyPlantingValidator is a validator for the "strategy_planting" field. It is called by the builders before save.
	role.StrategyPlantingValidator = func() func(int) error {
		validators := roleDescStrategyPlanting.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(strategy_planting int) error {
			for _, fn := range fns {
				if err := fn(strategy_planting); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescStrategySocial is the schema descriptor for strategy_social field.
	roleDescStrategySocial := roleFields[9].Descriptor()
	// role.DefaultStrategySocial holds the default value on creation for the strategy_social field.
	role.DefaultStrategySocial = roleDescStrategySocial.Default.(int)
	// role.StrategySocialValidator is a validator for the "strategy_social" field. It is called by the builders before save.
	role.StrategySocialValidator = func() func(int) error {
		validators := roleDescStrategySocial.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(strategy_social int) error {
			for _, fn := range fns {
				if err := fn(strategy_social); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescStrategyTrade is the schema descriptor for strategy_trade field.
	roleDescStrategyTrade := roleFields[10].Descriptor()
	// role.DefaultStrategyTrade holds the default value on creation for the strategy_trade field.
	role.DefaultStrategyTrade = roleDescStrategyTrade.Default.(int)
	// role.StrategyTradeValidator is a validator for the "strategy_trade" field. It is called by the builders before save.
	role.StrategyTradeValidator = func() func(int) error {
		validators := roleDescStrategyTrade.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(strategy_trade int) error {
			for _, fn := range fns {
				if err := fn(strategy_trade); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescStrategyResource is the schema descriptor for strategy_resource field.
	roleDescStrategyResource := roleFields[11].Descriptor()
	// role.DefaultStrategyResource holds the default value on creation for the strategy_resource field.
	role.DefaultStrategyResource = roleDescStrategyResource.Default.(int)
	// role.StrategyResourceValidator is a validator for the "strategy_resource" field. It is called by the builders before save.
	role.StrategyResourceValidator = func() func(int) error {
		validators := roleDescStrategyResource.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(strategy_resource int) error {
			for _, fn := range fns {
				if err := fn(strategy_resource); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// roleDescDailySocialCount is the schema descriptor for daily_social_count field.
	roleDescDailySocialCount := roleFields[12].Descriptor()
	// role.DefaultDailySocialCount holds the default value on creation for the daily_social_count field.
	role.DefaultDailySocialCount = roleDescDailySocialCount.Default.(int)
	// role.DailySocialCountValidator is a validator for the "daily_social_count" field. It is called by the builders before save.
	role.DailySocialCountValidator = roleDescDailySocialCount.Validators[0].(func(int) error)
	// roleDescMapID is the schema descriptor for map_id field.
	roleDescMapID := roleFields[15].Descriptor()
	// role.DefaultMapID holds the default value on creation for the map_id field.
	role.DefaultMapID = roleDescMapID.Default.(string)
	// roleDescTileX is the schema descriptor for tile_x field.
	roleDescTileX := roleFields[16].Descriptor()
	// role.DefaultTileX holds the default value on creation for the tile_x field.
	role.DefaultTileX = roleDescTileX.Default.(int)
	// roleDescTileY is the schema descriptor for tile_y field.
	roleDescTileY := roleFields[17].Descriptor()
	// role.DefaultTileY holds the default value on creation for the tile_y field.
	role.DefaultTileY = roleDescTileY.Default.(int)
	// roleDescID is the schema descriptor for id field.
	roleDescID := roleFields[0].Descriptor()
	// role.DefaultID holds the default value on creation for the id field.
	role.DefaultID = roleDescID.Default.(func() uuid.UUID)
	seasonFields := schema.Season{}.Fields()
	_ = seasonFields
	// seasonDescNumber is the schema descriptor for number field.
	seasonDescNumber := seasonFields[1].Descriptor()
	// season.NumberValidator is a validator for the "number" field. It is called by the builders before save.
	season.NumberValidator = seasonDescNumber.Validators[0].(func(int) error)
	// seasonDescName is the schema descriptor for name field.
	seasonDescName := seasonFields[2].Descriptor()
	// season.NameValidator is a validator for the "name" field. It is called by the builders before save.
	season.NameValidator = seasonDescName.Validators[0].(func(string) error)
	// seasonDescStatus is the schema descriptor for status field.
	seasonDescStatus := seasonFields[5].Descriptor()
	// season.DefaultStatus holds the default value on creation for the status field.
	season.DefaultStatus = seasonDescStatus.Default.(string)
	// season.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	season.StatusValidator = seasonDescStatus.Validators[0].(func(string) error)
	// seasonDescTasksConfig is the schema descriptor for tasks_config field.
	seasonDescTasksConfig := seasonFields[6].Descriptor()
	// season.DefaultTasksConfig holds the default value on creation for the tasks_config field.
	season.DefaultTasksConfig = seasonDescTasksConfig.Default.([]interface{})
	// seasonDescRewardsConfig is the schema descriptor for rewards_config field.
	seasonDescRewardsConfig := seasonFields[7].Descriptor()
	// season.DefaultRewardsConfig holds the default value on creation for the rewards_config field.
	season.DefaultRewardsConfig = seasonDescRewardsConfig.Default.(map[string]interface{})
	// seasonDescID is the schema descriptor for id field.
	seasonDescID := seasonFields[0].Descriptor()
	// season.DefaultID holds the default value on creation for the id field.
	season.DefaultID = seasonDescID.Default.(func() uuid.UUID)
	seasonscoreFields := schema.SeasonScore{}.Fields()
	_ = seasonscoreFields
	// seasonscoreDescScoreOutput is the schema descriptor for score_output field.
	seasonscoreDescScoreOutput := seasonscoreFields[3].Descriptor()
	// seasonscore.DefaultScoreOutput holds the default value on creation for the score_output field.
	seasonscore.DefaultScoreOutput = seasonscoreDescScoreOutput.Default.(int64)
	// seasonscore.ScoreOutputValidator is a validator for the "score_output" field. It is called by the builders before save.
	seasonscore.ScoreOutputValidator = seasonscoreDescScoreOutput.Validators[0].(func(int64) error)
	// seasonscoreDescScoreSocial is the schema descriptor for score_social field.
	seasonscoreDescScoreSocial := seasonscoreFields[4].Descriptor()
	// seasonscore.DefaultScoreSocial holds the default value on creation for the score_social field.
	seasonscore.DefaultScoreSocial = seasonscoreDescScoreSocial.Default.(int64)
	// seasonscore.ScoreSocialValidator is a validator for the "score_social" field. It is called by the builders before save.
	seasonscore.ScoreSocialValidator = seasonscoreDescScoreSocial.Validators[0].(func(int64) error)
	// seasonscoreDescScoreCollection is the schema descriptor for score_collection field.
	seasonscoreDescScoreCollection := seasonscoreFields[5].Descriptor()
	// seasonscore.DefaultScoreCollection holds the default value on creation for the score_collection field.
	seasonscore.DefaultScoreCollection = seasonscoreDescScoreCollection.Default.(int64)
	// seasonscore.ScoreCollectionValidator is a validator for the "score_collection" field. It is called by the builders before save.
	seasonscore.ScoreCollectionValidator = seasonscoreDescScoreCollection.Validators[0].(func(int64) error)
	// seasonscoreDescScoreQuality is the schema descriptor for score_quality field.
	seasonscoreDescScoreQuality := seasonscoreFields[6].Descriptor()
	// seasonscore.DefaultScoreQuality holds the default value on creation for the score_quality field.
	seasonscore.DefaultScoreQuality = seasonscoreDescScoreQuality.Default.(int64)
	// seasonscore.ScoreQualityValidator is a validator for the "score_quality" field. It is called by the builders before save.
	seasonscore.ScoreQualityValidator = seasonscoreDescScoreQuality.Validators[0].(func(int64) error)
	// seasonscoreDescScoreTotal is the schema descriptor for score_total field.
	seasonscoreDescScoreTotal := seasonscoreFields[7].Descriptor()
	// seasonscore.DefaultScoreTotal holds the default value on creation for the score_total field.
	seasonscore.DefaultScoreTotal = seasonscoreDescScoreTotal.Default.(int64)
	// seasonscore.ScoreTotalValidator is a validator for the "score_total" field. It is called by the builders before save.
	seasonscore.ScoreTotalValidator = seasonscoreDescScoreTotal.Validators[0].(func(int64) error)
	// seasonscoreDescUpdatedAt is the schema descriptor for updated_at field.
	seasonscoreDescUpdatedAt := seasonscoreFields[9].Descriptor()
	// seasonscore.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	seasonscore.DefaultUpdatedAt = seasonscoreDescUpdatedAt.Default.(func() time.Time)
	// seasonscore.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	seasonscore.UpdateDefaultUpdatedAt = seasonscoreDescUpdatedAt.UpdateDefault.(func() time.Time)
	// seasonscoreDescID is the schema descriptor for id field.
	seasonscoreDescID := seasonscoreFields[0].Descriptor()
	// seasonscore.DefaultID holds the default value on creation for the id field.
	seasonscore.DefaultID = seasonscoreDescID.Default.(func() uuid.UUID)
	seasontaskprogressFields := schema.SeasonTaskProgress{}.Fields()
	_ = seasontaskprogressFields
	// seasontaskprogressDescTaskID is the schema descriptor for task_id field.
	seasontaskprogressDescTaskID := seasontaskprogressFields[3].Descriptor()
	// seasontaskprogress.TaskIDValidator is a validator for the "task_id" field. It is called by the builders before save.
	seasontaskprogress.TaskIDValidator = seasontaskprogressDescTaskID.Validators[0].(func(string) error)
	// seasontaskprogressDescProgress is the schema descriptor for progress field.
	seasontaskprogressDescProgress := seasontaskprogressFields[4].Descriptor()
	// seasontaskprogress.DefaultProgress holds the default value on creation for the progress field.
	seasontaskprogress.DefaultProgress = seasontaskprogressDescProgress.Default.(int64)
	// seasontaskprogress.ProgressValidator is a validator for the "progress" field. It is called by the builders before save.
	seasontaskprogress.ProgressValidator = seasontaskprogressDescProgress.Validators[0].(func(int64) error)
	// seasontaskprogressDescTarget is the schema descriptor for target field.
	seasontaskprogressDescTarget := seasontaskprogressFields[5].Descriptor()
	// seasontaskprogress.TargetValidator is a validator for the "target" field. It is called by the builders before save.
	seasontaskprogress.TargetValidator = seasontaskprogressDescTarget.Validators[0].(func(int64) error)
	// seasontaskprogressDescCompleted is the schema descriptor for completed field.
	seasontaskprogressDescCompleted := seasontaskprogressFields[6].Descriptor()
	// seasontaskprogress.DefaultCompleted holds the default value on creation for the completed field.
	seasontaskprogress.DefaultCompleted = seasontaskprogressDescCompleted.Default.(bool)
	// seasontaskprogressDescClaimed is the schema descriptor for claimed field.
	seasontaskprogressDescClaimed := seasontaskprogressFields[7].Descriptor()
	// seasontaskprogress.DefaultClaimed holds the default value on creation for the claimed field.
	seasontaskprogress.DefaultClaimed = seasontaskprogressDescClaimed.Default.(bool)
	// seasontaskprogressDescID is the schema descriptor for id field.
	seasontaskprogressDescID := seasontaskprogressFields[0].Descriptor()
	// seasontaskprogress.DefaultID holds the default value on creation for the id field.
	seasontaskprogress.DefaultID = seasontaskprogressDescID.Default.(func() uuid.UUID)
	subscriptionFields := schema.Subscription{}.Fields()
	_ = subscriptionFields
	// subscriptionDescPlanID is the schema descriptor for plan_id field.
	subscriptionDescPlanID := subscriptionFields[2].Descriptor()
	// subscription.PlanIDValidator is a validator for the "plan_id" field. It is called by the builders before save.
	subscription.PlanIDValidator = subscriptionDescPlanID.Validators[0].(func(string) error)
	// subscriptionDescStatus is the schema descriptor for status field.
	subscriptionDescStatus := subscriptionFields[5].Descriptor()
	// subscription.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	subscription.StatusValidator = subscriptionDescStatus.Validators[0].(func(string) error)
	// subscriptionDescAutoRenew is the schema descriptor for auto_renew field.
	subscriptionDescAutoRenew := subscriptionFields[6].Descriptor()
	// subscription.DefaultAutoRenew holds the default value on creation for the auto_renew field.
	subscription.DefaultAutoRenew = subscriptionDescAutoRenew.Default.(bool)
	// subscriptionDescUpdatedAt is the schema descriptor for updated_at field.
	subscriptionDescUpdatedAt := subscriptionFields[7].Descriptor()
	// subscription.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	subscription.DefaultUpdatedAt = subscriptionDescUpdatedAt.Default.(func() time.Time)
	// subscription.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	subscription.UpdateDefaultUpdatedAt = subscriptionDescUpdatedAt.UpdateDefault.(func() time.Time)
	// subscriptionDescID is the schema descriptor for id field.
	subscriptionDescID := subscriptionFields[0].Descriptor()
	// subscription.DefaultID holds the default value on creation for the id field.
	subscription.DefaultID = subscriptionDescID.Default.(func() uuid.UUID)
	tradeorderFields := schema.TradeOrder{}.Fields()
	_ = tradeorderFields
	// tradeorderDescScope is the schema descriptor for scope field.
	tradeorderDescScope := tradeorderFields[3].Descriptor()
	// tradeorder.ScopeValidator is a validator for the "scope" field. It is called by the builders before save.
	tradeorder.ScopeValidator = tradeorderDescScope.Validators[0].(func(string) error)
	// tradeorderDescItemID is the schema descriptor for item_id field.
	tradeorderDescItemID := tradeorderFields[4].Descriptor()
	// tradeorder.ItemIDValidator is a validator for the "item_id" field. It is called by the builders before save.
	tradeorder.ItemIDValidator = tradeorderDescItemID.Validators[0].(func(string) error)
	// tradeorderDescItemType is the schema descriptor for item_type field.
	tradeorderDescItemType := tradeorderFields[5].Descriptor()
	// tradeorder.ItemTypeValidator is a validator for the "item_type" field. It is called by the builders before save.
	tradeorder.ItemTypeValidator = tradeorderDescItemType.Validators[0].(func(string) error)
	// tradeorderDescQuality is the schema descriptor for quality field.
	tradeorderDescQuality := tradeorderFields[6].Descriptor()
	// tradeorder.QualityValidator is a validator for the "quality" field. It is called by the builders before save.
	tradeorder.QualityValidator = tradeorderDescQuality.Validators[0].(func(string) error)
	// tradeorderDescQuantity is the schema descriptor for quantity field.
	tradeorderDescQuantity := tradeorderFields[7].Descriptor()
	// tradeorder.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	tradeorder.QuantityValidator = tradeorderDescQuantity.Validators[0].(func(int64) error)
	// tradeorderDescQuantityLeft is the schema descriptor for quantity_left field.
	tradeorderDescQuantityLeft := tradeorderFields[8].Descriptor()
	// tradeorder.QuantityLeftValidator is a validator for the "quantity_left" field. It is called by the builders before save.
	tradeorder.QuantityLeftValidator = tradeorderDescQuantityLeft.Validators[0].(func(int64) error)
	// tradeorderDescPriceEach is the schema descriptor for price_each field.
	tradeorderDescPriceEach := tradeorderFields[9].Descriptor()
	// tradeorder.PriceEachValidator is a validator for the "price_each" field. It is called by the builders before save.
	tradeorder.PriceEachValidator = tradeorderDescPriceEach.Validators[0].(func(int64) error)
	// tradeorderDescFeeRate is the schema descriptor for fee_rate field.
	tradeorderDescFeeRate := tradeorderFields[10].Descriptor()
	// tradeorder.DefaultFeeRate holds the default value on creation for the fee_rate field.
	tradeorder.DefaultFeeRate = tradeorderDescFeeRate.Default.(float32)
	// tradeorderDescStatus is the schema descriptor for status field.
	tradeorderDescStatus := tradeorderFields[11].Descriptor()
	// tradeorder.DefaultStatus holds the default value on creation for the status field.
	tradeorder.DefaultStatus = tradeorderDescStatus.Default.(string)
	// tradeorder.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	tradeorder.StatusValidator = tradeorderDescStatus.Validators[0].(func(string) error)
	// tradeorderDescListedAt is the schema descriptor for listed_at field.
	tradeorderDescListedAt := tradeorderFields[12].Descriptor()
	// tradeorder.DefaultListedAt holds the default value on creation for the listed_at field.
	tradeorder.DefaultListedAt = tradeorderDescListedAt.Default.(func() time.Time)
	// tradeorderDescID is the schema descriptor for id field.
	tradeorderDescID := tradeorderFields[0].Descriptor()
	// tradeorder.DefaultID holds the default value on creation for the id field.
	tradeorder.DefaultID = tradeorderDescID.Default.(func() uuid.UUID)
	tradetransactionFields := schema.TradeTransaction{}.Fields()
	_ = tradetransactionFields
	// tradetransactionDescItemID is the schema descriptor for item_id field.
	tradetransactionDescItemID := tradetransactionFields[4].Descriptor()
	// tradetransaction.ItemIDValidator is a validator for the "item_id" field. It is called by the builders before save.
	tradetransaction.ItemIDValidator = tradetransactionDescItemID.Validators[0].(func(string) error)
	// tradetransactionDescQuantity is the schema descriptor for quantity field.
	tradetransactionDescQuantity := tradetransactionFields[5].Descriptor()
	// tradetransaction.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	tradetransaction.QuantityValidator = tradetransactionDescQuantity.Validators[0].(func(int64) error)
	// tradetransactionDescPriceEach is the schema descriptor for price_each field.
	tradetransactionDescPriceEach := tradetransactionFields[6].Descriptor()
	// tradetransaction.PriceEachValidator is a validator for the "price_each" field. It is called by the builders before save.
	tradetransaction.PriceEachValidator = tradetransactionDescPriceEach.Validators[0].(func(int64) error)
	// tradetransactionDescFee is the schema descriptor for fee field.
	tradetransactionDescFee := tradetransactionFields[7].Descriptor()
	// tradetransaction.DefaultFee holds the default value on creation for the fee field.
	tradetransaction.DefaultFee = tradetransactionDescFee.Default.(int64)
	// tradetransaction.FeeValidator is a validator for the "fee" field. It is called by the builders before save.
	tradetransaction.FeeValidator = tradetransactionDescFee.Validators[0].(func(int64) error)
	// tradetransactionDescCreatedAt is the schema descriptor for created_at field.
	tradetransactionDescCreatedAt := tradetransactionFields[8].Descriptor()
	// tradetransaction.DefaultCreatedAt holds the default value on creation for the created_at field.
	tradetransaction.DefaultCreatedAt = tradetransactionDescCreatedAt.Default.(func() time.Time)
	// tradetransactionDescID is the schema descriptor for id field.
	tradetransactionDescID := tradetransactionFields[0].Descriptor()
	// tradetransaction.DefaultID holds the default value on creation for the id field.
	tradetransaction.DefaultID = tradetransactionDescID.Default.(func() uuid.UUID)
	tutorialprogressFields := schema.TutorialProgress{}.Fields()
	_ = tutorialprogressFields
	// tutorialprogressDescStep is the schema descriptor for step field.
	tutorialprogressDescStep := tutorialprogressFields[2].Descriptor()
	// tutorialprogress.StepValidator is a validator for the "step" field. It is called by the builders before save.
	tutorialprogress.StepValidator = tutorialprogressDescStep.Validators[0].(func(string) error)
	// tutorialprogressDescCompletedAt is the schema descriptor for completed_at field.
	tutorialprogressDescCompletedAt := tutorialprogressFields[3].Descriptor()
	// tutorialprogress.DefaultCompletedAt holds the default value on creation for the completed_at field.
	tutorialprogress.DefaultCompletedAt = tutorialprogressDescCompletedAt.Default.(func() time.Time)
	// tutorialprogressDescID is the schema descriptor for id field.
	tutorialprogressDescID := tutorialprogressFields[0].Descriptor()
	// tutorialprogress.DefaultID holds the default value on creation for the id field.
	tutorialprogress.DefaultID = tutorialprogressDescID.Default.(func() uuid.UUID)
	userMixin := schema.User{}.Mixin()
	userMixinFields0 := userMixin[0].Fields()
	_ = userMixinFields0
	userFields := schema.User{}.Fields()
	_ = userFields
	// userDescCreatedAt is the schema descriptor for created_at field.
	userDescCreatedAt := userMixinFields0[0].Descriptor()
	// user.DefaultCreatedAt holds the default value on creation for the created_at field.
	user.DefaultCreatedAt = userDescCreatedAt.Default.(func() time.Time)
	// userDescUpdatedAt is the schema descriptor for updated_at field.
	userDescUpdatedAt := userMixinFields0[1].Descriptor()
	// user.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	user.DefaultUpdatedAt = userDescUpdatedAt.Default.(func() time.Time)
	// user.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	user.UpdateDefaultUpdatedAt = userDescUpdatedAt.UpdateDefault.(func() time.Time)
	// userDescOpenid is the schema descriptor for openid field.
	userDescOpenid := userFields[1].Descriptor()
	// user.OpenidValidator is a validator for the "openid" field. It is called by the builders before save.
	user.OpenidValidator = userDescOpenid.Validators[0].(func(string) error)
	// userDescPhone is the schema descriptor for phone field.
	userDescPhone := userFields[2].Descriptor()
	// user.PhoneValidator is a validator for the "phone" field. It is called by the builders before save.
	user.PhoneValidator = userDescPhone.Validators[0].(func(string) error)
	// userDescPasswordHash is the schema descriptor for password_hash field.
	userDescPasswordHash := userFields[3].Descriptor()
	// user.PasswordHashValidator is a validator for the "password_hash" field. It is called by the builders before save.
	user.PasswordHashValidator = userDescPasswordHash.Validators[0].(func(string) error)
	// userDescNickname is the schema descriptor for nickname field.
	userDescNickname := userFields[4].Descriptor()
	// user.NicknameValidator is a validator for the "nickname" field. It is called by the builders before save.
	user.NicknameValidator = func() func(string) error {
		validators := userDescNickname.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(nickname string) error {
			for _, fn := range fns {
				if err := fn(nickname); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// userDescLevel is the schema descriptor for level field.
	userDescLevel := userFields[6].Descriptor()
	// user.DefaultLevel holds the default value on creation for the level field.
	user.DefaultLevel = userDescLevel.Default.(int)
	// user.LevelValidator is a validator for the "level" field. It is called by the builders before save.
	user.LevelValidator = userDescLevel.Validators[0].(func(int) error)
	// userDescExp is the schema descriptor for exp field.
	userDescExp := userFields[7].Descriptor()
	// user.DefaultExp holds the default value on creation for the exp field.
	user.DefaultExp = userDescExp.Default.(int64)
	// user.ExpValidator is a validator for the "exp" field. It is called by the builders before save.
	user.ExpValidator = userDescExp.Validators[0].(func(int64) error)
	// userDescCoins is the schema descriptor for coins field.
	userDescCoins := userFields[8].Descriptor()
	// user.DefaultCoins holds the default value on creation for the coins field.
	user.DefaultCoins = userDescCoins.Default.(int64)
	// user.CoinsValidator is a validator for the "coins" field. It is called by the builders before save.
	user.CoinsValidator = userDescCoins.Validators[0].(func(int64) error)
	// userDescDiamonds is the schema descriptor for diamonds field.
	userDescDiamonds := userFields[9].Descriptor()
	// user.DefaultDiamonds holds the default value on creation for the diamonds field.
	user.DefaultDiamonds = userDescDiamonds.Default.(int)
	// user.DiamondsValidator is a validator for the "diamonds" field. It is called by the builders before save.
	user.DiamondsValidator = userDescDiamonds.Validators[0].(func(int) error)
	// userDescStamina is the schema descriptor for stamina field.
	userDescStamina := userFields[10].Descriptor()
	// user.DefaultStamina holds the default value on creation for the stamina field.
	user.DefaultStamina = userDescStamina.Default.(int)
	// user.StaminaValidator is a validator for the "stamina" field. It is called by the builders before save.
	user.StaminaValidator = userDescStamina.Validators[0].(func(int) error)
	// userDescMaxStamina is the schema descriptor for max_stamina field.
	userDescMaxStamina := userFields[11].Descriptor()
	// user.DefaultMaxStamina holds the default value on creation for the max_stamina field.
	user.DefaultMaxStamina = userDescMaxStamina.Default.(int)
	// user.MaxStaminaValidator is a validator for the "max_stamina" field. It is called by the builders before save.
	user.MaxStaminaValidator = userDescMaxStamina.Validators[0].(func(int) error)
	// userDescStaminaUpdatedAt is the schema descriptor for stamina_updated_at field.
	userDescStaminaUpdatedAt := userFields[12].Descriptor()
	// user.DefaultStaminaUpdatedAt holds the default value on creation for the stamina_updated_at field.
	user.DefaultStaminaUpdatedAt = userDescStaminaUpdatedAt.Default.(func() time.Time)
	// userDescFriendshipPoints is the schema descriptor for friendship_points field.
	userDescFriendshipPoints := userFields[13].Descriptor()
	// user.DefaultFriendshipPoints holds the default value on creation for the friendship_points field.
	user.DefaultFriendshipPoints = userDescFriendshipPoints.Default.(int)
	// user.FriendshipPointsValidator is a validator for the "friendship_points" field. It is called by the builders before save.
	user.FriendshipPointsValidator = userDescFriendshipPoints.Validators[0].(func(int) error)
	// userDescIsFirstCharge is the schema descriptor for is_first_charge field.
	userDescIsFirstCharge := userFields[14].Descriptor()
	// user.DefaultIsFirstCharge holds the default value on creation for the is_first_charge field.
	user.DefaultIsFirstCharge = userDescIsFirstCharge.Default.(bool)
	// userDescID is the schema descriptor for id field.
	userDescID := userFields[0].Descriptor()
	// user.DefaultID holds the default value on creation for the id field.
	user.DefaultID = userDescID.Default.(func() uuid.UUID)
	villageMixin := schema.Village{}.Mixin()
	villageMixinFields0 := villageMixin[0].Fields()
	_ = villageMixinFields0
	villageFields := schema.Village{}.Fields()
	_ = villageFields
	// villageDescCreatedAt is the schema descriptor for created_at field.
	villageDescCreatedAt := villageMixinFields0[0].Descriptor()
	// village.DefaultCreatedAt holds the default value on creation for the created_at field.
	village.DefaultCreatedAt = villageDescCreatedAt.Default.(func() time.Time)
	// villageDescUpdatedAt is the schema descriptor for updated_at field.
	villageDescUpdatedAt := villageMixinFields0[1].Descriptor()
	// village.DefaultUpdatedAt holds the default value on creation for the updated_at field.
	village.DefaultUpdatedAt = villageDescUpdatedAt.Default.(func() time.Time)
	// village.UpdateDefaultUpdatedAt holds the default value on update for the updated_at field.
	village.UpdateDefaultUpdatedAt = villageDescUpdatedAt.UpdateDefault.(func() time.Time)
	// villageDescName is the schema descriptor for name field.
	villageDescName := villageFields[1].Descriptor()
	// village.NameValidator is a validator for the "name" field. It is called by the builders before save.
	village.NameValidator = func() func(string) error {
		validators := villageDescName.Validators
		fns := [...]func(string) error{
			validators[0].(func(string) error),
			validators[1].(func(string) error),
		}
		return func(name string) error {
			for _, fn := range fns {
				if err := fn(name); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// villageDescLevel is the schema descriptor for level field.
	villageDescLevel := villageFields[2].Descriptor()
	// village.DefaultLevel holds the default value on creation for the level field.
	village.DefaultLevel = villageDescLevel.Default.(int)
	// village.LevelValidator is a validator for the "level" field. It is called by the builders before save.
	village.LevelValidator = func() func(int) error {
		validators := villageDescLevel.Validators
		fns := [...]func(int) error{
			validators[0].(func(int) error),
			validators[1].(func(int) error),
		}
		return func(level int) error {
			for _, fn := range fns {
				if err := fn(level); err != nil {
					return err
				}
			}
			return nil
		}
	}()
	// villageDescContribution is the schema descriptor for contribution field.
	villageDescContribution := villageFields[3].Descriptor()
	// village.DefaultContribution holds the default value on creation for the contribution field.
	village.DefaultContribution = villageDescContribution.Default.(int64)
	// village.ContributionValidator is a validator for the "contribution" field. It is called by the builders before save.
	village.ContributionValidator = villageDescContribution.Validators[0].(func(int64) error)
	// villageDescMemberCount is the schema descriptor for member_count field.
	villageDescMemberCount := villageFields[4].Descriptor()
	// village.DefaultMemberCount holds the default value on creation for the member_count field.
	village.DefaultMemberCount = villageDescMemberCount.Default.(int)
	// village.MemberCountValidator is a validator for the "member_count" field. It is called by the builders before save.
	village.MemberCountValidator = villageDescMemberCount.Validators[0].(func(int) error)
	// villageDescMaxMembers is the schema descriptor for max_members field.
	villageDescMaxMembers := villageFields[5].Descriptor()
	// village.DefaultMaxMembers holds the default value on creation for the max_members field.
	village.DefaultMaxMembers = villageDescMaxMembers.Default.(int)
	// villageDescSpecialty is the schema descriptor for specialty field.
	villageDescSpecialty := villageFields[6].Descriptor()
	// village.DefaultSpecialty holds the default value on creation for the specialty field.
	village.DefaultSpecialty = villageDescSpecialty.Default.([]string)
	// villageDescID is the schema descriptor for id field.
	villageDescID := villageFields[0].Descriptor()
	// village.DefaultID holds the default value on creation for the id field.
	village.DefaultID = villageDescID.Default.(func() uuid.UUID)
	villagememberFields := schema.VillageMember{}.Fields()
	_ = villagememberFields
	// villagememberDescRole is the schema descriptor for role field.
	villagememberDescRole := villagememberFields[3].Descriptor()
	// villagemember.DefaultRole holds the default value on creation for the role field.
	villagemember.DefaultRole = villagememberDescRole.Default.(string)
	// villagemember.RoleValidator is a validator for the "role" field. It is called by the builders before save.
	villagemember.RoleValidator = villagememberDescRole.Validators[0].(func(string) error)
	// villagememberDescContribution is the schema descriptor for contribution field.
	villagememberDescContribution := villagememberFields[4].Descriptor()
	// villagemember.DefaultContribution holds the default value on creation for the contribution field.
	villagemember.DefaultContribution = villagememberDescContribution.Default.(int64)
	// villagemember.ContributionValidator is a validator for the "contribution" field. It is called by the builders before save.
	villagemember.ContributionValidator = villagememberDescContribution.Validators[0].(func(int64) error)
	// villagememberDescJoinedAt is the schema descriptor for joined_at field.
	villagememberDescJoinedAt := villagememberFields[5].Descriptor()
	// villagemember.DefaultJoinedAt holds the default value on creation for the joined_at field.
	villagemember.DefaultJoinedAt = villagememberDescJoinedAt.Default.(func() time.Time)
	// villagememberDescID is the schema descriptor for id field.
	villagememberDescID := villagememberFields[0].Descriptor()
	// villagemember.DefaultID holds the default value on creation for the id field.
	villagemember.DefaultID = villagememberDescID.Default.(func() uuid.UUID)
	villageprojectFields := schema.VillageProject{}.Fields()
	_ = villageprojectFields
	// villageprojectDescType is the schema descriptor for type field.
	villageprojectDescType := villageprojectFields[2].Descriptor()
	// villageproject.TypeValidator is a validator for the "type" field. It is called by the builders before save.
	villageproject.TypeValidator = villageprojectDescType.Validators[0].(func(string) error)
	// villageprojectDescName is the schema descriptor for name field.
	villageprojectDescName := villageprojectFields[3].Descriptor()
	// villageproject.NameValidator is a validator for the "name" field. It is called by the builders before save.
	villageproject.NameValidator = villageprojectDescName.Validators[0].(func(string) error)
	// villageprojectDescStatus is the schema descriptor for status field.
	villageprojectDescStatus := villageprojectFields[5].Descriptor()
	// villageproject.DefaultStatus holds the default value on creation for the status field.
	villageproject.DefaultStatus = villageprojectDescStatus.Default.(string)
	// villageproject.StatusValidator is a validator for the "status" field. It is called by the builders before save.
	villageproject.StatusValidator = villageprojectDescStatus.Validators[0].(func(string) error)
	// villageprojectDescStartedAt is the schema descriptor for started_at field.
	villageprojectDescStartedAt := villageprojectFields[6].Descriptor()
	// villageproject.DefaultStartedAt holds the default value on creation for the started_at field.
	villageproject.DefaultStartedAt = villageprojectDescStartedAt.Default.(func() time.Time)
	// villageprojectDescID is the schema descriptor for id field.
	villageprojectDescID := villageprojectFields[0].Descriptor()
	// villageproject.DefaultID holds the default value on creation for the id field.
	villageproject.DefaultID = villageprojectDescID.Default.(func() uuid.UUID)
	villageprojectcontributionFields := schema.VillageProjectContribution{}.Fields()
	_ = villageprojectcontributionFields
	// villageprojectcontributionDescResourceType is the schema descriptor for resource_type field.
	villageprojectcontributionDescResourceType := villageprojectcontributionFields[3].Descriptor()
	// villageprojectcontribution.ResourceTypeValidator is a validator for the "resource_type" field. It is called by the builders before save.
	villageprojectcontribution.ResourceTypeValidator = villageprojectcontributionDescResourceType.Validators[0].(func(string) error)
	// villageprojectcontributionDescItemID is the schema descriptor for item_id field.
	villageprojectcontributionDescItemID := villageprojectcontributionFields[4].Descriptor()
	// villageprojectcontribution.ItemIDValidator is a validator for the "item_id" field. It is called by the builders before save.
	villageprojectcontribution.ItemIDValidator = villageprojectcontributionDescItemID.Validators[0].(func(string) error)
	// villageprojectcontributionDescQuantity is the schema descriptor for quantity field.
	villageprojectcontributionDescQuantity := villageprojectcontributionFields[5].Descriptor()
	// villageprojectcontribution.QuantityValidator is a validator for the "quantity" field. It is called by the builders before save.
	villageprojectcontribution.QuantityValidator = villageprojectcontributionDescQuantity.Validators[0].(func(int64) error)
	// villageprojectcontributionDescCreatedAt is the schema descriptor for created_at field.
	villageprojectcontributionDescCreatedAt := villageprojectcontributionFields[6].Descriptor()
	// villageprojectcontribution.DefaultCreatedAt holds the default value on creation for the created_at field.
	villageprojectcontribution.DefaultCreatedAt = villageprojectcontributionDescCreatedAt.Default.(func() time.Time)
	// villageprojectcontributionDescID is the schema descriptor for id field.
	villageprojectcontributionDescID := villageprojectcontributionFields[0].Descriptor()
	// villageprojectcontribution.DefaultID holds the default value on creation for the id field.
	villageprojectcontribution.DefaultID = villageprojectcontributionDescID.Default.(func() uuid.UUID)
}
