// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/season"
	"github.com/liukai/farmer/server/ent/seasontaskprogress"
	"github.com/liukai/farmer/server/ent/user"
)

// SeasonTaskProgressCreate is the builder for creating a SeasonTaskProgress entity.
type SeasonTaskProgressCreate struct {
	config
	mutation *SeasonTaskProgressMutation
	hooks    []Hook
}

// SetSeasonID sets the "season_id" field.
func (_c *SeasonTaskProgressCreate) SetSeasonID(v uuid.UUID) *SeasonTaskProgressCreate {
	_c.mutation.SetSeasonID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *SeasonTaskProgressCreate) SetUserID(v uuid.UUID) *SeasonTaskProgressCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetTaskID sets the "task_id" field.
func (_c *SeasonTaskProgressCreate) SetTaskID(v string) *SeasonTaskProgressCreate {
	_c.mutation.SetTaskID(v)
	return _c
}

// SetProgress sets the "progress" field.
func (_c *SeasonTaskProgressCreate) SetProgress(v int64) *SeasonTaskProgressCreate {
	_c.mutation.SetProgress(v)
	return _c
}

// SetNillableProgress sets the "progress" field if the given value is not nil.
func (_c *SeasonTaskProgressCreate) SetNillableProgress(v *int64) *SeasonTaskProgressCreate {
	if v != nil {
		_c.SetProgress(*v)
	}
	return _c
}

// SetTarget sets the "target" field.
func (_c *SeasonTaskProgressCreate) SetTarget(v int64) *SeasonTaskProgressCreate {
	_c.mutation.SetTarget(v)
	return _c
}

// SetCompleted sets the "completed" field.
func (_c *SeasonTaskProgressCreate) SetCompleted(v bool) *SeasonTaskProgressCreate {
	_c.mutation.SetCompleted(v)
	return _c
}

// SetNillableCompleted sets the "completed" field if the given value is not nil.
func (_c *SeasonTaskProgressCreate) SetNillableCompleted(v *bool) *SeasonTaskProgressCreate {
	if v != nil {
		_c.SetCompleted(*v)
	}
	return _c
}

// SetClaimed sets the "claimed" field.
func (_c *SeasonTaskProgressCreate) SetClaimed(v bool) *SeasonTaskProgressCreate {
	_c.mutation.SetClaimed(v)
	return _c
}

// SetNillableClaimed sets the "claimed" field if the given value is not nil.
func (_c *SeasonTaskProgressCreate) SetNillableClaimed(v *bool) *SeasonTaskProgressCreate {
	if v != nil {
		_c.SetClaimed(*v)
	}
	return _c
}

// SetCompletedAt sets the "completed_at" field.
func (_c *SeasonTaskProgressCreate) SetCompletedAt(v time.Time) *SeasonTaskProgressCreate {
	_c.mutation.SetCompletedAt(v)
	return _c
}

// SetNillableCompletedAt sets the "completed_at" field if the given value is not nil.
func (_c *SeasonTaskProgressCreate) SetNillableCompletedAt(v *time.Time) *SeasonTaskProgressCreate {
	if v != nil {
		_c.SetCompletedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *SeasonTaskProgressCreate) SetID(v uuid.UUID) *SeasonTaskProgressCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *SeasonTaskProgressCreate) SetNillableID(v *uuid.UUID) *SeasonTaskProgressCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetSeason sets the "season" edge to the Season entity.
func (_c *SeasonTaskProgressCreate) SetSeason(v *Season) *SeasonTaskProgressCreate {
	return _c.SetSeasonID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *SeasonTaskProgressCreate) SetUser(v *User) *SeasonTaskProgressCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the SeasonTaskProgressMutation object of the builder.
func (_c *SeasonTaskProgressCreate) Mutation() *SeasonTaskProgressMutation {
	return _c.mutation
}

// Save creates the SeasonTaskProgress in the database.
func (_c *SeasonTaskProgressCreate) Save(ctx context.Context) (*SeasonTaskProgress, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SeasonTaskProgressCreate) SaveX(ctx context.Context) *SeasonTaskProgress {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SeasonTaskProgressCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SeasonTaskProgressCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SeasonTaskProgressCreate) defaults() {
	if _, ok := _c.mutation.Progress(); !ok {
		v := seasontaskprogress.DefaultProgress
		_c.mutation.SetProgress(v)
	}
	if _, ok := _c.mutation.Completed(); !ok {
		v := seasontaskprogress.DefaultCompleted
		_c.mutation.SetCompleted(v)
	}
	if _, ok := _c.mutation.Claimed(); !ok {
		v := seasontaskprogress.DefaultClaimed
		_c.mutation.SetClaimed(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := seasontaskprogress.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SeasonTaskProgressCreate) check() error {
	if _, ok := _c.mutation.SeasonID(); !ok {
		return &ValidationError{Name: "season_id", err: errors.New(`ent: missing required field "SeasonTaskProgress.season_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SeasonTaskProgress.user_id"`)}
	}
	if _, ok := _c.mutation.TaskID(); !ok {
		return &ValidationError{Name: "task_id", err: errors.New(`ent: missing required field "SeasonTaskProgress.task_id"`)}
	}
	if v, ok := _c.mutation.TaskID(); ok {
		if err := seasontaskprogress.TaskIDValidator(v); err != nil {
			return &ValidationError{Name: "task_id", err: fmt.Errorf(`ent: validator failed for field "SeasonTaskProgress.task_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Progress(); !ok {
		return &ValidationError{Name: "progress", err: errors.New(`ent: missing required field "SeasonTaskProgress.progress"`)}
	}
	if v, ok := _c.mutation.Progress(); ok {
		if err := seasontaskprogress.ProgressValidator(v); err != nil {
			return &ValidationError{Name: "progress", err: fmt.Errorf(`ent: validator failed for field "SeasonTaskProgress.progress": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Target(); !ok {
		return &ValidationError{Name: "target", err: errors.New(`ent: missing required field "SeasonTaskProgress.target"`)}
	}
	if v, ok := _c.mutation.Target(); ok {
		if err := seasontaskprogress.TargetValidator(v); err != nil {
			return &ValidationError{Name: "target", err: fmt.Errorf(`ent: validator failed for field "SeasonTaskProgress.target": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Completed(); !ok {
		return &ValidationError{Name: "completed", err: errors.New(`ent: missing required field "SeasonTaskProgress.completed"`)}
	}
	if _, ok := _c.mutation.Claimed(); !ok {
		return &ValidationError{Name: "claimed", err: errors.New(`ent: missing required field "SeasonTaskProgress.claimed"`)}
	}
	if len(_c.mutation.SeasonIDs()) == 0 {
		return &ValidationError{Name: "season", err: errors.New(`ent: missing required edge "SeasonTaskProgress.season"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SeasonTaskProgress.user"`)}
	}
	return nil
}

func (_c *SeasonTaskProgressCreate) sqlSave(ctx context.Context) (*SeasonTaskProgress, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SeasonTaskProgressCreate) createSpec() (*SeasonTaskProgress, *sqlgraph.CreateSpec) {
	var (
		_node = &SeasonTaskProgress{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(seasontaskprogress.Table, sqlgraph.NewFieldSpec(seasontaskprogress.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.TaskID(); ok {
		_spec.SetField(seasontaskprogress.FieldTaskID, field.TypeString, value)
		_node.TaskID = value
	}
	if value, ok := _c.mutation.Progress(); ok {
		_spec.SetField(seasontaskprogress.FieldProgress, field.TypeInt64, value)
		_node.Progress = value
	}
	if value, ok := _c.mutation.Target(); ok {
		_spec.SetField(seasontaskprogress.FieldTarget, field.TypeInt64, value)
		_node.Target = value
	}
	if value, ok := _c.mutation.Completed(); ok {
		_spec.SetField(seasontaskprogress.FieldCompleted, field.TypeBool, value)
		_node.Completed = value
	}
	if value, ok := _c.mutation.Claimed(); ok {
		_spec.SetField(seasontaskprogress.FieldClaimed, field.TypeBool, value)
		_node.Claimed = value
	}
	if value, ok := _c.mutation.CompletedAt(); ok {
		_spec.SetField(seasontaskprogress.FieldCompletedAt, field.TypeTime, value)
		_node.CompletedAt = &value
	}
	if nodes := _c.mutation.SeasonIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   seasontaskprogress.SeasonTable,
			Columns: []string{seasontaskprogress.SeasonColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(season.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.SeasonID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   seasontaskprogress.UserTable,
			Columns: []string{seasontaskprogress.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// SeasonTaskProgressCreateBulk is the builder for creating many SeasonTaskProgress entities in bulk.
type SeasonTaskProgressCreateBulk struct {
	config
	err      error
	builders []*SeasonTaskProgressCreate
}

// Save creates the SeasonTaskProgress entities in the database.
func (_c *SeasonTaskProgressCreateBulk) Save(ctx context.Context) ([]*SeasonTaskProgress, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SeasonTaskProgress, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SeasonTaskProgressMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SeasonTaskProgressCreateBulk) SaveX(ctx context.Context) []*SeasonTaskProgress {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SeasonTaskProgressCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SeasonTaskProgressCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
