// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/tradeorder"
	"github.com/liukai/farmer/server/ent/user"
)

// TradeOrder is the model entity for the TradeOrder schema.
type TradeOrder struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// SellerID holds the value of the "seller_id" field.
	SellerID uuid.UUID `json:"seller_id,omitempty"`
	// 村内交易=本村；跨村=null
	VillageID *uuid.UUID `json:"village_id,omitempty"`
	// village/cross_village
	Scope string `json:"scope,omitempty"`
	// ItemID holds the value of the "item_id" field.
	ItemID string `json:"item_id,omitempty"`
	// ItemType holds the value of the "item_type" field.
	ItemType string `json:"item_type,omitempty"`
	// normal/good/excellent
	Quality *string `json:"quality,omitempty"`
	// 总上架数
	Quantity int64 `json:"quantity,omitempty"`
	// 剩余数量
	QuantityLeft int64 `json:"quantity_left,omitempty"`
	// 单价（金币）
	PriceEach int64 `json:"price_each,omitempty"`
	// 手续费率（0 或 0.05）
	FeeRate float32 `json:"fee_rate,omitempty"`
	// active/sold/expired/cancelled
	Status string `json:"status,omitempty"`
	// ListedAt holds the value of the "listed_at" field.
	ListedAt time.Time `json:"listed_at,omitempty"`
	// 默认 7 天后
	ExpiresAt time.Time `json:"expires_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the TradeOrderQuery when eager-loading is set.
	Edges        TradeOrderEdges `json:"edges"`
	selectValues sql.SelectValues
}

// TradeOrderEdges holds the relations/edges for other nodes in the graph.
type TradeOrderEdges struct {
	// Seller holds the value of the seller edge.
	Seller *User `json:"seller,omitempty"`
	// Transactions holds the value of the transactions edge.
	Transactions []*TradeTransaction `json:"transactions,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// SellerOrErr returns the Seller value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e TradeOrderEdges) SellerOrErr() (*User, error) {
	if e.Seller != nil {
		return e.Seller, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "seller"}
}

// TransactionsOrErr returns the Transactions value or an error if the edge
// was not loaded in eager-loading.
func (e TradeOrderEdges) TransactionsOrErr() ([]*TradeTransaction, error) {
	if e.loadedTypes[1] {
		return e.Transactions, nil
	}
	return nil, &NotLoadedError{edge: "transactions"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*TradeOrder) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case tradeorder.FieldVillageID:
			values[i] = &sql.NullScanner{S: new(uuid.UUID)}
		case tradeorder.FieldFeeRate:
			values[i] = new(sql.NullFloat64)
		case tradeorder.FieldQuantity, tradeorder.FieldQuantityLeft, tradeorder.FieldPriceEach:
			values[i] = new(sql.NullInt64)
		case tradeorder.FieldScope, tradeorder.FieldItemID, tradeorder.FieldItemType, tradeorder.FieldQuality, tradeorder.FieldStatus:
			values[i] = new(sql.NullString)
		case tradeorder.FieldListedAt, tradeorder.FieldExpiresAt:
			values[i] = new(sql.NullTime)
		case tradeorder.FieldID, tradeorder.FieldSellerID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the TradeOrder fields.
func (_m *TradeOrder) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case tradeorder.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case tradeorder.FieldSellerID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field seller_id", values[i])
			} else if value != nil {
				_m.SellerID = *value
			}
		case tradeorder.FieldVillageID:
			if value, ok := values[i].(*sql.NullScanner); !ok {
				return fmt.Errorf("unexpected type %T for field village_id", values[i])
			} else if value.Valid {
				_m.VillageID = new(uuid.UUID)
				*_m.VillageID = *value.S.(*uuid.UUID)
			}
		case tradeorder.FieldScope:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field scope", values[i])
			} else if value.Valid {
				_m.Scope = value.String
			}
		case tradeorder.FieldItemID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field item_id", values[i])
			} else if value.Valid {
				_m.ItemID = value.String
			}
		case tradeorder.FieldItemType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field item_type", values[i])
			} else if value.Valid {
				_m.ItemType = value.String
			}
		case tradeorder.FieldQuality:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field quality", values[i])
			} else if value.Valid {
				_m.Quality = new(string)
				*_m.Quality = value.String
			}
		case tradeorder.FieldQuantity:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity", values[i])
			} else if value.Valid {
				_m.Quantity = value.Int64
			}
		case tradeorder.FieldQuantityLeft:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field quantity_left", values[i])
			} else if value.Valid {
				_m.QuantityLeft = value.Int64
			}
		case tradeorder.FieldPriceEach:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field price_each", values[i])
			} else if value.Valid {
				_m.PriceEach = value.Int64
			}
		case tradeorder.FieldFeeRate:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field fee_rate", values[i])
			} else if value.Valid {
				_m.FeeRate = float32(value.Float64)
			}
		case tradeorder.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case tradeorder.FieldListedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field listed_at", values[i])
			} else if value.Valid {
				_m.ListedAt = value.Time
			}
		case tradeorder.FieldExpiresAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field expires_at", values[i])
			} else if value.Valid {
				_m.ExpiresAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the TradeOrder.
// This includes values selected through modifiers, order, etc.
func (_m *TradeOrder) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QuerySeller queries the "seller" edge of the TradeOrder entity.
func (_m *TradeOrder) QuerySeller() *UserQuery {
	return NewTradeOrderClient(_m.config).QuerySeller(_m)
}

// QueryTransactions queries the "transactions" edge of the TradeOrder entity.
func (_m *TradeOrder) QueryTransactions() *TradeTransactionQuery {
	return NewTradeOrderClient(_m.config).QueryTransactions(_m)
}

// Update returns a builder for updating this TradeOrder.
// Note that you need to call TradeOrder.Unwrap() before calling this method if this TradeOrder
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *TradeOrder) Update() *TradeOrderUpdateOne {
	return NewTradeOrderClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the TradeOrder entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *TradeOrder) Unwrap() *TradeOrder {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: TradeOrder is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *TradeOrder) String() string {
	var builder strings.Builder
	builder.WriteString("TradeOrder(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("seller_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.SellerID))
	builder.WriteString(", ")
	if v := _m.VillageID; v != nil {
		builder.WriteString("village_id=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("scope=")
	builder.WriteString(_m.Scope)
	builder.WriteString(", ")
	builder.WriteString("item_id=")
	builder.WriteString(_m.ItemID)
	builder.WriteString(", ")
	builder.WriteString("item_type=")
	builder.WriteString(_m.ItemType)
	builder.WriteString(", ")
	if v := _m.Quality; v != nil {
		builder.WriteString("quality=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("quantity=")
	builder.WriteString(fmt.Sprintf("%v", _m.Quantity))
	builder.WriteString(", ")
	builder.WriteString("quantity_left=")
	builder.WriteString(fmt.Sprintf("%v", _m.QuantityLeft))
	builder.WriteString(", ")
	builder.WriteString("price_each=")
	builder.WriteString(fmt.Sprintf("%v", _m.PriceEach))
	builder.WriteString(", ")
	builder.WriteString("fee_rate=")
	builder.WriteString(fmt.Sprintf("%v", _m.FeeRate))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("listed_at=")
	builder.WriteString(_m.ListedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("expires_at=")
	builder.WriteString(_m.ExpiresAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// TradeOrders is a parsable slice of TradeOrder.
type TradeOrders []*TradeOrder
