// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/predicate"
	"github.com/liukai/farmer/server/ent/tutorialprogress"
	"github.com/liukai/farmer/server/ent/user"
)

// TutorialProgressUpdate is the builder for updating TutorialProgress entities.
type TutorialProgressUpdate struct {
	config
	hooks    []Hook
	mutation *TutorialProgressMutation
}

// Where appends a list predicates to the TutorialProgressUpdate builder.
func (_u *TutorialProgressUpdate) Where(ps ...predicate.TutorialProgress) *TutorialProgressUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *TutorialProgressUpdate) SetUserID(v uuid.UUID) *TutorialProgressUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TutorialProgressUpdate) SetNillableUserID(v *uuid.UUID) *TutorialProgressUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetStep sets the "step" field.
func (_u *TutorialProgressUpdate) SetStep(v string) *TutorialProgressUpdate {
	_u.mutation.SetStep(v)
	return _u
}

// SetNillableStep sets the "step" field if the given value is not nil.
func (_u *TutorialProgressUpdate) SetNillableStep(v *string) *TutorialProgressUpdate {
	if v != nil {
		_u.SetStep(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TutorialProgressUpdate) SetUser(v *User) *TutorialProgressUpdate {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TutorialProgressMutation object of the builder.
func (_u *TutorialProgressUpdate) Mutation() *TutorialProgressMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TutorialProgressUpdate) ClearUser() *TutorialProgressUpdate {
	_u.mutation.ClearUser()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *TutorialProgressUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TutorialProgressUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *TutorialProgressUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TutorialProgressUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TutorialProgressUpdate) check() error {
	if v, ok := _u.mutation.Step(); ok {
		if err := tutorialprogress.StepValidator(v); err != nil {
			return &ValidationError{Name: "step", err: fmt.Errorf(`ent: validator failed for field "TutorialProgress.step": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TutorialProgress.user"`)
	}
	return nil
}

func (_u *TutorialProgressUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tutorialprogress.Table, tutorialprogress.Columns, sqlgraph.NewFieldSpec(tutorialprogress.FieldID, field.TypeUUID))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Step(); ok {
		_spec.SetField(tutorialprogress.FieldStep, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tutorialprogress.UserTable,
			Columns: []string{tutorialprogress.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tutorialprogress.UserTable,
			Columns: []string{tutorialprogress.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tutorialprogress.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// TutorialProgressUpdateOne is the builder for updating a single TutorialProgress entity.
type TutorialProgressUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *TutorialProgressMutation
}

// SetUserID sets the "user_id" field.
func (_u *TutorialProgressUpdateOne) SetUserID(v uuid.UUID) *TutorialProgressUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *TutorialProgressUpdateOne) SetNillableUserID(v *uuid.UUID) *TutorialProgressUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetStep sets the "step" field.
func (_u *TutorialProgressUpdateOne) SetStep(v string) *TutorialProgressUpdateOne {
	_u.mutation.SetStep(v)
	return _u
}

// SetNillableStep sets the "step" field if the given value is not nil.
func (_u *TutorialProgressUpdateOne) SetNillableStep(v *string) *TutorialProgressUpdateOne {
	if v != nil {
		_u.SetStep(*v)
	}
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *TutorialProgressUpdateOne) SetUser(v *User) *TutorialProgressUpdateOne {
	return _u.SetUserID(v.ID)
}

// Mutation returns the TutorialProgressMutation object of the builder.
func (_u *TutorialProgressUpdateOne) Mutation() *TutorialProgressMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *TutorialProgressUpdateOne) ClearUser() *TutorialProgressUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// Where appends a list predicates to the TutorialProgressUpdate builder.
func (_u *TutorialProgressUpdateOne) Where(ps ...predicate.TutorialProgress) *TutorialProgressUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *TutorialProgressUpdateOne) Select(field string, fields ...string) *TutorialProgressUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated TutorialProgress entity.
func (_u *TutorialProgressUpdateOne) Save(ctx context.Context) (*TutorialProgress, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *TutorialProgressUpdateOne) SaveX(ctx context.Context) *TutorialProgress {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *TutorialProgressUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *TutorialProgressUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *TutorialProgressUpdateOne) check() error {
	if v, ok := _u.mutation.Step(); ok {
		if err := tutorialprogress.StepValidator(v); err != nil {
			return &ValidationError{Name: "step", err: fmt.Errorf(`ent: validator failed for field "TutorialProgress.step": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "TutorialProgress.user"`)
	}
	return nil
}

func (_u *TutorialProgressUpdateOne) sqlSave(ctx context.Context) (_node *TutorialProgress, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(tutorialprogress.Table, tutorialprogress.Columns, sqlgraph.NewFieldSpec(tutorialprogress.FieldID, field.TypeUUID))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "TutorialProgress.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, tutorialprogress.FieldID)
		for _, f := range fields {
			if !tutorialprogress.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != tutorialprogress.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Step(); ok {
		_spec.SetField(tutorialprogress.FieldStep, field.TypeString, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tutorialprogress.UserTable,
			Columns: []string{tutorialprogress.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   tutorialprogress.UserTable,
			Columns: []string{tutorialprogress.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &TutorialProgress{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{tutorialprogress.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
