// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"sync"

	"entgo.io/ent/dialect"
)

// Tx is a transactional client that is created by calling Client.Tx().
type Tx struct {
	config
	// ActivityComment is the client for interacting with the ActivityComment builders.
	ActivityComment *ActivityCommentClient
	// ActivityLike is the client for interacting with the ActivityLike builders.
	ActivityLike *ActivityLikeClient
	// ActivityLog is the client for interacting with the ActivityLog builders.
	ActivityLog *ActivityLogClient
	// Animal is the client for interacting with the Animal builders.
	Animal *AnimalClient
	// Building is the client for interacting with the Building builders.
	Building *BuildingClient
	// ChatLog is the client for interacting with the ChatLog builders.
	ChatLog *ChatLogClient
	// DailyCheckin is the client for interacting with the DailyCheckin builders.
	DailyCheckin *DailyCheckinClient
	// Farm is the client for interacting with the Farm builders.
	Farm *FarmClient
	// Friend is the client for interacting with the Friend builders.
	Friend *FriendClient
	// FriendRequest is the client for interacting with the FriendRequest builders.
	FriendRequest *FriendRequestClient
	// Gift is the client for interacting with the Gift builders.
	Gift *GiftClient
	// HelpRequest is the client for interacting with the HelpRequest builders.
	HelpRequest *HelpRequestClient
	// InventoryItem is the client for interacting with the InventoryItem builders.
	InventoryItem *InventoryItemClient
	// Notification is the client for interacting with the Notification builders.
	Notification *NotificationClient
	// PaymentOrder is the client for interacting with the PaymentOrder builders.
	PaymentOrder *PaymentOrderClient
	// Relationship is the client for interacting with the Relationship builders.
	Relationship *RelationshipClient
	// Role is the client for interacting with the Role builders.
	Role *RoleClient
	// Season is the client for interacting with the Season builders.
	Season *SeasonClient
	// SeasonScore is the client for interacting with the SeasonScore builders.
	SeasonScore *SeasonScoreClient
	// SeasonTaskProgress is the client for interacting with the SeasonTaskProgress builders.
	SeasonTaskProgress *SeasonTaskProgressClient
	// Subscription is the client for interacting with the Subscription builders.
	Subscription *SubscriptionClient
	// TradeOrder is the client for interacting with the TradeOrder builders.
	TradeOrder *TradeOrderClient
	// TradeTransaction is the client for interacting with the TradeTransaction builders.
	TradeTransaction *TradeTransactionClient
	// TutorialProgress is the client for interacting with the TutorialProgress builders.
	TutorialProgress *TutorialProgressClient
	// User is the client for interacting with the User builders.
	User *UserClient
	// Village is the client for interacting with the Village builders.
	Village *VillageClient
	// VillageMember is the client for interacting with the VillageMember builders.
	VillageMember *VillageMemberClient
	// VillageProject is the client for interacting with the VillageProject builders.
	VillageProject *VillageProjectClient
	// VillageProjectContribution is the client for interacting with the VillageProjectContribution builders.
	VillageProjectContribution *VillageProjectContributionClient

	// lazily loaded.
	client     *Client
	clientOnce sync.Once
	// ctx lives for the life of the transaction. It is
	// the same context used by the underlying connection.
	ctx context.Context
}

type (
	// Committer is the interface that wraps the Commit method.
	Committer interface {
		Commit(context.Context, *Tx) error
	}

	// The CommitFunc type is an adapter to allow the use of ordinary
	// function as a Committer. If f is a function with the appropriate
	// signature, CommitFunc(f) is a Committer that calls f.
	CommitFunc func(context.Context, *Tx) error

	// CommitHook defines the "commit middleware". A function that gets a Committer
	// and returns a Committer. For example:
	//
	//	hook := func(next ent.Committer) ent.Committer {
	//		return ent.CommitFunc(func(ctx context.Context, tx *ent.Tx) error {
	//			// Do some stuff before.
	//			if err := next.Commit(ctx, tx); err != nil {
	//				return err
	//			}
	//			// Do some stuff after.
	//			return nil
	//		})
	//	}
	//
	CommitHook func(Committer) Committer
)

// Commit calls f(ctx, m).
func (f CommitFunc) Commit(ctx context.Context, tx *Tx) error {
	return f(ctx, tx)
}

// Commit commits the transaction.
func (tx *Tx) Commit() error {
	txDriver := tx.config.driver.(*txDriver)
	var fn Committer = CommitFunc(func(context.Context, *Tx) error {
		return txDriver.tx.Commit()
	})
	txDriver.mu.Lock()
	hooks := append([]CommitHook(nil), txDriver.onCommit...)
	txDriver.mu.Unlock()
	for i := len(hooks) - 1; i >= 0; i-- {
		fn = hooks[i](fn)
	}
	return fn.Commit(tx.ctx, tx)
}

// OnCommit adds a hook to call on commit.
func (tx *Tx) OnCommit(f CommitHook) {
	txDriver := tx.config.driver.(*txDriver)
	txDriver.mu.Lock()
	txDriver.onCommit = append(txDriver.onCommit, f)
	txDriver.mu.Unlock()
}

type (
	// Rollbacker is the interface that wraps the Rollback method.
	Rollbacker interface {
		Rollback(context.Context, *Tx) error
	}

	// The RollbackFunc type is an adapter to allow the use of ordinary
	// function as a Rollbacker. If f is a function with the appropriate
	// signature, RollbackFunc(f) is a Rollbacker that calls f.
	RollbackFunc func(context.Context, *Tx) error

	// RollbackHook defines the "rollback middleware". A function that gets a Rollbacker
	// and returns a Rollbacker. For example:
	//
	//	hook := func(next ent.Rollbacker) ent.Rollbacker {
	//		return ent.RollbackFunc(func(ctx context.Context, tx *ent.Tx) error {
	//			// Do some stuff before.
	//			if err := next.Rollback(ctx, tx); err != nil {
	//				return err
	//			}
	//			// Do some stuff after.
	//			return nil
	//		})
	//	}
	//
	RollbackHook func(Rollbacker) Rollbacker
)

// Rollback calls f(ctx, m).
func (f RollbackFunc) Rollback(ctx context.Context, tx *Tx) error {
	return f(ctx, tx)
}

// Rollback rollbacks the transaction.
func (tx *Tx) Rollback() error {
	txDriver := tx.config.driver.(*txDriver)
	var fn Rollbacker = RollbackFunc(func(context.Context, *Tx) error {
		return txDriver.tx.Rollback()
	})
	txDriver.mu.Lock()
	hooks := append([]RollbackHook(nil), txDriver.onRollback...)
	txDriver.mu.Unlock()
	for i := len(hooks) - 1; i >= 0; i-- {
		fn = hooks[i](fn)
	}
	return fn.Rollback(tx.ctx, tx)
}

// OnRollback adds a hook to call on rollback.
func (tx *Tx) OnRollback(f RollbackHook) {
	txDriver := tx.config.driver.(*txDriver)
	txDriver.mu.Lock()
	txDriver.onRollback = append(txDriver.onRollback, f)
	txDriver.mu.Unlock()
}

// Client returns a Client that binds to current transaction.
func (tx *Tx) Client() *Client {
	tx.clientOnce.Do(func() {
		tx.client = &Client{config: tx.config}
		tx.client.init()
	})
	return tx.client
}

func (tx *Tx) init() {
	tx.ActivityComment = NewActivityCommentClient(tx.config)
	tx.ActivityLike = NewActivityLikeClient(tx.config)
	tx.ActivityLog = NewActivityLogClient(tx.config)
	tx.Animal = NewAnimalClient(tx.config)
	tx.Building = NewBuildingClient(tx.config)
	tx.ChatLog = NewChatLogClient(tx.config)
	tx.DailyCheckin = NewDailyCheckinClient(tx.config)
	tx.Farm = NewFarmClient(tx.config)
	tx.Friend = NewFriendClient(tx.config)
	tx.FriendRequest = NewFriendRequestClient(tx.config)
	tx.Gift = NewGiftClient(tx.config)
	tx.HelpRequest = NewHelpRequestClient(tx.config)
	tx.InventoryItem = NewInventoryItemClient(tx.config)
	tx.Notification = NewNotificationClient(tx.config)
	tx.PaymentOrder = NewPaymentOrderClient(tx.config)
	tx.Relationship = NewRelationshipClient(tx.config)
	tx.Role = NewRoleClient(tx.config)
	tx.Season = NewSeasonClient(tx.config)
	tx.SeasonScore = NewSeasonScoreClient(tx.config)
	tx.SeasonTaskProgress = NewSeasonTaskProgressClient(tx.config)
	tx.Subscription = NewSubscriptionClient(tx.config)
	tx.TradeOrder = NewTradeOrderClient(tx.config)
	tx.TradeTransaction = NewTradeTransactionClient(tx.config)
	tx.TutorialProgress = NewTutorialProgressClient(tx.config)
	tx.User = NewUserClient(tx.config)
	tx.Village = NewVillageClient(tx.config)
	tx.VillageMember = NewVillageMemberClient(tx.config)
	tx.VillageProject = NewVillageProjectClient(tx.config)
	tx.VillageProjectContribution = NewVillageProjectContributionClient(tx.config)
}

// txDriver wraps the given dialect.Tx with a nop dialect.Driver implementation.
// The idea is to support transactions without adding any extra code to the builders.
// When a builder calls to driver.Tx(), it gets the same dialect.Tx instance.
// Commit and Rollback are nop for the internal builders and the user must call one
// of them in order to commit or rollback the transaction.
//
// If a closed transaction is embedded in one of the generated entities, and the entity
// applies a query, for example: ActivityComment.QueryXXX(), the query will be executed
// through the driver which created this transaction.
//
// Note that txDriver is not goroutine safe.
type txDriver struct {
	// the driver we started the transaction from.
	drv dialect.Driver
	// tx is the underlying transaction.
	tx dialect.Tx
	// completion hooks.
	mu         sync.Mutex
	onCommit   []CommitHook
	onRollback []RollbackHook
}

// newTx creates a new transactional driver.
func newTx(ctx context.Context, drv dialect.Driver) (*txDriver, error) {
	tx, err := drv.Tx(ctx)
	if err != nil {
		return nil, err
	}
	return &txDriver{tx: tx, drv: drv}, nil
}

// Tx returns the transaction wrapper (txDriver) to avoid Commit or Rollback calls
// from the internal builders. Should be called only by the internal builders.
func (tx *txDriver) Tx(context.Context) (dialect.Tx, error) { return tx, nil }

// Dialect returns the dialect of the driver we started the transaction from.
func (tx *txDriver) Dialect() string { return tx.drv.Dialect() }

// Close is a nop close.
func (*txDriver) Close() error { return nil }

// Commit is a nop commit for the internal builders.
// User must call `Tx.Commit` in order to commit the transaction.
func (*txDriver) Commit() error { return nil }

// Rollback is a nop rollback for the internal builders.
// User must call `Tx.Rollback` in order to rollback the transaction.
func (*txDriver) Rollback() error { return nil }

// Exec calls tx.Exec.
func (tx *txDriver) Exec(ctx context.Context, query string, args, v any) error {
	return tx.tx.Exec(ctx, query, args, v)
}

// Query calls tx.Query.
func (tx *txDriver) Query(ctx context.Context, query string, args, v any) error {
	return tx.tx.Query(ctx, query, args, v)
}

var _ dialect.Driver = (*txDriver)(nil)
