// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/user"
	"github.com/liukai/farmer/server/ent/village"
	"github.com/liukai/farmer/server/ent/villagemember"
)

// VillageMemberCreate is the builder for creating a VillageMember entity.
type VillageMemberCreate struct {
	config
	mutation *VillageMemberMutation
	hooks    []Hook
}

// SetVillageID sets the "village_id" field.
func (_c *VillageMemberCreate) SetVillageID(v uuid.UUID) *VillageMemberCreate {
	_c.mutation.SetVillageID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *VillageMemberCreate) SetUserID(v uuid.UUID) *VillageMemberCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetRole sets the "role" field.
func (_c *VillageMemberCreate) SetRole(v string) *VillageMemberCreate {
	_c.mutation.SetRole(v)
	return _c
}

// SetNillableRole sets the "role" field if the given value is not nil.
func (_c *VillageMemberCreate) SetNillableRole(v *string) *VillageMemberCreate {
	if v != nil {
		_c.SetRole(*v)
	}
	return _c
}

// SetContribution sets the "contribution" field.
func (_c *VillageMemberCreate) SetContribution(v int64) *VillageMemberCreate {
	_c.mutation.SetContribution(v)
	return _c
}

// SetNillableContribution sets the "contribution" field if the given value is not nil.
func (_c *VillageMemberCreate) SetNillableContribution(v *int64) *VillageMemberCreate {
	if v != nil {
		_c.SetContribution(*v)
	}
	return _c
}

// SetJoinedAt sets the "joined_at" field.
func (_c *VillageMemberCreate) SetJoinedAt(v time.Time) *VillageMemberCreate {
	_c.mutation.SetJoinedAt(v)
	return _c
}

// SetNillableJoinedAt sets the "joined_at" field if the given value is not nil.
func (_c *VillageMemberCreate) SetNillableJoinedAt(v *time.Time) *VillageMemberCreate {
	if v != nil {
		_c.SetJoinedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *VillageMemberCreate) SetID(v uuid.UUID) *VillageMemberCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *VillageMemberCreate) SetNillableID(v *uuid.UUID) *VillageMemberCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetVillage sets the "village" edge to the Village entity.
func (_c *VillageMemberCreate) SetVillage(v *Village) *VillageMemberCreate {
	return _c.SetVillageID(v.ID)
}

// SetUser sets the "user" edge to the User entity.
func (_c *VillageMemberCreate) SetUser(v *User) *VillageMemberCreate {
	return _c.SetUserID(v.ID)
}

// Mutation returns the VillageMemberMutation object of the builder.
func (_c *VillageMemberCreate) Mutation() *VillageMemberMutation {
	return _c.mutation
}

// Save creates the VillageMember in the database.
func (_c *VillageMemberCreate) Save(ctx context.Context) (*VillageMember, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VillageMemberCreate) SaveX(ctx context.Context) *VillageMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VillageMemberCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VillageMemberCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VillageMemberCreate) defaults() {
	if _, ok := _c.mutation.Role(); !ok {
		v := villagemember.DefaultRole
		_c.mutation.SetRole(v)
	}
	if _, ok := _c.mutation.Contribution(); !ok {
		v := villagemember.DefaultContribution
		_c.mutation.SetContribution(v)
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		v := villagemember.DefaultJoinedAt()
		_c.mutation.SetJoinedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := villagemember.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VillageMemberCreate) check() error {
	if _, ok := _c.mutation.VillageID(); !ok {
		return &ValidationError{Name: "village_id", err: errors.New(`ent: missing required field "VillageMember.village_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "VillageMember.user_id"`)}
	}
	if _, ok := _c.mutation.Role(); !ok {
		return &ValidationError{Name: "role", err: errors.New(`ent: missing required field "VillageMember.role"`)}
	}
	if v, ok := _c.mutation.Role(); ok {
		if err := villagemember.RoleValidator(v); err != nil {
			return &ValidationError{Name: "role", err: fmt.Errorf(`ent: validator failed for field "VillageMember.role": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Contribution(); !ok {
		return &ValidationError{Name: "contribution", err: errors.New(`ent: missing required field "VillageMember.contribution"`)}
	}
	if v, ok := _c.mutation.Contribution(); ok {
		if err := villagemember.ContributionValidator(v); err != nil {
			return &ValidationError{Name: "contribution", err: fmt.Errorf(`ent: validator failed for field "VillageMember.contribution": %w`, err)}
		}
	}
	if _, ok := _c.mutation.JoinedAt(); !ok {
		return &ValidationError{Name: "joined_at", err: errors.New(`ent: missing required field "VillageMember.joined_at"`)}
	}
	if len(_c.mutation.VillageIDs()) == 0 {
		return &ValidationError{Name: "village", err: errors.New(`ent: missing required edge "VillageMember.village"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "VillageMember.user"`)}
	}
	return nil
}

func (_c *VillageMemberCreate) sqlSave(ctx context.Context) (*VillageMember, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VillageMemberCreate) createSpec() (*VillageMember, *sqlgraph.CreateSpec) {
	var (
		_node = &VillageMember{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(villagemember.Table, sqlgraph.NewFieldSpec(villagemember.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.Role(); ok {
		_spec.SetField(villagemember.FieldRole, field.TypeString, value)
		_node.Role = value
	}
	if value, ok := _c.mutation.Contribution(); ok {
		_spec.SetField(villagemember.FieldContribution, field.TypeInt64, value)
		_node.Contribution = value
	}
	if value, ok := _c.mutation.JoinedAt(); ok {
		_spec.SetField(villagemember.FieldJoinedAt, field.TypeTime, value)
		_node.JoinedAt = value
	}
	if nodes := _c.mutation.VillageIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   villagemember.VillageTable,
			Columns: []string{villagemember.VillageColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(village.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.VillageID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   villagemember.UserTable,
			Columns: []string{villagemember.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// VillageMemberCreateBulk is the builder for creating many VillageMember entities in bulk.
type VillageMemberCreateBulk struct {
	config
	err      error
	builders []*VillageMemberCreate
}

// Save creates the VillageMember entities in the database.
func (_c *VillageMemberCreateBulk) Save(ctx context.Context) ([]*VillageMember, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VillageMember, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VillageMemberMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VillageMemberCreateBulk) SaveX(ctx context.Context) []*VillageMember {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VillageMemberCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VillageMemberCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
