// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/user"
	"github.com/liukai/farmer/server/ent/village"
	"github.com/liukai/farmer/server/ent/villagemember"
)

// VillageMember is the model entity for the VillageMember schema.
type VillageMember struct {
	config `json:"-"`
	// ID of the ent.
	ID uuid.UUID `json:"id,omitempty"`
	// VillageID holds the value of the "village_id" field.
	VillageID uuid.UUID `json:"village_id,omitempty"`
	// 一个用户只能加入一个村庄
	UserID uuid.UUID `json:"user_id,omitempty"`
	// member/elder/chief
	Role string `json:"role,omitempty"`
	// 个人对本村总贡献
	Contribution int64 `json:"contribution,omitempty"`
	// JoinedAt holds the value of the "joined_at" field.
	JoinedAt time.Time `json:"joined_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the VillageMemberQuery when eager-loading is set.
	Edges        VillageMemberEdges `json:"edges"`
	selectValues sql.SelectValues
}

// VillageMemberEdges holds the relations/edges for other nodes in the graph.
type VillageMemberEdges struct {
	// Village holds the value of the village edge.
	Village *Village `json:"village,omitempty"`
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// VillageOrErr returns the Village value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VillageMemberEdges) VillageOrErr() (*Village, error) {
	if e.Village != nil {
		return e.Village, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: village.Label}
	}
	return nil, &NotLoadedError{edge: "village"}
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e VillageMemberEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*VillageMember) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case villagemember.FieldContribution:
			values[i] = new(sql.NullInt64)
		case villagemember.FieldRole:
			values[i] = new(sql.NullString)
		case villagemember.FieldJoinedAt:
			values[i] = new(sql.NullTime)
		case villagemember.FieldID, villagemember.FieldVillageID, villagemember.FieldUserID:
			values[i] = new(uuid.UUID)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the VillageMember fields.
func (_m *VillageMember) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case villagemember.FieldID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value != nil {
				_m.ID = *value
			}
		case villagemember.FieldVillageID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field village_id", values[i])
			} else if value != nil {
				_m.VillageID = *value
			}
		case villagemember.FieldUserID:
			if value, ok := values[i].(*uuid.UUID); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value != nil {
				_m.UserID = *value
			}
		case villagemember.FieldRole:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field role", values[i])
			} else if value.Valid {
				_m.Role = value.String
			}
		case villagemember.FieldContribution:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field contribution", values[i])
			} else if value.Valid {
				_m.Contribution = value.Int64
			}
		case villagemember.FieldJoinedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field joined_at", values[i])
			} else if value.Valid {
				_m.JoinedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the VillageMember.
// This includes values selected through modifiers, order, etc.
func (_m *VillageMember) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryVillage queries the "village" edge of the VillageMember entity.
func (_m *VillageMember) QueryVillage() *VillageQuery {
	return NewVillageMemberClient(_m.config).QueryVillage(_m)
}

// QueryUser queries the "user" edge of the VillageMember entity.
func (_m *VillageMember) QueryUser() *UserQuery {
	return NewVillageMemberClient(_m.config).QueryUser(_m)
}

// Update returns a builder for updating this VillageMember.
// Note that you need to call VillageMember.Unwrap() before calling this method if this VillageMember
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *VillageMember) Update() *VillageMemberUpdateOne {
	return NewVillageMemberClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the VillageMember entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *VillageMember) Unwrap() *VillageMember {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: VillageMember is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *VillageMember) String() string {
	var builder strings.Builder
	builder.WriteString("VillageMember(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("village_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.VillageID))
	builder.WriteString(", ")
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("role=")
	builder.WriteString(_m.Role)
	builder.WriteString(", ")
	builder.WriteString("contribution=")
	builder.WriteString(fmt.Sprintf("%v", _m.Contribution))
	builder.WriteString(", ")
	builder.WriteString("joined_at=")
	builder.WriteString(_m.JoinedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// VillageMembers is a parsable slice of VillageMember.
type VillageMembers []*VillageMember
