// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/user"
	"github.com/liukai/farmer/server/ent/villageproject"
	"github.com/liukai/farmer/server/ent/villageprojectcontribution"
)

// VillageProjectContributionCreate is the builder for creating a VillageProjectContribution entity.
type VillageProjectContributionCreate struct {
	config
	mutation *VillageProjectContributionMutation
	hooks    []Hook
}

// SetProjectID sets the "project_id" field.
func (_c *VillageProjectContributionCreate) SetProjectID(v uuid.UUID) *VillageProjectContributionCreate {
	_c.mutation.SetProjectID(v)
	return _c
}

// SetUserID sets the "user_id" field.
func (_c *VillageProjectContributionCreate) SetUserID(v uuid.UUID) *VillageProjectContributionCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetResourceType sets the "resource_type" field.
func (_c *VillageProjectContributionCreate) SetResourceType(v string) *VillageProjectContributionCreate {
	_c.mutation.SetResourceType(v)
	return _c
}

// SetItemID sets the "item_id" field.
func (_c *VillageProjectContributionCreate) SetItemID(v string) *VillageProjectContributionCreate {
	_c.mutation.SetItemID(v)
	return _c
}

// SetNillableItemID sets the "item_id" field if the given value is not nil.
func (_c *VillageProjectContributionCreate) SetNillableItemID(v *string) *VillageProjectContributionCreate {
	if v != nil {
		_c.SetItemID(*v)
	}
	return _c
}

// SetQuantity sets the "quantity" field.
func (_c *VillageProjectContributionCreate) SetQuantity(v int64) *VillageProjectContributionCreate {
	_c.mutation.SetQuantity(v)
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *VillageProjectContributionCreate) SetCreatedAt(v time.Time) *VillageProjectContributionCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *VillageProjectContributionCreate) SetNillableCreatedAt(v *time.Time) *VillageProjectContributionCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *VillageProjectContributionCreate) SetID(v uuid.UUID) *VillageProjectContributionCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *VillageProjectContributionCreate) SetNillableID(v *uuid.UUID) *VillageProjectContributionCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetProject sets the "project" edge to the VillageProject entity.
func (_c *VillageProjectContributionCreate) SetProject(v *VillageProject) *VillageProjectContributionCreate {
	return _c.SetProjectID(v.ID)
}

// SetContributorID sets the "contributor" edge to the User entity by ID.
func (_c *VillageProjectContributionCreate) SetContributorID(id uuid.UUID) *VillageProjectContributionCreate {
	_c.mutation.SetContributorID(id)
	return _c
}

// SetContributor sets the "contributor" edge to the User entity.
func (_c *VillageProjectContributionCreate) SetContributor(v *User) *VillageProjectContributionCreate {
	return _c.SetContributorID(v.ID)
}

// Mutation returns the VillageProjectContributionMutation object of the builder.
func (_c *VillageProjectContributionCreate) Mutation() *VillageProjectContributionMutation {
	return _c.mutation
}

// Save creates the VillageProjectContribution in the database.
func (_c *VillageProjectContributionCreate) Save(ctx context.Context) (*VillageProjectContribution, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *VillageProjectContributionCreate) SaveX(ctx context.Context) *VillageProjectContribution {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VillageProjectContributionCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VillageProjectContributionCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *VillageProjectContributionCreate) defaults() {
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := villageprojectcontribution.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := villageprojectcontribution.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *VillageProjectContributionCreate) check() error {
	if _, ok := _c.mutation.ProjectID(); !ok {
		return &ValidationError{Name: "project_id", err: errors.New(`ent: missing required field "VillageProjectContribution.project_id"`)}
	}
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "VillageProjectContribution.user_id"`)}
	}
	if _, ok := _c.mutation.ResourceType(); !ok {
		return &ValidationError{Name: "resource_type", err: errors.New(`ent: missing required field "VillageProjectContribution.resource_type"`)}
	}
	if v, ok := _c.mutation.ResourceType(); ok {
		if err := villageprojectcontribution.ResourceTypeValidator(v); err != nil {
			return &ValidationError{Name: "resource_type", err: fmt.Errorf(`ent: validator failed for field "VillageProjectContribution.resource_type": %w`, err)}
		}
	}
	if v, ok := _c.mutation.ItemID(); ok {
		if err := villageprojectcontribution.ItemIDValidator(v); err != nil {
			return &ValidationError{Name: "item_id", err: fmt.Errorf(`ent: validator failed for field "VillageProjectContribution.item_id": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Quantity(); !ok {
		return &ValidationError{Name: "quantity", err: errors.New(`ent: missing required field "VillageProjectContribution.quantity"`)}
	}
	if v, ok := _c.mutation.Quantity(); ok {
		if err := villageprojectcontribution.QuantityValidator(v); err != nil {
			return &ValidationError{Name: "quantity", err: fmt.Errorf(`ent: validator failed for field "VillageProjectContribution.quantity": %w`, err)}
		}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "VillageProjectContribution.created_at"`)}
	}
	if len(_c.mutation.ProjectIDs()) == 0 {
		return &ValidationError{Name: "project", err: errors.New(`ent: missing required edge "VillageProjectContribution.project"`)}
	}
	if len(_c.mutation.ContributorIDs()) == 0 {
		return &ValidationError{Name: "contributor", err: errors.New(`ent: missing required edge "VillageProjectContribution.contributor"`)}
	}
	return nil
}

func (_c *VillageProjectContributionCreate) sqlSave(ctx context.Context) (*VillageProjectContribution, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(*uuid.UUID); ok {
			_node.ID = *id
		} else if err := _node.ID.Scan(_spec.ID.Value); err != nil {
			return nil, err
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *VillageProjectContributionCreate) createSpec() (*VillageProjectContribution, *sqlgraph.CreateSpec) {
	var (
		_node = &VillageProjectContribution{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(villageprojectcontribution.Table, sqlgraph.NewFieldSpec(villageprojectcontribution.FieldID, field.TypeUUID))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = &id
	}
	if value, ok := _c.mutation.ResourceType(); ok {
		_spec.SetField(villageprojectcontribution.FieldResourceType, field.TypeString, value)
		_node.ResourceType = value
	}
	if value, ok := _c.mutation.ItemID(); ok {
		_spec.SetField(villageprojectcontribution.FieldItemID, field.TypeString, value)
		_node.ItemID = &value
	}
	if value, ok := _c.mutation.Quantity(); ok {
		_spec.SetField(villageprojectcontribution.FieldQuantity, field.TypeInt64, value)
		_node.Quantity = value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(villageprojectcontribution.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if nodes := _c.mutation.ProjectIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   villageprojectcontribution.ProjectTable,
			Columns: []string{villageprojectcontribution.ProjectColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(villageproject.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.ProjectID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.ContributorIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: true,
			Table:   villageprojectcontribution.ContributorTable,
			Columns: []string{villageprojectcontribution.ContributorColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeUUID),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// VillageProjectContributionCreateBulk is the builder for creating many VillageProjectContribution entities in bulk.
type VillageProjectContributionCreateBulk struct {
	config
	err      error
	builders []*VillageProjectContributionCreate
}

// Save creates the VillageProjectContribution entities in the database.
func (_c *VillageProjectContributionCreateBulk) Save(ctx context.Context) ([]*VillageProjectContribution, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*VillageProjectContribution, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*VillageProjectContributionMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *VillageProjectContributionCreateBulk) SaveX(ctx context.Context) []*VillageProjectContribution {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *VillageProjectContributionCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *VillageProjectContributionCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
