// Code generated by ent, DO NOT EDIT.

package role

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the role type in the database.
	Label = "role"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldAvatar holds the string denoting the avatar field in the database.
	FieldAvatar = "avatar"
	// FieldExtroversion holds the string denoting the extroversion field in the database.
	FieldExtroversion = "extroversion"
	// FieldGenerosity holds the string denoting the generosity field in the database.
	FieldGenerosity = "generosity"
	// FieldAdventure holds the string denoting the adventure field in the database.
	FieldAdventure = "adventure"
	// FieldStrategyManagement holds the string denoting the strategy_management field in the database.
	FieldStrategyManagement = "strategy_management"
	// FieldStrategyPlanting holds the string denoting the strategy_planting field in the database.
	FieldStrategyPlanting = "strategy_planting"
	// FieldStrategySocial holds the string denoting the strategy_social field in the database.
	FieldStrategySocial = "strategy_social"
	// FieldStrategyTrade holds the string denoting the strategy_trade field in the database.
	FieldStrategyTrade = "strategy_trade"
	// FieldStrategyResource holds the string denoting the strategy_resource field in the database.
	FieldStrategyResource = "strategy_resource"
	// FieldDailySocialCount holds the string denoting the daily_social_count field in the database.
	FieldDailySocialCount = "daily_social_count"
	// FieldDailySocialDate holds the string denoting the daily_social_date field in the database.
	FieldDailySocialDate = "daily_social_date"
	// FieldLastActiveAt holds the string denoting the last_active_at field in the database.
	FieldLastActiveAt = "last_active_at"
	// FieldMapID holds the string denoting the map_id field in the database.
	FieldMapID = "map_id"
	// FieldTileX holds the string denoting the tile_x field in the database.
	FieldTileX = "tile_x"
	// FieldTileY holds the string denoting the tile_y field in the database.
	FieldTileY = "tile_y"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the role in the database.
	Table = "roles"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "roles"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for role fields.
var Columns = []string{
	FieldID,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldUserID,
	FieldName,
	FieldAvatar,
	FieldExtroversion,
	FieldGenerosity,
	FieldAdventure,
	FieldStrategyManagement,
	FieldStrategyPlanting,
	FieldStrategySocial,
	FieldStrategyTrade,
	FieldStrategyResource,
	FieldDailySocialCount,
	FieldDailySocialDate,
	FieldLastActiveAt,
	FieldMapID,
	FieldTileX,
	FieldTileY,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// AvatarValidator is a validator for the "avatar" field. It is called by the builders before save.
	AvatarValidator func(string) error
	// DefaultExtroversion holds the default value on creation for the "extroversion" field.
	DefaultExtroversion int
	// ExtroversionValidator is a validator for the "extroversion" field. It is called by the builders before save.
	ExtroversionValidator func(int) error
	// DefaultGenerosity holds the default value on creation for the "generosity" field.
	DefaultGenerosity int
	// GenerosityValidator is a validator for the "generosity" field. It is called by the builders before save.
	GenerosityValidator func(int) error
	// DefaultAdventure holds the default value on creation for the "adventure" field.
	DefaultAdventure int
	// AdventureValidator is a validator for the "adventure" field. It is called by the builders before save.
	AdventureValidator func(int) error
	// DefaultStrategyManagement holds the default value on creation for the "strategy_management" field.
	DefaultStrategyManagement int
	// StrategyManagementValidator is a validator for the "strategy_management" field. It is called by the builders before save.
	StrategyManagementValidator func(int) error
	// DefaultStrategyPlanting holds the default value on creation for the "strategy_planting" field.
	DefaultStrategyPlanting int
	// StrategyPlantingValidator is a validator for the "strategy_planting" field. It is called by the builders before save.
	StrategyPlantingValidator func(int) error
	// DefaultStrategySocial holds the default value on creation for the "strategy_social" field.
	DefaultStrategySocial int
	// StrategySocialValidator is a validator for the "strategy_social" field. It is called by the builders before save.
	StrategySocialValidator func(int) error
	// DefaultStrategyTrade holds the default value on creation for the "strategy_trade" field.
	DefaultStrategyTrade int
	// StrategyTradeValidator is a validator for the "strategy_trade" field. It is called by the builders before save.
	StrategyTradeValidator func(int) error
	// DefaultStrategyResource holds the default value on creation for the "strategy_resource" field.
	DefaultStrategyResource int
	// StrategyResourceValidator is a validator for the "strategy_resource" field. It is called by the builders before save.
	StrategyResourceValidator func(int) error
	// DefaultDailySocialCount holds the default value on creation for the "daily_social_count" field.
	DefaultDailySocialCount int
	// DailySocialCountValidator is a validator for the "daily_social_count" field. It is called by the builders before save.
	DailySocialCountValidator func(int) error
	// DefaultMapID holds the default value on creation for the "map_id" field.
	DefaultMapID string
	// DefaultTileX holds the default value on creation for the "tile_x" field.
	DefaultTileX int
	// DefaultTileY holds the default value on creation for the "tile_y" field.
	DefaultTileY int
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Role queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByAvatar orders the results by the avatar field.
func ByAvatar(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatar, opts...).ToFunc()
}

// ByExtroversion orders the results by the extroversion field.
func ByExtroversion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldExtroversion, opts...).ToFunc()
}

// ByGenerosity orders the results by the generosity field.
func ByGenerosity(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGenerosity, opts...).ToFunc()
}

// ByAdventure orders the results by the adventure field.
func ByAdventure(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAdventure, opts...).ToFunc()
}

// ByStrategyManagement orders the results by the strategy_management field.
func ByStrategyManagement(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrategyManagement, opts...).ToFunc()
}

// ByStrategyPlanting orders the results by the strategy_planting field.
func ByStrategyPlanting(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrategyPlanting, opts...).ToFunc()
}

// ByStrategySocial orders the results by the strategy_social field.
func ByStrategySocial(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrategySocial, opts...).ToFunc()
}

// ByStrategyTrade orders the results by the strategy_trade field.
func ByStrategyTrade(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrategyTrade, opts...).ToFunc()
}

// ByStrategyResource orders the results by the strategy_resource field.
func ByStrategyResource(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStrategyResource, opts...).ToFunc()
}

// ByDailySocialCount orders the results by the daily_social_count field.
func ByDailySocialCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailySocialCount, opts...).ToFunc()
}

// ByDailySocialDate orders the results by the daily_social_date field.
func ByDailySocialDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDailySocialDate, opts...).ToFunc()
}

// ByLastActiveAt orders the results by the last_active_at field.
func ByLastActiveAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastActiveAt, opts...).ToFunc()
}

// ByMapID orders the results by the map_id field.
func ByMapID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMapID, opts...).ToFunc()
}

// ByTileX orders the results by the tile_x field.
func ByTileX(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTileX, opts...).ToFunc()
}

// ByTileY orders the results by the tile_y field.
func ByTileY(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTileY, opts...).ToFunc()
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
	)
}
