// Code generated by ent, DO NOT EDIT.

package villagemember

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldLTE(FieldID, id))
}

// VillageID applies equality check predicate on the "village_id" field. It's identical to VillageIDEQ.
func VillageID(v uuid.UUID) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldEQ(FieldVillageID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldEQ(FieldUserID, v))
}

// Role applies equality check predicate on the "role" field. It's identical to RoleEQ.
func Role(v string) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldEQ(FieldRole, v))
}

// Contribution applies equality check predicate on the "contribution" field. It's identical to ContributionEQ.
func Contribution(v int64) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldEQ(FieldContribution, v))
}

// JoinedAt applies equality check predicate on the "joined_at" field. It's identical to JoinedAtEQ.
func JoinedAt(v time.Time) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldEQ(FieldJoinedAt, v))
}

// VillageIDEQ applies the EQ predicate on the "village_id" field.
func VillageIDEQ(v uuid.UUID) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldEQ(FieldVillageID, v))
}

// VillageIDNEQ applies the NEQ predicate on the "village_id" field.
func VillageIDNEQ(v uuid.UUID) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldNEQ(FieldVillageID, v))
}

// VillageIDIn applies the In predicate on the "village_id" field.
func VillageIDIn(vs ...uuid.UUID) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldIn(FieldVillageID, vs...))
}

// VillageIDNotIn applies the NotIn predicate on the "village_id" field.
func VillageIDNotIn(vs ...uuid.UUID) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldNotIn(FieldVillageID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldNotIn(FieldUserID, vs...))
}

// RoleEQ applies the EQ predicate on the "role" field.
func RoleEQ(v string) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldEQ(FieldRole, v))
}

// RoleNEQ applies the NEQ predicate on the "role" field.
func RoleNEQ(v string) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldNEQ(FieldRole, v))
}

// RoleIn applies the In predicate on the "role" field.
func RoleIn(vs ...string) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldIn(FieldRole, vs...))
}

// RoleNotIn applies the NotIn predicate on the "role" field.
func RoleNotIn(vs ...string) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldNotIn(FieldRole, vs...))
}

// RoleGT applies the GT predicate on the "role" field.
func RoleGT(v string) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldGT(FieldRole, v))
}

// RoleGTE applies the GTE predicate on the "role" field.
func RoleGTE(v string) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldGTE(FieldRole, v))
}

// RoleLT applies the LT predicate on the "role" field.
func RoleLT(v string) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldLT(FieldRole, v))
}

// RoleLTE applies the LTE predicate on the "role" field.
func RoleLTE(v string) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldLTE(FieldRole, v))
}

// RoleContains applies the Contains predicate on the "role" field.
func RoleContains(v string) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldContains(FieldRole, v))
}

// RoleHasPrefix applies the HasPrefix predicate on the "role" field.
func RoleHasPrefix(v string) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldHasPrefix(FieldRole, v))
}

// RoleHasSuffix applies the HasSuffix predicate on the "role" field.
func RoleHasSuffix(v string) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldHasSuffix(FieldRole, v))
}

// RoleEqualFold applies the EqualFold predicate on the "role" field.
func RoleEqualFold(v string) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldEqualFold(FieldRole, v))
}

// RoleContainsFold applies the ContainsFold predicate on the "role" field.
func RoleContainsFold(v string) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldContainsFold(FieldRole, v))
}

// ContributionEQ applies the EQ predicate on the "contribution" field.
func ContributionEQ(v int64) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldEQ(FieldContribution, v))
}

// ContributionNEQ applies the NEQ predicate on the "contribution" field.
func ContributionNEQ(v int64) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldNEQ(FieldContribution, v))
}

// ContributionIn applies the In predicate on the "contribution" field.
func ContributionIn(vs ...int64) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldIn(FieldContribution, vs...))
}

// ContributionNotIn applies the NotIn predicate on the "contribution" field.
func ContributionNotIn(vs ...int64) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldNotIn(FieldContribution, vs...))
}

// ContributionGT applies the GT predicate on the "contribution" field.
func ContributionGT(v int64) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldGT(FieldContribution, v))
}

// ContributionGTE applies the GTE predicate on the "contribution" field.
func ContributionGTE(v int64) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldGTE(FieldContribution, v))
}

// ContributionLT applies the LT predicate on the "contribution" field.
func ContributionLT(v int64) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldLT(FieldContribution, v))
}

// ContributionLTE applies the LTE predicate on the "contribution" field.
func ContributionLTE(v int64) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldLTE(FieldContribution, v))
}

// JoinedAtEQ applies the EQ predicate on the "joined_at" field.
func JoinedAtEQ(v time.Time) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldEQ(FieldJoinedAt, v))
}

// JoinedAtNEQ applies the NEQ predicate on the "joined_at" field.
func JoinedAtNEQ(v time.Time) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldNEQ(FieldJoinedAt, v))
}

// JoinedAtIn applies the In predicate on the "joined_at" field.
func JoinedAtIn(vs ...time.Time) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldIn(FieldJoinedAt, vs...))
}

// JoinedAtNotIn applies the NotIn predicate on the "joined_at" field.
func JoinedAtNotIn(vs ...time.Time) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldNotIn(FieldJoinedAt, vs...))
}

// JoinedAtGT applies the GT predicate on the "joined_at" field.
func JoinedAtGT(v time.Time) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldGT(FieldJoinedAt, v))
}

// JoinedAtGTE applies the GTE predicate on the "joined_at" field.
func JoinedAtGTE(v time.Time) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldGTE(FieldJoinedAt, v))
}

// JoinedAtLT applies the LT predicate on the "joined_at" field.
func JoinedAtLT(v time.Time) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldLT(FieldJoinedAt, v))
}

// JoinedAtLTE applies the LTE predicate on the "joined_at" field.
func JoinedAtLTE(v time.Time) predicate.VillageMember {
	return predicate.VillageMember(sql.FieldLTE(FieldJoinedAt, v))
}

// HasVillage applies the HasEdge predicate on the "village" edge.
func HasVillage() predicate.VillageMember {
	return predicate.VillageMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, VillageTable, VillageColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVillageWith applies the HasEdge predicate on the "village" edge with a given conditions (other predicates).
func HasVillageWith(preds ...predicate.Village) predicate.VillageMember {
	return predicate.VillageMember(func(s *sql.Selector) {
		step := newVillageStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.VillageMember {
	return predicate.VillageMember(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.VillageMember {
	return predicate.VillageMember(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.VillageMember) predicate.VillageMember {
	return predicate.VillageMember(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.VillageMember) predicate.VillageMember {
	return predicate.VillageMember(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.VillageMember) predicate.VillageMember {
	return predicate.VillageMember(sql.NotPredicates(p))
}
