// Code generated by ent, DO NOT EDIT.

package farm

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/schema"
)

const (
	// Label holds the string label denoting the farm type in the database.
	Label = "farm"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldOwnerID holds the string denoting the owner_id field in the database.
	FieldOwnerID = "owner_id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldLevel holds the string denoting the level field in the database.
	FieldLevel = "level"
	// FieldSpecialty holds the string denoting the specialty field in the database.
	FieldSpecialty = "specialty"
	// FieldPlots holds the string denoting the plots field in the database.
	FieldPlots = "plots"
	// FieldLastTickAt holds the string denoting the last_tick_at field in the database.
	FieldLastTickAt = "last_tick_at"
	// FieldCreatedAt holds the string denoting the created_at field in the database.
	FieldCreatedAt = "created_at"
	// EdgeOwner holds the string denoting the owner edge name in mutations.
	EdgeOwner = "owner"
	// EdgeBuildings holds the string denoting the buildings edge name in mutations.
	EdgeBuildings = "buildings"
	// EdgeAnimals holds the string denoting the animals edge name in mutations.
	EdgeAnimals = "animals"
	// Table holds the table name of the farm in the database.
	Table = "farms"
	// OwnerTable is the table that holds the owner relation/edge.
	OwnerTable = "farms"
	// OwnerInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	OwnerInverseTable = "users"
	// OwnerColumn is the table column denoting the owner relation/edge.
	OwnerColumn = "owner_id"
	// BuildingsTable is the table that holds the buildings relation/edge.
	BuildingsTable = "buildings"
	// BuildingsInverseTable is the table name for the Building entity.
	// It exists in this package in order to avoid circular dependency with the "building" package.
	BuildingsInverseTable = "buildings"
	// BuildingsColumn is the table column denoting the buildings relation/edge.
	BuildingsColumn = "farm_id"
	// AnimalsTable is the table that holds the animals relation/edge.
	AnimalsTable = "animals"
	// AnimalsInverseTable is the table name for the Animal entity.
	// It exists in this package in order to avoid circular dependency with the "animal" package.
	AnimalsInverseTable = "animals"
	// AnimalsColumn is the table column denoting the animals relation/edge.
	AnimalsColumn = "farm_id"
)

// Columns holds all SQL columns for farm fields.
var Columns = []string{
	FieldID,
	FieldOwnerID,
	FieldName,
	FieldLevel,
	FieldSpecialty,
	FieldPlots,
	FieldLastTickAt,
	FieldCreatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// NameValidator is a validator for the "name" field. It is called by the builders before save.
	NameValidator func(string) error
	// DefaultLevel holds the default value on creation for the "level" field.
	DefaultLevel int
	// LevelValidator is a validator for the "level" field. It is called by the builders before save.
	LevelValidator func(int) error
	// DefaultSpecialty holds the default value on creation for the "specialty" field.
	DefaultSpecialty []string
	// DefaultPlots holds the default value on creation for the "plots" field.
	DefaultPlots []schema.PlotState
	// DefaultLastTickAt holds the default value on creation for the "last_tick_at" field.
	DefaultLastTickAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "created_at" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the Farm queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByOwnerID orders the results by the owner_id field.
func ByOwnerID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldOwnerID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByLevel orders the results by the level field.
func ByLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLevel, opts...).ToFunc()
}

// ByLastTickAt orders the results by the last_tick_at field.
func ByLastTickAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLastTickAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the created_at field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByOwnerField orders the results by owner field.
func ByOwnerField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newOwnerStep(), sql.OrderByField(field, opts...))
	}
}

// ByBuildingsCount orders the results by buildings count.
func ByBuildingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBuildingsStep(), opts...)
	}
}

// ByBuildings orders the results by buildings terms.
func ByBuildings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBuildingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAnimalsCount orders the results by animals count.
func ByAnimalsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAnimalsStep(), opts...)
	}
}

// ByAnimals orders the results by animals terms.
func ByAnimals(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAnimalsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newOwnerStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(OwnerInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2O, true, OwnerTable, OwnerColumn),
	)
}
func newBuildingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BuildingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, BuildingsTable, BuildingsColumn),
	)
}
func newAnimalsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AnimalsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, false, AnimalsTable, AnimalsColumn),
	)
}
