// Code generated by ent, DO NOT EDIT.

package animal

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.Animal {
	return predicate.Animal(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.Animal {
	return predicate.Animal(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.Animal {
	return predicate.Animal(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.Animal {
	return predicate.Animal(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.Animal {
	return predicate.Animal(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.Animal {
	return predicate.Animal(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.Animal {
	return predicate.Animal(sql.FieldLTE(FieldID, id))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldUpdatedAt, v))
}

// FarmID applies equality check predicate on the "farm_id" field. It's identical to FarmIDEQ.
func FarmID(v uuid.UUID) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldFarmID, v))
}

// Type applies equality check predicate on the "type" field. It's identical to TypeEQ.
func Type(v string) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldType, v))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldName, v))
}

// Mood applies equality check predicate on the "mood" field. It's identical to MoodEQ.
func Mood(v int) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldMood, v))
}

// Health applies equality check predicate on the "health" field. It's identical to HealthEQ.
func Health(v int) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldHealth, v))
}

// LastFedAt applies equality check predicate on the "last_fed_at" field. It's identical to LastFedAtEQ.
func LastFedAt(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldLastFedAt, v))
}

// LastCleanedAt applies equality check predicate on the "last_cleaned_at" field. It's identical to LastCleanedAtEQ.
func LastCleanedAt(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldLastCleanedAt, v))
}

// LastProductAt applies equality check predicate on the "last_product_at" field. It's identical to LastProductAtEQ.
func LastProductAt(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldLastProductAt, v))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldLTE(FieldUpdatedAt, v))
}

// FarmIDEQ applies the EQ predicate on the "farm_id" field.
func FarmIDEQ(v uuid.UUID) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldFarmID, v))
}

// FarmIDNEQ applies the NEQ predicate on the "farm_id" field.
func FarmIDNEQ(v uuid.UUID) predicate.Animal {
	return predicate.Animal(sql.FieldNEQ(FieldFarmID, v))
}

// FarmIDIn applies the In predicate on the "farm_id" field.
func FarmIDIn(vs ...uuid.UUID) predicate.Animal {
	return predicate.Animal(sql.FieldIn(FieldFarmID, vs...))
}

// FarmIDNotIn applies the NotIn predicate on the "farm_id" field.
func FarmIDNotIn(vs ...uuid.UUID) predicate.Animal {
	return predicate.Animal(sql.FieldNotIn(FieldFarmID, vs...))
}

// TypeEQ applies the EQ predicate on the "type" field.
func TypeEQ(v string) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldType, v))
}

// TypeNEQ applies the NEQ predicate on the "type" field.
func TypeNEQ(v string) predicate.Animal {
	return predicate.Animal(sql.FieldNEQ(FieldType, v))
}

// TypeIn applies the In predicate on the "type" field.
func TypeIn(vs ...string) predicate.Animal {
	return predicate.Animal(sql.FieldIn(FieldType, vs...))
}

// TypeNotIn applies the NotIn predicate on the "type" field.
func TypeNotIn(vs ...string) predicate.Animal {
	return predicate.Animal(sql.FieldNotIn(FieldType, vs...))
}

// TypeGT applies the GT predicate on the "type" field.
func TypeGT(v string) predicate.Animal {
	return predicate.Animal(sql.FieldGT(FieldType, v))
}

// TypeGTE applies the GTE predicate on the "type" field.
func TypeGTE(v string) predicate.Animal {
	return predicate.Animal(sql.FieldGTE(FieldType, v))
}

// TypeLT applies the LT predicate on the "type" field.
func TypeLT(v string) predicate.Animal {
	return predicate.Animal(sql.FieldLT(FieldType, v))
}

// TypeLTE applies the LTE predicate on the "type" field.
func TypeLTE(v string) predicate.Animal {
	return predicate.Animal(sql.FieldLTE(FieldType, v))
}

// TypeContains applies the Contains predicate on the "type" field.
func TypeContains(v string) predicate.Animal {
	return predicate.Animal(sql.FieldContains(FieldType, v))
}

// TypeHasPrefix applies the HasPrefix predicate on the "type" field.
func TypeHasPrefix(v string) predicate.Animal {
	return predicate.Animal(sql.FieldHasPrefix(FieldType, v))
}

// TypeHasSuffix applies the HasSuffix predicate on the "type" field.
func TypeHasSuffix(v string) predicate.Animal {
	return predicate.Animal(sql.FieldHasSuffix(FieldType, v))
}

// TypeEqualFold applies the EqualFold predicate on the "type" field.
func TypeEqualFold(v string) predicate.Animal {
	return predicate.Animal(sql.FieldEqualFold(FieldType, v))
}

// TypeContainsFold applies the ContainsFold predicate on the "type" field.
func TypeContainsFold(v string) predicate.Animal {
	return predicate.Animal(sql.FieldContainsFold(FieldType, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Animal {
	return predicate.Animal(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Animal {
	return predicate.Animal(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Animal {
	return predicate.Animal(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Animal {
	return predicate.Animal(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Animal {
	return predicate.Animal(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Animal {
	return predicate.Animal(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Animal {
	return predicate.Animal(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Animal {
	return predicate.Animal(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Animal {
	return predicate.Animal(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Animal {
	return predicate.Animal(sql.FieldHasSuffix(FieldName, v))
}

// NameIsNil applies the IsNil predicate on the "name" field.
func NameIsNil() predicate.Animal {
	return predicate.Animal(sql.FieldIsNull(FieldName))
}

// NameNotNil applies the NotNil predicate on the "name" field.
func NameNotNil() predicate.Animal {
	return predicate.Animal(sql.FieldNotNull(FieldName))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Animal {
	return predicate.Animal(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Animal {
	return predicate.Animal(sql.FieldContainsFold(FieldName, v))
}

// MoodEQ applies the EQ predicate on the "mood" field.
func MoodEQ(v int) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldMood, v))
}

// MoodNEQ applies the NEQ predicate on the "mood" field.
func MoodNEQ(v int) predicate.Animal {
	return predicate.Animal(sql.FieldNEQ(FieldMood, v))
}

// MoodIn applies the In predicate on the "mood" field.
func MoodIn(vs ...int) predicate.Animal {
	return predicate.Animal(sql.FieldIn(FieldMood, vs...))
}

// MoodNotIn applies the NotIn predicate on the "mood" field.
func MoodNotIn(vs ...int) predicate.Animal {
	return predicate.Animal(sql.FieldNotIn(FieldMood, vs...))
}

// MoodGT applies the GT predicate on the "mood" field.
func MoodGT(v int) predicate.Animal {
	return predicate.Animal(sql.FieldGT(FieldMood, v))
}

// MoodGTE applies the GTE predicate on the "mood" field.
func MoodGTE(v int) predicate.Animal {
	return predicate.Animal(sql.FieldGTE(FieldMood, v))
}

// MoodLT applies the LT predicate on the "mood" field.
func MoodLT(v int) predicate.Animal {
	return predicate.Animal(sql.FieldLT(FieldMood, v))
}

// MoodLTE applies the LTE predicate on the "mood" field.
func MoodLTE(v int) predicate.Animal {
	return predicate.Animal(sql.FieldLTE(FieldMood, v))
}

// HealthEQ applies the EQ predicate on the "health" field.
func HealthEQ(v int) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldHealth, v))
}

// HealthNEQ applies the NEQ predicate on the "health" field.
func HealthNEQ(v int) predicate.Animal {
	return predicate.Animal(sql.FieldNEQ(FieldHealth, v))
}

// HealthIn applies the In predicate on the "health" field.
func HealthIn(vs ...int) predicate.Animal {
	return predicate.Animal(sql.FieldIn(FieldHealth, vs...))
}

// HealthNotIn applies the NotIn predicate on the "health" field.
func HealthNotIn(vs ...int) predicate.Animal {
	return predicate.Animal(sql.FieldNotIn(FieldHealth, vs...))
}

// HealthGT applies the GT predicate on the "health" field.
func HealthGT(v int) predicate.Animal {
	return predicate.Animal(sql.FieldGT(FieldHealth, v))
}

// HealthGTE applies the GTE predicate on the "health" field.
func HealthGTE(v int) predicate.Animal {
	return predicate.Animal(sql.FieldGTE(FieldHealth, v))
}

// HealthLT applies the LT predicate on the "health" field.
func HealthLT(v int) predicate.Animal {
	return predicate.Animal(sql.FieldLT(FieldHealth, v))
}

// HealthLTE applies the LTE predicate on the "health" field.
func HealthLTE(v int) predicate.Animal {
	return predicate.Animal(sql.FieldLTE(FieldHealth, v))
}

// LastFedAtEQ applies the EQ predicate on the "last_fed_at" field.
func LastFedAtEQ(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldLastFedAt, v))
}

// LastFedAtNEQ applies the NEQ predicate on the "last_fed_at" field.
func LastFedAtNEQ(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldNEQ(FieldLastFedAt, v))
}

// LastFedAtIn applies the In predicate on the "last_fed_at" field.
func LastFedAtIn(vs ...time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldIn(FieldLastFedAt, vs...))
}

// LastFedAtNotIn applies the NotIn predicate on the "last_fed_at" field.
func LastFedAtNotIn(vs ...time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldNotIn(FieldLastFedAt, vs...))
}

// LastFedAtGT applies the GT predicate on the "last_fed_at" field.
func LastFedAtGT(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldGT(FieldLastFedAt, v))
}

// LastFedAtGTE applies the GTE predicate on the "last_fed_at" field.
func LastFedAtGTE(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldGTE(FieldLastFedAt, v))
}

// LastFedAtLT applies the LT predicate on the "last_fed_at" field.
func LastFedAtLT(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldLT(FieldLastFedAt, v))
}

// LastFedAtLTE applies the LTE predicate on the "last_fed_at" field.
func LastFedAtLTE(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldLTE(FieldLastFedAt, v))
}

// LastFedAtIsNil applies the IsNil predicate on the "last_fed_at" field.
func LastFedAtIsNil() predicate.Animal {
	return predicate.Animal(sql.FieldIsNull(FieldLastFedAt))
}

// LastFedAtNotNil applies the NotNil predicate on the "last_fed_at" field.
func LastFedAtNotNil() predicate.Animal {
	return predicate.Animal(sql.FieldNotNull(FieldLastFedAt))
}

// LastCleanedAtEQ applies the EQ predicate on the "last_cleaned_at" field.
func LastCleanedAtEQ(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldLastCleanedAt, v))
}

// LastCleanedAtNEQ applies the NEQ predicate on the "last_cleaned_at" field.
func LastCleanedAtNEQ(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldNEQ(FieldLastCleanedAt, v))
}

// LastCleanedAtIn applies the In predicate on the "last_cleaned_at" field.
func LastCleanedAtIn(vs ...time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldIn(FieldLastCleanedAt, vs...))
}

// LastCleanedAtNotIn applies the NotIn predicate on the "last_cleaned_at" field.
func LastCleanedAtNotIn(vs ...time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldNotIn(FieldLastCleanedAt, vs...))
}

// LastCleanedAtGT applies the GT predicate on the "last_cleaned_at" field.
func LastCleanedAtGT(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldGT(FieldLastCleanedAt, v))
}

// LastCleanedAtGTE applies the GTE predicate on the "last_cleaned_at" field.
func LastCleanedAtGTE(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldGTE(FieldLastCleanedAt, v))
}

// LastCleanedAtLT applies the LT predicate on the "last_cleaned_at" field.
func LastCleanedAtLT(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldLT(FieldLastCleanedAt, v))
}

// LastCleanedAtLTE applies the LTE predicate on the "last_cleaned_at" field.
func LastCleanedAtLTE(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldLTE(FieldLastCleanedAt, v))
}

// LastCleanedAtIsNil applies the IsNil predicate on the "last_cleaned_at" field.
func LastCleanedAtIsNil() predicate.Animal {
	return predicate.Animal(sql.FieldIsNull(FieldLastCleanedAt))
}

// LastCleanedAtNotNil applies the NotNil predicate on the "last_cleaned_at" field.
func LastCleanedAtNotNil() predicate.Animal {
	return predicate.Animal(sql.FieldNotNull(FieldLastCleanedAt))
}

// LastProductAtEQ applies the EQ predicate on the "last_product_at" field.
func LastProductAtEQ(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldEQ(FieldLastProductAt, v))
}

// LastProductAtNEQ applies the NEQ predicate on the "last_product_at" field.
func LastProductAtNEQ(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldNEQ(FieldLastProductAt, v))
}

// LastProductAtIn applies the In predicate on the "last_product_at" field.
func LastProductAtIn(vs ...time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldIn(FieldLastProductAt, vs...))
}

// LastProductAtNotIn applies the NotIn predicate on the "last_product_at" field.
func LastProductAtNotIn(vs ...time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldNotIn(FieldLastProductAt, vs...))
}

// LastProductAtGT applies the GT predicate on the "last_product_at" field.
func LastProductAtGT(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldGT(FieldLastProductAt, v))
}

// LastProductAtGTE applies the GTE predicate on the "last_product_at" field.
func LastProductAtGTE(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldGTE(FieldLastProductAt, v))
}

// LastProductAtLT applies the LT predicate on the "last_product_at" field.
func LastProductAtLT(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldLT(FieldLastProductAt, v))
}

// LastProductAtLTE applies the LTE predicate on the "last_product_at" field.
func LastProductAtLTE(v time.Time) predicate.Animal {
	return predicate.Animal(sql.FieldLTE(FieldLastProductAt, v))
}

// LastProductAtIsNil applies the IsNil predicate on the "last_product_at" field.
func LastProductAtIsNil() predicate.Animal {
	return predicate.Animal(sql.FieldIsNull(FieldLastProductAt))
}

// LastProductAtNotNil applies the NotNil predicate on the "last_product_at" field.
func LastProductAtNotNil() predicate.Animal {
	return predicate.Animal(sql.FieldNotNull(FieldLastProductAt))
}

// HasFarm applies the HasEdge predicate on the "farm" edge.
func HasFarm() predicate.Animal {
	return predicate.Animal(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, FarmTable, FarmColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasFarmWith applies the HasEdge predicate on the "farm" edge with a given conditions (other predicates).
func HasFarmWith(preds ...predicate.Farm) predicate.Animal {
	return predicate.Animal(func(s *sql.Selector) {
		step := newFarmStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Animal) predicate.Animal {
	return predicate.Animal(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Animal) predicate.Animal {
	return predicate.Animal(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Animal) predicate.Animal {
	return predicate.Animal(sql.NotPredicates(p))
}
