// Code generated by ent, DO NOT EDIT.

package seasonscore

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
)

const (
	// Label holds the string label denoting the seasonscore type in the database.
	Label = "season_score"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldSeasonID holds the string denoting the season_id field in the database.
	FieldSeasonID = "season_id"
	// FieldUserID holds the string denoting the user_id field in the database.
	FieldUserID = "user_id"
	// FieldScoreOutput holds the string denoting the score_output field in the database.
	FieldScoreOutput = "score_output"
	// FieldScoreSocial holds the string denoting the score_social field in the database.
	FieldScoreSocial = "score_social"
	// FieldScoreCollection holds the string denoting the score_collection field in the database.
	FieldScoreCollection = "score_collection"
	// FieldScoreQuality holds the string denoting the score_quality field in the database.
	FieldScoreQuality = "score_quality"
	// FieldScoreTotal holds the string denoting the score_total field in the database.
	FieldScoreTotal = "score_total"
	// FieldFinalRank holds the string denoting the final_rank field in the database.
	FieldFinalRank = "final_rank"
	// FieldUpdatedAt holds the string denoting the updated_at field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgeSeason holds the string denoting the season edge name in mutations.
	EdgeSeason = "season"
	// EdgeUser holds the string denoting the user edge name in mutations.
	EdgeUser = "user"
	// Table holds the table name of the seasonscore in the database.
	Table = "season_scores"
	// SeasonTable is the table that holds the season relation/edge.
	SeasonTable = "season_scores"
	// SeasonInverseTable is the table name for the Season entity.
	// It exists in this package in order to avoid circular dependency with the "season" package.
	SeasonInverseTable = "seasons"
	// SeasonColumn is the table column denoting the season relation/edge.
	SeasonColumn = "season_id"
	// UserTable is the table that holds the user relation/edge.
	UserTable = "season_scores"
	// UserInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	UserInverseTable = "users"
	// UserColumn is the table column denoting the user relation/edge.
	UserColumn = "user_id"
)

// Columns holds all SQL columns for seasonscore fields.
var Columns = []string{
	FieldID,
	FieldSeasonID,
	FieldUserID,
	FieldScoreOutput,
	FieldScoreSocial,
	FieldScoreCollection,
	FieldScoreQuality,
	FieldScoreTotal,
	FieldFinalRank,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultScoreOutput holds the default value on creation for the "score_output" field.
	DefaultScoreOutput int64
	// ScoreOutputValidator is a validator for the "score_output" field. It is called by the builders before save.
	ScoreOutputValidator func(int64) error
	// DefaultScoreSocial holds the default value on creation for the "score_social" field.
	DefaultScoreSocial int64
	// ScoreSocialValidator is a validator for the "score_social" field. It is called by the builders before save.
	ScoreSocialValidator func(int64) error
	// DefaultScoreCollection holds the default value on creation for the "score_collection" field.
	DefaultScoreCollection int64
	// ScoreCollectionValidator is a validator for the "score_collection" field. It is called by the builders before save.
	ScoreCollectionValidator func(int64) error
	// DefaultScoreQuality holds the default value on creation for the "score_quality" field.
	DefaultScoreQuality int64
	// ScoreQualityValidator is a validator for the "score_quality" field. It is called by the builders before save.
	ScoreQualityValidator func(int64) error
	// DefaultScoreTotal holds the default value on creation for the "score_total" field.
	DefaultScoreTotal int64
	// ScoreTotalValidator is a validator for the "score_total" field. It is called by the builders before save.
	ScoreTotalValidator func(int64) error
	// DefaultUpdatedAt holds the default value on creation for the "updated_at" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updated_at" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() uuid.UUID
)

// OrderOption defines the ordering options for the SeasonScore queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// BySeasonID orders the results by the season_id field.
func BySeasonID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSeasonID, opts...).ToFunc()
}

// ByUserID orders the results by the user_id field.
func ByUserID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUserID, opts...).ToFunc()
}

// ByScoreOutput orders the results by the score_output field.
func ByScoreOutput(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScoreOutput, opts...).ToFunc()
}

// ByScoreSocial orders the results by the score_social field.
func ByScoreSocial(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScoreSocial, opts...).ToFunc()
}

// ByScoreCollection orders the results by the score_collection field.
func ByScoreCollection(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScoreCollection, opts...).ToFunc()
}

// ByScoreQuality orders the results by the score_quality field.
func ByScoreQuality(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScoreQuality, opts...).ToFunc()
}

// ByScoreTotal orders the results by the score_total field.
func ByScoreTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScoreTotal, opts...).ToFunc()
}

// ByFinalRank orders the results by the final_rank field.
func ByFinalRank(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinalRank, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updated_at field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// BySeasonField orders the results by season field.
func BySeasonField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSeasonStep(), sql.OrderByField(field, opts...))
	}
}

// ByUserField orders the results by user field.
func ByUserField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newUserStep(), sql.OrderByField(field, opts...))
	}
}
func newSeasonStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SeasonInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, SeasonTable, SeasonColumn),
	)
}
func newUserStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(UserInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
	)
}
