// Code generated by ent, DO NOT EDIT.

package seasonscore

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/google/uuid"
	"github.com/liukai/farmer/server/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id uuid.UUID) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id uuid.UUID) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id uuid.UUID) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...uuid.UUID) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...uuid.UUID) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id uuid.UUID) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id uuid.UUID) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id uuid.UUID) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id uuid.UUID) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldLTE(FieldID, id))
}

// SeasonID applies equality check predicate on the "season_id" field. It's identical to SeasonIDEQ.
func SeasonID(v uuid.UUID) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldEQ(FieldSeasonID, v))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v uuid.UUID) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldEQ(FieldUserID, v))
}

// ScoreOutput applies equality check predicate on the "score_output" field. It's identical to ScoreOutputEQ.
func ScoreOutput(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldEQ(FieldScoreOutput, v))
}

// ScoreSocial applies equality check predicate on the "score_social" field. It's identical to ScoreSocialEQ.
func ScoreSocial(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldEQ(FieldScoreSocial, v))
}

// ScoreCollection applies equality check predicate on the "score_collection" field. It's identical to ScoreCollectionEQ.
func ScoreCollection(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldEQ(FieldScoreCollection, v))
}

// ScoreQuality applies equality check predicate on the "score_quality" field. It's identical to ScoreQualityEQ.
func ScoreQuality(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldEQ(FieldScoreQuality, v))
}

// ScoreTotal applies equality check predicate on the "score_total" field. It's identical to ScoreTotalEQ.
func ScoreTotal(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldEQ(FieldScoreTotal, v))
}

// FinalRank applies equality check predicate on the "final_rank" field. It's identical to FinalRankEQ.
func FinalRank(v int) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldEQ(FieldFinalRank, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldEQ(FieldUpdatedAt, v))
}

// SeasonIDEQ applies the EQ predicate on the "season_id" field.
func SeasonIDEQ(v uuid.UUID) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldEQ(FieldSeasonID, v))
}

// SeasonIDNEQ applies the NEQ predicate on the "season_id" field.
func SeasonIDNEQ(v uuid.UUID) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNEQ(FieldSeasonID, v))
}

// SeasonIDIn applies the In predicate on the "season_id" field.
func SeasonIDIn(vs ...uuid.UUID) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldIn(FieldSeasonID, vs...))
}

// SeasonIDNotIn applies the NotIn predicate on the "season_id" field.
func SeasonIDNotIn(vs ...uuid.UUID) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNotIn(FieldSeasonID, vs...))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v uuid.UUID) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v uuid.UUID) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...uuid.UUID) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...uuid.UUID) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNotIn(FieldUserID, vs...))
}

// ScoreOutputEQ applies the EQ predicate on the "score_output" field.
func ScoreOutputEQ(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldEQ(FieldScoreOutput, v))
}

// ScoreOutputNEQ applies the NEQ predicate on the "score_output" field.
func ScoreOutputNEQ(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNEQ(FieldScoreOutput, v))
}

// ScoreOutputIn applies the In predicate on the "score_output" field.
func ScoreOutputIn(vs ...int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldIn(FieldScoreOutput, vs...))
}

// ScoreOutputNotIn applies the NotIn predicate on the "score_output" field.
func ScoreOutputNotIn(vs ...int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNotIn(FieldScoreOutput, vs...))
}

// ScoreOutputGT applies the GT predicate on the "score_output" field.
func ScoreOutputGT(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldGT(FieldScoreOutput, v))
}

// ScoreOutputGTE applies the GTE predicate on the "score_output" field.
func ScoreOutputGTE(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldGTE(FieldScoreOutput, v))
}

// ScoreOutputLT applies the LT predicate on the "score_output" field.
func ScoreOutputLT(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldLT(FieldScoreOutput, v))
}

// ScoreOutputLTE applies the LTE predicate on the "score_output" field.
func ScoreOutputLTE(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldLTE(FieldScoreOutput, v))
}

// ScoreSocialEQ applies the EQ predicate on the "score_social" field.
func ScoreSocialEQ(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldEQ(FieldScoreSocial, v))
}

// ScoreSocialNEQ applies the NEQ predicate on the "score_social" field.
func ScoreSocialNEQ(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNEQ(FieldScoreSocial, v))
}

// ScoreSocialIn applies the In predicate on the "score_social" field.
func ScoreSocialIn(vs ...int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldIn(FieldScoreSocial, vs...))
}

// ScoreSocialNotIn applies the NotIn predicate on the "score_social" field.
func ScoreSocialNotIn(vs ...int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNotIn(FieldScoreSocial, vs...))
}

// ScoreSocialGT applies the GT predicate on the "score_social" field.
func ScoreSocialGT(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldGT(FieldScoreSocial, v))
}

// ScoreSocialGTE applies the GTE predicate on the "score_social" field.
func ScoreSocialGTE(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldGTE(FieldScoreSocial, v))
}

// ScoreSocialLT applies the LT predicate on the "score_social" field.
func ScoreSocialLT(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldLT(FieldScoreSocial, v))
}

// ScoreSocialLTE applies the LTE predicate on the "score_social" field.
func ScoreSocialLTE(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldLTE(FieldScoreSocial, v))
}

// ScoreCollectionEQ applies the EQ predicate on the "score_collection" field.
func ScoreCollectionEQ(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldEQ(FieldScoreCollection, v))
}

// ScoreCollectionNEQ applies the NEQ predicate on the "score_collection" field.
func ScoreCollectionNEQ(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNEQ(FieldScoreCollection, v))
}

// ScoreCollectionIn applies the In predicate on the "score_collection" field.
func ScoreCollectionIn(vs ...int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldIn(FieldScoreCollection, vs...))
}

// ScoreCollectionNotIn applies the NotIn predicate on the "score_collection" field.
func ScoreCollectionNotIn(vs ...int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNotIn(FieldScoreCollection, vs...))
}

// ScoreCollectionGT applies the GT predicate on the "score_collection" field.
func ScoreCollectionGT(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldGT(FieldScoreCollection, v))
}

// ScoreCollectionGTE applies the GTE predicate on the "score_collection" field.
func ScoreCollectionGTE(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldGTE(FieldScoreCollection, v))
}

// ScoreCollectionLT applies the LT predicate on the "score_collection" field.
func ScoreCollectionLT(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldLT(FieldScoreCollection, v))
}

// ScoreCollectionLTE applies the LTE predicate on the "score_collection" field.
func ScoreCollectionLTE(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldLTE(FieldScoreCollection, v))
}

// ScoreQualityEQ applies the EQ predicate on the "score_quality" field.
func ScoreQualityEQ(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldEQ(FieldScoreQuality, v))
}

// ScoreQualityNEQ applies the NEQ predicate on the "score_quality" field.
func ScoreQualityNEQ(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNEQ(FieldScoreQuality, v))
}

// ScoreQualityIn applies the In predicate on the "score_quality" field.
func ScoreQualityIn(vs ...int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldIn(FieldScoreQuality, vs...))
}

// ScoreQualityNotIn applies the NotIn predicate on the "score_quality" field.
func ScoreQualityNotIn(vs ...int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNotIn(FieldScoreQuality, vs...))
}

// ScoreQualityGT applies the GT predicate on the "score_quality" field.
func ScoreQualityGT(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldGT(FieldScoreQuality, v))
}

// ScoreQualityGTE applies the GTE predicate on the "score_quality" field.
func ScoreQualityGTE(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldGTE(FieldScoreQuality, v))
}

// ScoreQualityLT applies the LT predicate on the "score_quality" field.
func ScoreQualityLT(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldLT(FieldScoreQuality, v))
}

// ScoreQualityLTE applies the LTE predicate on the "score_quality" field.
func ScoreQualityLTE(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldLTE(FieldScoreQuality, v))
}

// ScoreTotalEQ applies the EQ predicate on the "score_total" field.
func ScoreTotalEQ(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldEQ(FieldScoreTotal, v))
}

// ScoreTotalNEQ applies the NEQ predicate on the "score_total" field.
func ScoreTotalNEQ(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNEQ(FieldScoreTotal, v))
}

// ScoreTotalIn applies the In predicate on the "score_total" field.
func ScoreTotalIn(vs ...int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldIn(FieldScoreTotal, vs...))
}

// ScoreTotalNotIn applies the NotIn predicate on the "score_total" field.
func ScoreTotalNotIn(vs ...int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNotIn(FieldScoreTotal, vs...))
}

// ScoreTotalGT applies the GT predicate on the "score_total" field.
func ScoreTotalGT(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldGT(FieldScoreTotal, v))
}

// ScoreTotalGTE applies the GTE predicate on the "score_total" field.
func ScoreTotalGTE(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldGTE(FieldScoreTotal, v))
}

// ScoreTotalLT applies the LT predicate on the "score_total" field.
func ScoreTotalLT(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldLT(FieldScoreTotal, v))
}

// ScoreTotalLTE applies the LTE predicate on the "score_total" field.
func ScoreTotalLTE(v int64) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldLTE(FieldScoreTotal, v))
}

// FinalRankEQ applies the EQ predicate on the "final_rank" field.
func FinalRankEQ(v int) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldEQ(FieldFinalRank, v))
}

// FinalRankNEQ applies the NEQ predicate on the "final_rank" field.
func FinalRankNEQ(v int) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNEQ(FieldFinalRank, v))
}

// FinalRankIn applies the In predicate on the "final_rank" field.
func FinalRankIn(vs ...int) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldIn(FieldFinalRank, vs...))
}

// FinalRankNotIn applies the NotIn predicate on the "final_rank" field.
func FinalRankNotIn(vs ...int) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNotIn(FieldFinalRank, vs...))
}

// FinalRankGT applies the GT predicate on the "final_rank" field.
func FinalRankGT(v int) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldGT(FieldFinalRank, v))
}

// FinalRankGTE applies the GTE predicate on the "final_rank" field.
func FinalRankGTE(v int) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldGTE(FieldFinalRank, v))
}

// FinalRankLT applies the LT predicate on the "final_rank" field.
func FinalRankLT(v int) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldLT(FieldFinalRank, v))
}

// FinalRankLTE applies the LTE predicate on the "final_rank" field.
func FinalRankLTE(v int) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldLTE(FieldFinalRank, v))
}

// FinalRankIsNil applies the IsNil predicate on the "final_rank" field.
func FinalRankIsNil() predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldIsNull(FieldFinalRank))
}

// FinalRankNotNil applies the NotNil predicate on the "final_rank" field.
func FinalRankNotNil() predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNotNull(FieldFinalRank))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SeasonScore {
	return predicate.SeasonScore(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasSeason applies the HasEdge predicate on the "season" edge.
func HasSeason() predicate.SeasonScore {
	return predicate.SeasonScore(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, SeasonTable, SeasonColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasSeasonWith applies the HasEdge predicate on the "season" edge with a given conditions (other predicates).
func HasSeasonWith(preds ...predicate.Season) predicate.SeasonScore {
	return predicate.SeasonScore(func(s *sql.Selector) {
		step := newSeasonStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.SeasonScore {
	return predicate.SeasonScore(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.SeasonScore {
	return predicate.SeasonScore(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SeasonScore) predicate.SeasonScore {
	return predicate.SeasonScore(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SeasonScore) predicate.SeasonScore {
	return predicate.SeasonScore(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SeasonScore) predicate.SeasonScore {
	return predicate.SeasonScore(sql.NotPredicates(p))
}
